import type { GitHubDemandExecutionPack } from "../radar/githubDemandExecutionTypes";
import { deliveryWorkspaceSafetyFlags, type OperatorDeliveryWorkspace } from "./operatorDeliveryWorkspaceTypes";
const clean = (v: unknown, fallback: string) => (typeof v === "string" && v.trim() ? v : fallback);
export function buildOperatorDeliveryWorkspace(pack: GitHubDemandExecutionPack): OperatorDeliveryWorkspace {
  const now = new Date().toISOString(); const repo = pack.conversionPack?.candidate?.repository ?? {}; const title = clean(pack.offerTitle, "Manual GitHub delivery");
  const pt = [`Rascunho manual COPY_ONLY — ${title}`, `Repositório: ${clean((repo as any).fullName, "repo em revisão")}`, `Escopo incluído: ${pack.scopeIncluded.join("; ")}`, `Evidências a anexar manualmente: ${pack.evidenceChecklist.join("; ")}`, "Limite: este texto não envia mensagem, não cria PR, não comenta no GitHub e não confirma pagamento."].join("\n");
  const en = [`COPY_ONLY manual draft — ${title}`, `Repository: ${clean((repo as any).fullName, "repository under review")}`, `Included scope: ${pack.scopeIncluded.join("; ")}`, `Evidence to attach manually: ${pack.evidenceChecklist.join("; ")}`, "Boundary: this draft does not send messages, open PRs, comment on GitHub, or confirm payment."].join("\n");
  return { ...deliveryWorkspaceSafetyFlags, id:`odw_${pack.id}_${Date.now()}`, executionPackId:pack.id, conversionPackId:pack.conversionPackId, candidateId:pack.candidateId, status:"READY_FOR_OPERATOR", source:"OPERATOR_DELIVERY_WORKSPACE_P0", sourceRepository:{ fullName:(repo as any).fullName, url:(repo as any).url, issueUrl:(pack.conversionPack?.candidate as any)?.url, title:(pack.conversionPack?.candidate as any)?.title }, executionPack:pack, createdAt:now, updatedAt:now, operatorBrief:`Prepare manual delivery for ${title}. Keep all outputs preview-only and operator-reviewed before any external action.`, ptBrDeliveryDraft:pt, enUsDeliveryDraft:en, evidenceChecklist:pack.evidenceChecklist, deliveryChecklist:pack.deliveryArtifacts, validationChecklist:pack.validationChecklist, releaseChecklist:["Review final diff/evidence manually", "Prepare release note draft only", "Confirm no GitHub write automation is enabled"], ledgerPreview:{ ...pack.ledgerPreview, status:"LEDGER_PREVIEW_CREATED", revenueReceived:false, rewardNotGuaranteed:true }, riskWarnings:[...pack.riskWarnings, "No external contact automation; operator must review/copy manually.", "No payment provider call; reward is not guaranteed."], scopeIncluded:pack.scopeIncluded, scopeExcluded:pack.scopeExcluded, manualActionPlan:["Review execution pack scope", "Copy PT-BR or EN-US draft manually", "Prepare evidence preview", "Prepare validation/release/ledger previews", "Only then decide manual external next steps outside GXEON"], nextManualAction:"Review the operator brief and copy a draft only after manual approval.", actionHistory:[{ actionType:"WORKSPACE_CREATED", status:"READY_FOR_OPERATOR", timestamp:now, previewId:pack.id }] };
}
