import type { GitHubDemandExecutionPack } from "../radar/githubDemandExecutionTypes";

export type OperatorDeliveryWorkspaceStatus = "DRAFT" | "READY_FOR_OPERATOR" | "EVIDENCE_PREPARED" | "VALIDATION_PREVIEW_CREATED" | "RELEASE_PREVIEW_CREATED" | "LEDGER_PREVIEW_CREATED" | "ARCHIVED";
export type DeliveryWorkspaceActionType = "WORKSPACE_CREATED" | "EVIDENCE_PREVIEW" | "VALIDATION_PREVIEW" | "RELEASE_PREVIEW" | "LEDGER_PREVIEW";
export type DeliveryWorkspaceSafetyFlags = { mode:"PREVIEW_ONLY"; copyOnly:true; manualReviewRequired:true; githubWriteDisabled:true; externalContactDisabled:true; paymentProviderDisabled:true; rewardNotGuaranteed:true; runtimeExecutionDisabled:true; noRepoClone:true; noExternalCodeExecution:true; persistence:"IN_MEMORY_P0" };
export const deliveryWorkspaceSafetyFlags: DeliveryWorkspaceSafetyFlags = { mode:"PREVIEW_ONLY", copyOnly:true, manualReviewRequired:true, githubWriteDisabled:true, externalContactDisabled:true, paymentProviderDisabled:true, rewardNotGuaranteed:true, runtimeExecutionDisabled:true, noRepoClone:true, noExternalCodeExecution:true, persistence:"IN_MEMORY_P0" };
export type DeliveryWorkspaceActionRecord = { actionType: DeliveryWorkspaceActionType; status: OperatorDeliveryWorkspaceStatus; timestamp: string; previewId?: string };
export type OperatorDeliveryWorkspace = DeliveryWorkspaceSafetyFlags & { id:string; executionPackId:string; conversionPackId:string; candidateId:string; status:OperatorDeliveryWorkspaceStatus; source:"OPERATOR_DELIVERY_WORKSPACE_P0"; sourceRepository:{ fullName?:string; url?:string; issueUrl?:string; title?:string }; executionPack: GitHubDemandExecutionPack; createdAt:string; updatedAt:string; operatorBrief:string; ptBrDeliveryDraft:string; enUsDeliveryDraft:string; evidenceChecklist:string[]; deliveryChecklist:string[]; validationChecklist:string[]; releaseChecklist:string[]; ledgerPreview:Record<string, unknown>; riskWarnings:string[]; scopeIncluded:string[]; scopeExcluded:string[]; manualActionPlan:string[]; nextManualAction:string; actionHistory:DeliveryWorkspaceActionRecord[] };
export type DeliveryWorkspaceActionResult = { actionType:DeliveryWorkspaceActionType; status:OperatorDeliveryWorkspaceStatus; workspaceId:string; executionPackId:string; mode:"PREVIEW_ONLY"; safetyFlags:DeliveryWorkspaceSafetyFlags; nextManualAction:string; preview:Record<string, unknown> };
