import { OperatorAssistantPanel } from "@/components/operatorAssistant/OperatorAssistantPanel";import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { BrainCircuit, ClipboardList, HandCoins, Plug, ShieldCheck, Target } from "lucide-react";
import { fetchCommandBrainStatus, fetchRevenueSprintOfferPacks, startMinimumRevenueSprint, type MinimumRevenueSprintRecord, type RevenueOfferPack, type RevenueSprintStatusResponse } from "@/services/commandBrainService";
import { fetchConnectorBrainSummary, type ConnectorBrainSummary } from "@/services/realConnectorService";
import { revenueCloseLoopService } from "@/services/revenueCloseLoopService";

export default function CommandBrainPage() {
  const [status, setStatus] = useState<RevenueSprintStatusResponse | null>(null);
  const [offerPacks, setOfferPacks] = useState<RevenueOfferPack[]>([]);
  const [sprint, setSprint] = useState<MinimumRevenueSprintRecord | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [connectorSummary, setConnectorSummary] = useState<ConnectorBrainSummary | null>(null);
  const [closeLoopSummary, setCloseLoopSummary] = useState<any>({});
  const [form, setForm] = useState({ targetAmountBrl: "100", deadlineLabel: "tomorrow 9am", preferredPayoutMethod: "MERCADO_PAGO_PIX_MANUAL", mercadoPagoManualLink: "", pixKeyLabel: "", operatorNotes: "urgent debt payment; manual execution only; no payment provider API" });
  useEffect(() => { const c = new AbortController(); Promise.all([fetchCommandBrainStatus(c.signal), fetchRevenueSprintOfferPacks(c.signal), fetchConnectorBrainSummary(c.signal)]).then(([s, packs, connectors]) => { setStatus(s); setOfferPacks(packs.offerPacks); setConnectorSummary(connectors); }).catch((e) => setError(e instanceof Error ? e.message : "COMMAND_BRAIN_LOAD_FAILED")); revenueCloseLoopService.summary().then((r) => setCloseLoopSummary(r.data ?? {})); return () => c.abort(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); try { const result = await startMinimumRevenueSprint({ ...form, targetAmountBrl: Number(form.targetAmountBrl) || 100, preferredPayoutMethod: "MERCADO_PAGO_PIX_MANUAL" }); setSprint(result.sprint); setOfferPacks(result.sprint.offerPacks); } catch (e) { setError(e instanceof Error ? e.message : "REVENUE_SPRINT_START_FAILED"); } }
  const activePacks = sprint?.offerPacks ?? offerPacks;
  const routes = sprint?.actionPlan ?? [];
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[2rem] border border-amber-300/20 bg-slate-950/90 p-6 shadow-2xl shadow-amber-950/20">
      <div className="relative z-10 mb-4 flex flex-wrap gap-2"><Link href="/ops/r100-war-room" className="inline-flex rounded-2xl border border-emerald-300/30 px-4 py-2 text-sm font-bold text-emerald-100">Open R$100 War Room</Link><Link href={(closeLoopSummary.activeCloseLoops ?? 0) > 0 ? "/ops/revenue-close-loop" : "/ops/prospects"} className="inline-flex rounded-2xl bg-emerald-300 px-4 py-2 text-sm font-black text-slate-950">{(closeLoopSummary.activeCloseLoops ?? 0) > 0 ? "Continuar Fechamento R$100" : "Criar ciclo a partir de Prospect"}</Link><span className="rounded-2xl border border-emerald-300/20 px-4 py-2 text-xs font-bold text-emerald-100">Ativos {closeLoopSummary.activeCloseLoops ?? 0} · Preview R$ {closeLoopSummary.previewRevenueBrl ?? 0} · Confirmado R$ {closeLoopSummary.operatorConfirmedRevenueBrl ?? 0}</span></div>
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_12%,rgba(245,158,11,0.22),transparent_33%),radial-gradient(circle_at_15%_25%,rgba(34,211,238,0.14),transparent_30%)]" />
      <div className="relative space-y-5">
        <div className="flex flex-wrap gap-2">{["PREVIEW_ONLY", "MANUAL_FIRST", "REVENUE_SPRINT", "PIX_MANUAL", "NO_PROVIDER_API"].map((b) => <Badge key={b} className="border-amber-300/30 bg-amber-400/10 text-amber-100">{b}</Badge>)}</div>
        <div><p className="text-xs uppercase tracking-[0.45em] text-amber-200/70">Central command for monetization, priorities and next best action</p><h1 className="mt-2 flex items-center gap-3 text-4xl font-black text-white md:text-6xl"><BrainCircuit className="h-10 w-10 text-amber-200" />GXEON Command Brain P0</h1><p className="mt-3 max-w-4xl text-slate-300">Safe manual-first command layer for generating a minimum R$100 revenue target with offer packs, manual Pix/Mercado Pago instructions, evidence checklist and ledger preview. No checkout, no automatic send, no provider verification.</p></div>
        <div className="grid gap-3 md:grid-cols-3"><Card className="border-emerald-300/20 bg-emerald-400/10"><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.25em] text-emerald-100">Primary objective</p><p className="mt-2 text-2xl font-black text-white">Generate R$100 minimum revenue</p></CardContent></Card><Card className="border-cyan-300/20 bg-cyan-400/10"><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.25em] text-cyan-100">Fastest route</p><p className="mt-2 text-2xl font-black text-white">{status?.fastestRoute ?? "DIRECT_PIX_OFFER"}</p></CardContent></Card><Card className="border-white/10 bg-white/[0.04]"><CardContent className="p-4"><p className="text-xs uppercase tracking-[0.25em] text-slate-300">Mode</p><p className="mt-2 text-2xl font-black text-white">PREVIEW_ONLY</p></CardContent></Card></div>
        {error && <p className="rounded-2xl border border-red-300/25 bg-red-500/10 p-3 text-sm text-red-100">{error}</p>}
      </div>
    </section>

    <section className="rounded-[2rem] border border-cyan-300/20 bg-cyan-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.35em] text-cyan-200/70">Connector readiness</p><h2 className="text-2xl font-bold text-white">Real monetization blockers</h2><p className="mt-1 text-sm text-cyan-50/80">Next for R$100 sprint: {connectorSummary?.nextConnectorForR100Sprint ?? "Mercado Pago manual link / Pix manual first"}</p><p className="mt-2 text-xs text-cyan-100">Top blockers: {connectorSummary?.topBlockers.map((b) => b.label).join(", ") || "loading"}</p></div><Link href="/ops/connectors"><Button className="bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Plug className="mr-2 h-4 w-4" />Open Connector Command Center</Button></Link></div></section>

    <section className="rounded-[2rem] border border-emerald-300/20 bg-emerald-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.35em] text-emerald-200/70">GitHub Demand execution packs</p><h2 className="text-2xl font-bold text-white">{status?.githubDemandExecution?.readyCount ?? 0} execution-ready pack(s)</h2><p className="mt-1 text-sm text-emerald-50/80">Top R$100 sprint route: {status?.githubDemandExecution?.topRouteForR100Sprint?.route ?? "Generate an execution pack from GitHub Demand"}</p><p className="mt-2 text-xs text-emerald-100">Revenue is not claimed; all handoffs remain manual previews.</p></div><Link href="/ops/github-demand"><Button className="bg-emerald-300 text-slate-950 hover:bg-emerald-200">Open GitHub Demand</Button></Link></div></section>

    <section className="rounded-[2rem] border border-fuchsia-300/20 bg-fuchsia-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.35em] text-fuchsia-200/70">Manual Prospect readiness</p><h2 className="text-2xl font-bold text-white">{(status as any)?.manualProspects?.total ?? 0} manual prospect(s)</h2><p className="mt-1 text-sm text-fuchsia-50/80">Hot: {(status as any)?.manualProspects?.hotProspectsCount ?? 0}; waiting: {(status as any)?.manualProspects?.waitingResponseCount ?? 0}; accepted: {(status as any)?.manualProspects?.acceptedManualCount ?? 0}. Top R$100 prospect: {(status as any)?.manualProspects?.topR100Prospect?.displayNameOrLabel ?? "none yet"}.</p></div><Link href="/ops/prospects"><Button className="bg-fuchsia-300 text-slate-950 hover:bg-fuchsia-200">Open Prospect Pipeline</Button></Link></div></section>

    <section className="rounded-[2rem] border border-cyan-300/20 bg-cyan-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.35em] text-cyan-200/70">Client Offer Send readiness</p><h2 className="text-2xl font-bold text-white">{(status as any)?.clientOfferSend?.clientOfferPacksReadyCount ?? 0} ready offer pack(s)</h2><p className="mt-1 text-sm text-cyan-50/80">Manual sent: {(status as any)?.clientOfferSend?.manualOfferSentCount ?? 0}; waiting response: {(status as any)?.clientOfferSend?.waitingResponseManualCount ?? 0}. Top R$100 pack: {(status as any)?.clientOfferSend?.topR100SprintPack?.title ?? "none yet"}.</p></div><Link href="/ops/client-offers"><Button className="bg-cyan-300 text-slate-950 hover:bg-cyan-200">Open Client Offers</Button></Link></div></section>

    <section className="rounded-[2rem] border border-amber-300/20 bg-amber-400/10 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.35em] text-amber-200/70">Manual Payment Request readiness</p><h2 className="text-2xl font-bold text-white">{(status as any)?.manualPayment?.manualPaymentReadyCount ?? 0} ready request(s)</h2><p className="mt-1 text-sm text-amber-50/80">Expected preview total: R$ {(status as any)?.manualPayment?.manualPaymentTotalExpectedPreviewBrl ?? 0}. Real revenue remains R$0 inside P0.</p></div><Link href="/ops/manual-payment"><Button className="bg-amber-300 text-slate-950 hover:bg-amber-200">Open Manual Payment Center</Button></Link></div></section>
    <section className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><Card className="border-amber-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white">Start R$100 Revenue Sprint</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="space-y-3"><Input type="number" value={form.targetAmountBrl} onChange={(e) => setForm({ ...form, targetAmountBrl: e.target.value })} /><Input value={form.deadlineLabel} onChange={(e) => setForm({ ...form, deadlineLabel: e.target.value })} placeholder="Deadline" /><Input value="Mercado Pago / Pix manual" readOnly /><Input value={form.mercadoPagoManualLink} onChange={(e) => setForm({ ...form, mercadoPagoManualLink: e.target.value })} placeholder="Optional manual payment link (paste manually)" /><Input value={form.pixKeyLabel} onChange={(e) => setForm({ ...form, pixKeyLabel: e.target.value })} placeholder="Optional Pix key label (not a secret)" /><Textarea value={form.operatorNotes} onChange={(e) => setForm({ ...form, operatorNotes: e.target.value })} /><Button className="w-full bg-amber-300 font-black text-slate-950 hover:bg-amber-200"><Target className="mr-2 h-4 w-4" />Start R$100 Revenue Sprint</Button></form></CardContent></Card>
    <Card className="border-emerald-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white">Fastest safe routes</CardTitle></CardHeader><CardContent className="space-y-3">{(routes.length ? routes : [{ rank: 1, label: "Direct Pix/Mercado Pago Offer", description: "Sell a small service manually.", target: "2 x R$50 or 1 x R$100", estimatedSpeed: "Hoje", manualSteps: ["Copy offer", "Send manually", "Confirm outside GXEON"], riskNotes: ["Revenue not guaranteed"] }]).map((r) => <div key={r.rank} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4"><p className="font-bold text-white">#{r.rank} {r.label}</p><p className="text-sm text-slate-300">{r.description}</p><p className="text-xs text-amber-100">{r.target} · {r.estimatedSpeed}</p></div>)}</CardContent></Card></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{activePacks.map((pack) => <Card key={pack.id} className="border-white/10 bg-slate-950/75"><CardHeader><CardTitle className="text-white">{pack.title}</CardTitle></CardHeader><CardContent className="space-y-3"><Badge className="bg-emerald-400/10 text-emerald-100">R${pack.priceBrl} · {pack.targetSales} venda(s)</Badge><p className="text-sm text-slate-300">{pack.deliverables.join(" · ")}</p><Textarea readOnly value={pack.readyToCopyMessage} className="min-h-36 text-xs" /></CardContent></Card>)}</section>
    {sprint && <section className="grid gap-4 lg:grid-cols-3"><Card className="border-cyan-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white"><HandCoins className="mr-2 inline h-4 w-4" />Manual payment instruction</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-300">{sprint.paymentInstruction.instructionText}</p></CardContent></Card><Card className="border-amber-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white"><ClipboardList className="mr-2 inline h-4 w-4" />Evidence checklist</CardTitle></CardHeader><CardContent><ul className="space-y-2 text-sm text-slate-300">{sprint.evidenceChecklist.map((item) => <li key={item}>• {item}</li>)}</ul></CardContent></Card><Card className="border-emerald-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white"><ShieldCheck className="mr-2 inline h-4 w-4" />Ledger preview</CardTitle></CardHeader><CardContent><p className="text-3xl font-black text-white">R${sprint.ledgerPreview.expectedGrossBrl}</p><p className="text-sm text-slate-300">{sprint.ledgerPreview.previewNote}</p><p className="mt-3 text-xs text-emerald-100">Next: {sprint.nextBestAction}</p></CardContent></Card></section>}
    <div className="flex flex-wrap gap-3"><Link href="/ops/monetization"><Button variant="outline" className="border-amber-300/30 text-amber-100">Monetization</Button></Link><Link href="/ops/manual-payment"><Button variant="outline" className="border-amber-300/30 text-amber-100">Manual Payment</Button></Link><Link href="/ops/web3-tasks"><Button variant="outline" className="border-cyan-300/30 text-cyan-100">Web3 Tasks</Button></Link><Link href="/ops/agent-economy"><Button variant="outline" className="border-emerald-300/30 text-emerald-100">Agent Economy</Button></Link><Link href="/ops/github-demand"><Button variant="outline" className="border-cyan-300/30 text-cyan-100">GitHub Demand</Button></Link><Link href="/ops/client-offers"><Button variant="outline" className="border-cyan-300/30 text-cyan-100">Client Offers</Button></Link><Link href="/ops/prospects"><Button variant="outline" className="border-fuchsia-300/30 text-fuchsia-100">Prospects</Button></Link></div>
  </div>;
}
