import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Github, PackageCheck, ShieldCheck } from "lucide-react";
import { GitHubDemandActionResultPanel } from "@/components/github-demand/GitHubDemandActionResultPanel";
import { GitHubDemandConversionPackCard } from "@/components/github-demand/GitHubDemandConversionPackCard";
import { GitHubDemandExecutionPackCard } from "@/components/github-demand/GitHubDemandExecutionPackCard";
import { createBrainRevenueSprintPreviewFromConversionPack, createBrokerPreviewFromExecutionPack, createExecutionCenterPreviewFromExecutionPack, createGitHubDemandPipelinePreview, createLedgerPreviewFromExecutionPack, createOpportunityFromConversionPack, createReleasePreviewFromExecutionPack, createTaskPreviewFromConversionPack, createTaskPreviewFromExecutionPack, createValidationPreviewFromExecutionPack, fetchGitHubDemandConversionPacks, fetchGitHubDemandExecutionPacks, fetchGitHubDemandPipelinePreviews, fetchGitHubDemandQueryPacks, fetchGitHubDemandStatus, generateGitHubDemandConversionPack, generateGitHubDemandExecutionPack, searchGitHubDemandPreview, type ConversionActionResult, type GitHubDemandCandidate, type GitHubDemandPipelinePreview, type GitHubDemandQueryPack } from "@/services/githubDemandService";

export default function GitHubDemandRadarPage(){
 const [packs,setPacks]=useState<GitHubDemandQueryPack[]>([]); const [query,setQuery]=useState(""); const [candidates,setCandidates]=useState<GitHubDemandCandidate[]>([]); const [pipelines,setPipelines]=useState<GitHubDemandPipelinePreview[]>([]); const [conversionPacks,setConversionPacks]=useState<any[]>([]); const [executionPacks,setExecutionPacks]=useState<any[]>([]); const [executionResult,setExecutionResult]=useState<any>(null); const [status,setStatus]=useState<any>(null); const [msg,setMsg]=useState<string|null>(null); const [err,setErr]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [loadingAction,setLoadingAction]=useState<{id:string;kind:string}|null>(null); const [lastActionResult,setLastActionResult]=useState<ConversionActionResult|null>(null);
 useEffect(()=>{const c=new AbortController(); Promise.all([fetchGitHubDemandStatus(c.signal),fetchGitHubDemandQueryPacks(c.signal),fetchGitHubDemandPipelinePreviews(c.signal),fetchGitHubDemandConversionPacks(c.signal),fetchGitHubDemandExecutionPacks(c.signal)]).then(([s,p,l,cp,ep])=>{setStatus(s);setPacks(p.queryPacks);setPipelines(l.pipelinePreviews);setConversionPacks(cp.conversionPacks);setExecutionPacks(ep.executionPacks)}).catch(()=>{}); return()=>c.abort();},[]);
 const summary=useMemo(()=>({total:conversionPacks.length,opportunities:conversionPacks.filter((p:any)=>p.status==="OPPORTUNITY_PREVIEW_CREATED"||p.actionHistory?.some((a:any)=>a.status==="OPPORTUNITY_PREVIEW_CREATED")).length,tasks:conversionPacks.filter((p:any)=>p.status==="TASK_PREVIEW_CREATED"||p.actionHistory?.some((a:any)=>a.status==="TASK_PREVIEW_CREATED")).length,brain:conversionPacks.filter((p:any)=>p.status==="BRAIN_SPRINT_PREVIEW_CREATED"||p.actionHistory?.some((a:any)=>a.status==="BRAIN_SPRINT_PREVIEW_CREATED")).length,pending:conversionPacks.filter((p:any)=>!p.actionHistory?.length&&p.status==="READY_FOR_MANUAL_REVIEW").length,executionPacks:executionPacks.length,broker:executionPacks.filter((p:any)=>p.status==="BROKER_ROUTE_PREPARED").length,execution:executionPacks.filter((p:any)=>p.status==="EXECUTION_PREVIEW_CREATED").length,validation:executionPacks.filter((p:any)=>p.status==="VALIDATION_PREVIEW_CREATED").length,release:executionPacks.filter((p:any)=>p.status==="RELEASE_PREVIEW_CREATED").length,ledger:executionPacks.filter((p:any)=>p.actionHistory?.some((a:any)=>a.actionType==="LEDGER_PREVIEW")).length}),[conversionPacks,executionPacks]);
 const markPack=(id:string,status:string)=>setConversionPacks((items)=>items.map((p:any)=>p.id===id?{...p,status,actionHistory:[...(p.actionHistory??[]),{status,timestamp:new Date().toISOString()}]}:p));
 async function search(packId?:string){setLoading(true);setErr(null);setMsg(null);try{const r=await searchGitHubDemandPreview(packId?{queryPackId:packId,limit:5}:{query,limit:5}); setCandidates(r.candidates); setMsg(`Search preview returned ${r.candidates.length} candidate(s). No GitHub write occurred.`)}catch(e){setErr(e instanceof Error?e.message:"GITHUB_DEMAND_SEARCH_FAILED")}finally{setLoading(false)}}
 async function pipe(c:GitHubDemandCandidate){try{const r=await createGitHubDemandPipelinePreview(c); setPipelines([r.pipelinePreview,...pipelines.filter(p=>p.id!==r.pipelinePreview.id)]); setMsg(`Pipeline preview ${r.pipelinePreview.id} created in memory only.`)}catch(e){setErr(e instanceof Error?e.message:"PIPELINE_PREVIEW_FAILED")}}
 async function conversion(id:string){try{const r=await generateGitHubDemandConversionPack(id); setConversionPacks([r.conversionPack,...conversionPacks.filter((p:any)=>p.id!==r.conversionPack.id)]); setMsg("Readable conversion pack generated. COPY_ONLY. DO_NOT_AUTO_SEND.")}catch(e){setErr(e instanceof Error?e.message:"CONVERSION_PACK_FAILED")}}
 async function handleCreateOpportunity(id:string,operatorConfirmed:boolean){setLoadingAction({id,kind:"opportunity"});setErr(null);try{const r=await createOpportunityFromConversionPack(id,operatorConfirmed); setLastActionResult(r.actionResult); markPack(id,r.actionResult.status); setMsg(`${r.actionResult.status}: ${r.actionResult.nextManualAction}`)}catch(e){setErr(e instanceof Error?e.message:"OPPORTUNITY_PREVIEW_FAILED")}finally{setLoadingAction(null)}}
 async function handleCreateTaskPreview(id:string){setLoadingAction({id,kind:"task"});setErr(null);try{const r=await createTaskPreviewFromConversionPack(id); setLastActionResult(r.actionResult); markPack(id,r.actionResult.status); setMsg(`${r.actionResult.status}: ${r.actionResult.taskPreview.title}`)}catch(e){setErr(e instanceof Error?e.message:"TASK_PREVIEW_FAILED")}finally{setLoadingAction(null)}}
 async function executionPack(id:string){try{const r=await generateGitHubDemandExecutionPack(id); setExecutionPacks([r.executionPack,...executionPacks.filter((p:any)=>p.id!==r.executionPack.id)]); setMsg("Execution pack generated. PREVIEW_ONLY internal draft.")}catch(e){setErr(e instanceof Error?e.message:"EXECUTION_PACK_FAILED")}}
 async function handleExecutionAction(id:string,kind:string){setLoadingAction({id,kind});setErr(null);try{const map:any={task:createTaskPreviewFromExecutionPack,broker:createBrokerPreviewFromExecutionPack,execution:createExecutionCenterPreviewFromExecutionPack,validation:createValidationPreviewFromExecutionPack,release:createReleasePreviewFromExecutionPack,ledger:createLedgerPreviewFromExecutionPack}; const r=await map[kind](id); setExecutionResult(r.actionResult); setExecutionPacks(items=>items.map((p:any)=>p.id===id?{...p,status:r.actionResult.status,actionHistory:[...(p.actionHistory??[]),{actionType:r.actionResult.actionType,status:r.actionResult.status,timestamp:new Date().toISOString()}]}:p)); setMsg(`${r.actionResult.actionType}: ${r.actionResult.nextManualAction}`)}catch(e){setErr(e instanceof Error?e.message:"EXECUTION_ACTION_FAILED")}finally{setLoadingAction(null)}}
 async function handleSendToBrain(id:string){setLoadingAction({id,kind:"brain"});setErr(null);try{const r=await createBrainRevenueSprintPreviewFromConversionPack(id); setLastActionResult(r.actionResult); markPack(id,r.actionResult.status); setMsg(`${r.actionResult.status}: ${r.actionResult.nextBestAction}`)}catch(e){setErr(e instanceof Error?e.message:"BRAIN_SPRINT_PREVIEW_FAILED")}finally{setLoadingAction(null)}}
 return <div className="space-y-6"><section className="rounded-[2rem] border border-cyan-300/20 bg-slate-950/85 p-6"><div className="flex flex-wrap gap-2">{["PREVIEW_ONLY","COPY_ONLY","DO_NOT_AUTO_SEND","NO_GITHUB_WRITE","NO_AUTO_CONTACT","NO_PAYMENT","REWARD_NOT_GUARANTEED"].map(b=><Badge key={b} className="border-cyan-300/30 bg-cyan-400/10 text-cyan-100">{b}</Badge>)}</div><h1 className="mt-3 text-4xl font-black text-white md:text-6xl"><Github className="mr-3 inline h-10 w-10 text-cyan-200"/>GitHub Demand Conversion Pack P0</h1><p className="mt-3 max-w-4xl text-slate-300">Readable PT-BR/EN-US manual commercial offers, bounty execution plans, price suggestions, scope, evidence, delivery, ledger and Brain Sprint previews. Manual-first only: no comments, PRs, contact automation or payments.</p><div className="mt-4 flex flex-wrap gap-3"><Badge variant="outline" className="border-emerald-300/30 text-emerald-100">{status?.status??"loading"}</Badge><Link href="/ops/radar-x"><Button variant="outline" className="border-white/20 text-white">Back to Radar X</Button></Link></div></section>{err&&<p className="rounded-2xl border border-red-300/30 bg-red-500/10 p-3 text-red-100">{err}</p>}{msg&&<p className="rounded-2xl border border-emerald-300/30 bg-emerald-500/10 p-3 text-emerald-100">{msg}</p>}
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{packs.map(p=><Card key={p.id} className="border-cyan-300/20 bg-slate-950/75"><CardHeader><CardTitle className="text-white">{p.label}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-300"><Badge className="bg-amber-300/10 text-amber-100">{p.monetizationRouteHint}</Badge><p>{p.operatorUseCase}</p><p className="text-xs text-slate-400">{p.query}</p><Button disabled={loading} onClick={()=>search(p.id)} className="w-full bg-cyan-300 text-slate-950">Search Preview</Button></CardContent></Card>)}</section>
 <Card className="border-white/10 bg-slate-950/75"><CardHeader><CardTitle className="text-white">Manual query input</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 md:flex-row"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'"MCP" "help wanted"'} className="border-white/10 bg-slate-950 text-white"/><Button disabled={loading||!query.trim()} onClick={()=>search()} className="bg-cyan-300 text-slate-950">Search Preview</Button></CardContent></Card>
 <section className="space-y-4"><h2 className="text-2xl font-black text-white">Demand candidates</h2>{candidates.map(c=><Card key={c.id} className="border-cyan-300/20 bg-slate-950/75"><CardHeader><CardTitle className="text-white">{c.title}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-slate-300"><p>{c.repository.fullName} · <a className="text-cyan-200" href={c.url} target="_blank" rel="noreferrer">issue</a></p><div className="flex flex-wrap gap-2">{[["Demand",c.score.demandScore],["Bounty",c.score.bountyConfidenceScore],["Service",c.score.serviceLeadScore],["Risk",c.score.riskScore]].map(([l,v])=><Badge key={l} className="bg-white/10 text-white">{l} {v}</Badge>)}<Badge variant="outline" className="border-amber-300/30 text-amber-100">{c.monetizationRoute}</Badge></div><p className="text-xs text-slate-400">Risk flags: {c.riskFlags.join(", ")||"none"}</p><Button onClick={()=>pipe(c)} className="bg-emerald-300 text-slate-950"><PackageCheck className="mr-2 h-4 w-4"/>Create Pipeline Preview</Button></CardContent></Card>)}</section>
 <section className="grid gap-4 xl:grid-cols-2"><Card className="border-white/10 bg-slate-950/75"><CardHeader><CardTitle className="text-white">Pipeline previews</CardTitle></CardHeader><CardContent className="space-y-3">{pipelines.map(p=><div key={p.id} className="rounded-2xl border border-white/10 p-3 text-sm text-slate-300"><p className="font-bold text-white">{p.candidate.title}</p><p>{p.status} · {p.candidate.monetizationRoute}</p><Button onClick={()=>conversion(p.id)} variant="outline" className="mt-2 border-cyan-300/30 text-cyan-100"><ShieldCheck className="mr-2 h-4 w-4"/>Generate Conversion Pack</Button></div>)}</CardContent></Card><Card className="border-amber-300/20 bg-slate-950/75"><CardHeader><CardTitle className="text-white">Conversion Pack Queue</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm text-slate-300 sm:grid-cols-2"><p>Total readable packs: <b className="text-white">{summary.total}</b></p><p>Opportunity previews created: <b className="text-white">{summary.opportunities}</b></p><p>Task previews created: <b className="text-white">{summary.tasks}</b></p><p>Brain sprint previews created: <b className="text-white">{summary.brain}</b></p><p>Execution packs: <b className="text-white">{summary.executionPacks}</b></p><p>Broker previews: <b className="text-white">{summary.broker}</b></p><p>Execution previews: <b className="text-white">{summary.execution}</b></p><p>Validation previews: <b className="text-white">{summary.validation}</b></p><p>Release previews: <b className="text-white">{summary.release}</b></p><p>Ledger previews: <b className="text-white">{summary.ledger}</b></p><p>Pending manual review: <b className="text-white">{summary.pending}</b></p>{!summary.total&&<p className="sm:col-span-2">No conversion packs yet. Generate a pipeline preview first; all actions remain preview-only.</p>}</CardContent></Card></section>
 <GitHubDemandActionResultPanel result={lastActionResult}/>
 <section className="space-y-4"><h2 className="text-2xl font-black text-white">Readable conversion packs</h2>{conversionPacks.map((p:any)=><GitHubDemandConversionPackCard key={p.id} pack={p} loadingAction={loadingAction?.id===p.id?loadingAction.kind:null} onOpportunity={handleCreateOpportunity} onTask={handleCreateTaskPreview} onBrain={handleSendToBrain}/>)}</section><section className="space-y-4"><h2 className="text-2xl font-black text-white">Execution-ready packs</h2>{executionResult&&<pre className="overflow-auto rounded-2xl border border-emerald-300/20 bg-emerald-950/30 p-3 text-xs text-emerald-100">{JSON.stringify(executionResult,null,2)}</pre>}{conversionPacks.map((p:any)=><Button key={p.id} onClick={()=>executionPack(p.id)} variant="outline" className="border-emerald-300/30 text-emerald-100">Generate Execution Pack for {p.offerTitle}</Button>)}{executionPacks.map((p:any)=><GitHubDemandExecutionPackCard key={p.id} pack={p} loading={loadingAction?.id===p.id?loadingAction.kind:null} onAction={handleExecutionAction}/>)}</section></div> }
