import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { R100CollectionCountsPanel } from "@/components/r100/R100CollectionCountsPanel";
import { R100DurableStateBanner } from "@/components/r100/R100DurableStateBanner";
import { createR100DurabilityProbe, fallbackR100Verification, fetchR100Snapshot, fetchR100Verification, reloadR100StateManually, type R100ProbeResult, type R100Snapshot, type R100VerificationSummary } from "@/services/r100DurableStateService";

const badges = ["MANUAL_FIRST", "PREVIEW_ONLY", "NO_PAYMENT_API", "NO_CHECKOUT", "NO_INVOICE", "NO_AUTO_SEND", "NO_GITHUB_WRITE", "NO_EXTERNAL_CONTACT", "NO_SCRAPING"];
function fmt(value: string | null) { return value ? new Date(value).toLocaleString("pt-BR") : "not recorded"; }

export default function R100DurableStatePage() {
  const [verification, setVerification] = useState<R100VerificationSummary>(() => fallbackR100Verification());
  const [probe, setProbe] = useState<R100ProbeResult | null>(null);
  const [snapshot, setSnapshot] = useState<R100Snapshot | null>(null);
  const [showSnapshot, setShowSnapshot] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  async function refresh(signal?: AbortSignal) { const next = await fetchR100Verification(signal); setVerification(next); return next; }
  useEffect(() => { const controller = new AbortController(); refresh(controller.signal).finally(()=>{ if(!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  async function runProbe() { const result = await createR100DurabilityProbe(); setProbe(result); await refresh(); setMessage(result.roundtripOk ? "Safe synthetic probe roundtrip succeeded." : "Safe synthetic probe failed; inspect adapter health."); }
  async function manualReload() { const result = await reloadR100StateManually(); setMessage(result?.reloaded ? "Manual reload completed. No external calls were made." : "Manual reload did not complete."); await refresh(); }
  async function loadSnapshot() { const result = await fetchR100Snapshot(); setSnapshot(result); setShowSnapshot(true); }

  return <main className="space-y-6 p-6 text-white"><section className="rounded-[2rem] border border-amber-300/20 bg-gradient-to-br from-amber-500/15 to-cyan-500/10 p-6"><p className="text-xs font-black uppercase tracking-[0.32em] text-amber-200">R$100 Memory Verification P1</p><h1 className="mt-3 text-4xl font-black">Memória Operacional R$100 P1</h1><p className="mt-2 max-w-4xl text-stone-300">Manual-first, Preview-only, Operator-approved only verification for the R$100 state adapter. No payment provider API, No checkout, No invoice, No auto-send, No external contact, No GitHub write, No scraping.</p><div className="mt-4 flex flex-wrap gap-2">{badges.map(b=><Badge key={b} variant="outline" className="border-cyan-300/30 text-cyan-100">{b}</Badge>)}<Badge className="border-emerald-300/30 bg-emerald-400/10 text-emerald-100">{verification.persistenceMode}</Badge></div></section>
    <R100DurableStateBanner verification={verification}/>
    {message ? <div className="rounded-2xl border border-emerald-300/25 bg-emerald-400/10 p-3 text-sm text-emerald-100">{message}</div> : null}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Persistence mode",verification.persistenceMode],["Adapter health",verification.healthy?"healthy":"needs review"],["Fallback used",verification.fallbackUsed?"yes":"no"],["Last saved",fmt(verification.lastSavedAt)],["Last loaded",fmt(verification.lastLoadedAt)]].map(([label,value])=><Card key={label} className="border-white/10 bg-[#090909]/85 text-white"><CardContent className="p-5"><p className="text-xs uppercase tracking-[0.24em] text-stone-500">{label}</p><p className="mt-3 text-xl font-black">{value}</p></CardContent></Card>)}</section>
    <section className="grid gap-4 lg:grid-cols-[1fr_0.8fr]"><Card className="border-white/10 bg-[#090909]/85 text-white"><CardContent className="space-y-4 p-5"><h2 className="text-xl font-black">Safe operator actions</h2><div className="flex flex-wrap gap-2"><Button onClick={()=>refresh()} className="bg-cyan-300 text-black hover:bg-cyan-200">Atualizar status</Button><Button onClick={runProbe} variant="outline" className="border-emerald-300/30 text-emerald-100">Criar probe segura</Button><Button onClick={manualReload} variant="outline" className="border-amber-300/30 text-amber-100">Recarregar estado manualmente</Button><Button onClick={loadSnapshot} variant="outline" className="border-violet-300/30 text-violet-100">Ver snapshot redigido</Button></div><p className="text-sm text-stone-400">Probe uses confirmation CREATE_SAFE_R100_DURABILITY_PROBE and creates only a synthetic non-business record. Reload uses RELOAD_R100_STATE_MANUALLY and never runs automatically.</p>{probe?<pre className="overflow-auto rounded-2xl bg-black/40 p-3 text-xs text-emerald-100">{JSON.stringify(probe,null,2)}</pre>:null}</CardContent></Card><Card className="border-white/10 bg-[#090909]/85 text-white"><CardContent className="space-y-3 p-5"><h2 className="text-xl font-black">Next manual action</h2><p className="text-sm text-stone-300">{verification.nextManualAction}</p><p className="text-xs text-stone-500">safeToProceed: {String(verification.safeToProceed)} · needsDatabaseBeforeScale: {String(verification.needsDatabaseBeforeScale)} · trust: {verification.operatorTrustLevel}</p></CardContent></Card></section>
    <section className="space-y-3"><h2 className="text-2xl font-black">Collection counts</h2><R100CollectionCountsPanel counts={verification.collectionCounts}/></section>
    <section className="grid gap-4 lg:grid-cols-2"><Card className="border-white/10 bg-[#090909]/85 text-white"><CardContent className="p-5"><h2 className="text-xl font-black">Restored collections</h2><div className="mt-3 flex flex-wrap gap-2">{verification.restoredCollections.length?verification.restoredCollections.map(c=><Badge key={c} className="bg-emerald-400/10 text-emerald-100">{c}</Badge>):<p className="text-sm text-stone-400">No restored collections reported yet.</p>}</div></CardContent></Card><Card className="border-white/10 bg-[#090909]/85 text-white"><CardContent className="p-5"><h2 className="text-xl font-black">Safety warnings</h2><ul className="mt-3 space-y-2 text-sm text-stone-300">{verification.warnings.map(w=><li key={w}>• {w}</li>)}</ul></CardContent></Card></section>
    <section className="rounded-3xl border border-violet-300/20 bg-violet-400/10 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Redacted snapshot</h2><p className="text-sm text-stone-300">Collapsed by default. Snapshot is for operator audit only and must not contain secrets.</p></div><Button variant="outline" className="border-violet-300/30 text-violet-100" onClick={()=>setShowSnapshot(!showSnapshot)}>{showSnapshot?"Hide":"Show"}</Button></div>{showSnapshot?<pre className="mt-4 max-h-[440px] overflow-auto rounded-2xl bg-black/50 p-4 text-xs text-violet-50">{JSON.stringify(snapshot??{snapshotMode:"SAFE_REDACTED",note:"Click Ver snapshot redigido to load."},null,2)}</pre>:null}</section>
    {loading ? <p className="text-sm text-stone-500">Loading verification...</p> : null}
  </main>;
}
