@echo off
cd /d c:\Users\P-c\Documents\xzeon-xpex-1
echo [1/6] Adicionando package-lock.json...
git add package-lock.json
echo [2/6] Commitando...
git commit -m "fix: sync package-lock.json for railway deploy"
echo [3/6] Push para runtime-hardening...
git push origin runtime-hardening
echo [4/6] Checkout main...
git checkout main
echo [5/6] Merge runtime-hardening...
git merge runtime-hardening --no-ff -m "deploy: merge runtime-hardening fixes for railway"
echo [6/6] Push para main...
git push origin main
echo.
echo ✅ CONCLUIDO! Railway vai detectar e fazer deploy automaticamente.
pause
