import type { R100WarRoomAction } from "./r100WarRoomTypes";
const blocked=["No automatic sending","No scraping or contact harvesting","No payment API, checkout, invoice, webhook or charge","No GitHub writes","No real revenue confirmation in P0"];
const action=(id:string,title:string,reason:string,value:number,urgency:R100WarRoomAction["urgency"],route:string,copy:string):R100WarRoomAction=>({actionId:id,title,reason,expectedValueBrl:value,urgency,targetRoute:route,copyInstruction:`Copy-only preview. Operator manually reviews and acts outside GXEON: ${copy}`,blockedActions:blocked,manualOnly:true,copyOnly:true});
export function rankR100ManualActions(input:{prospects:any[];offers:any[];payments:any[];githubPacks:any[]}):R100WarRoomAction[]{
 const {prospects,offers,payments,githubPacks}=input; const actions:R100WarRoomAction[]=[];
 const closeLoopSummary=(input as any).closeLoopSummary;
 if(closeLoopSummary?.activeCloseLoops){ actions.push(action("close_loop_next", closeLoopSummary.nextBestManualAction?.title??"Continuar fechamento R$100", "Existe ciclo de fechamento manual ativo; priorize avançar Prospect -> Oferta -> Pagamento -> Evidência -> Ledger.", closeLoopSummary.previewRevenueBrl||100, "HIGH", "/ops/revenue-close-loop", "abrir Fechamento R$100 e executar o próximo passo manual-only.")); }
 prospects.filter(p=>p.status==="ACCEPTED_MANUALLY"&&!p.linkedPaymentRequestId).forEach(p=>actions.push(action(`accepted_${p.id}`,`Criar pagamento manual para ${p.displayNameOrLabel}`,"Prospect aceito manualmente ainda não tem pedido de pagamento preview.",p.estimatedBudgetBrl??100,"HIGH","/ops/manual-payment","abrir Manual Payment e criar pedido de pagamento preview.")));
 prospects.filter(p=>(p.score?.sprintFitLabel==="HIGH"||p.urgencyLabel==="HIGH")&&!p.linkedOfferPackId).forEach(p=>actions.push(action(`hot_${p.id}`,`Preparar oferta para ${p.displayNameOrLabel}`,"Prospect quente informado pelo operador ainda não tem oferta pronta.",p.estimatedBudgetBrl??100,"HIGH","/ops/client-offers","gerar/copiar oferta manual, sem envio automático.")));
 offers.filter(o=>o.status==="READY_TO_COPY"||o.status==="DRAFT").forEach(o=>actions.push(action(`offer_${o.id}`,`Copiar oferta ${o.title}`,"Oferta pronta ou rascunho precisa de ação manual do operador.",o.amountBrl??100,"MEDIUM","/ops/client-offers","copiar a mensagem e enviar manualmente fora do GXEON.")));
 offers.filter(o=>o.status==="WAITING_RESPONSE_MANUAL").forEach(o=>actions.push(action(`follow_${o.id}`,`Follow-up manual de ${o.title}`,"Oferta aguardando resposta manual merece follow-up seguro.",o.amountBrl??100,"MEDIUM","/ops/client-offers","copiar follow-up e agir manualmente fora do GXEON.")));
 githubPacks.filter(p=>p.status==="READY_FOR_OPERATOR"||p.status==="READY_TO_CONVERT"||p.status==="DRAFT").forEach(p=>actions.push(action(`github_${p.id}`,`Executar pack GitHub Demand`,"Pack de demanda está pronto para conversão manual, sem escrever no GitHub.",100,"LOW","/ops/github-demand","abrir pack e copiar plano de abordagem manual.")));
 payments.filter(p=>p.status==="READY_TO_SEND_MANUALLY"||p.status==="DRAFT").forEach(p=>actions.push(action(`payment_${p.id}`,`Copiar pedido de pagamento ${p.offerTitle}`,"Pedido manual está pronto para cópia, sem provider ou checkout.",p.amountBrl??100,"HIGH","/ops/manual-payment","copiar instrução de pagamento manual.")));
 return actions.length?actions:[action("seed_manual_pipeline","Adicionar primeiro prospect manual","Nenhum ativo pronto; comece com contato conhecido e consentido pelo operador.",100,"HIGH","/ops/prospects","cadastrar prospect operator-provided e seguir checklist de 15 minutos.")];
}
