// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeERC20$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeERC20";
  readonly sourceName: "contracts/interfaces/SafeERC20.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122086118a1ae63d7275323090d5f0a2abda6714f70d0832714834ab5552604395e264736f6c63430008140033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122086118a1ae63d7275323090d5f0a2abda6714f70d0832714834ab5552604395e264736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/SafeERC20.sol";
  readonly buildInfoId: "solc-0_8_20-2ea50d980e193d3bbf29660fb6aa9a04bb1e5ff5";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeERC20"]: SafeERC20$Type;
    ["contracts/interfaces/SafeERC20.sol:SafeERC20"]: SafeERC20$Type;
  }
}