import { listManualProspects } from "../prospect/manualProspectStore";
import { listClientOfferSendPacks } from "../clientOffer/clientOfferSendStore";
import { listManualPaymentRequests } from "../manualPayment/manualPaymentRequestStore";
import { listRevenueCloseLoops } from "../revenueCloseLoop/revenueCloseLoopStore";
import { getLedgerStatusSummary, listLedgerPreviews } from "../ledger/ledgerStore";
import { listExecutionPacks } from "../radar/githubDemandExecutionStore";
import { listOperatorDeliveryWorkspaces } from "../deliveryWorkspace/operatorDeliveryWorkspaceStore";
import { buildOperatorWorkflowSummary } from "../operatorWorkflow/operatorWorkflowStateAggregator";
import type { R100SidebarStep, R100TruthSafetyFlags, R100TruthSummary, R100TopbarKpi } from "./r100TruthTypes";
export const r100TruthSafetyFlags: R100TruthSafetyFlags = { manualFirst:true, previewOnly:true, noAutoSend:true, noPaymentProviderApi:true, noCheckout:true, noInvoice:true, noWebhook:true, noExternalContact:true, noGithubWrite:true, noScraping:true, revenueNotProviderVerified:true };
const brl=(v:number)=>`R$${Math.max(0,Math.round(Number(v)||0)).toLocaleString("pt-BR")}`;
const count=(fn:()=>unknown[])=>{try{return fn().length}catch{return 0}};
const safeLedger=()=>{try{return getLedgerStatusSummary()}catch{return {forecastRevenueBrl:0,operatorConfirmedRevenueBrl:0,providerVerifiedRevenueBrl:0,pendingRevenueBrl:0,lostRevenueBrl:0}}};
const safeWorkflow=()=>{try{return buildOperatorWorkflowSummary()}catch{return {currentStep:1,nextStep:1,currentRoute:"/ops/r100-war-room",nextRoute:"/ops/r100-war-room",nextManualAction:"Abrir Sala R$100 e revisar estado manual seguro.",counts:{openHandoffs:0}} as any}};
const steps = [[1,"R$100 War Room","/ops/r100-war-room",""],[2,"Command Brain","/ops/brain",""],[3,"Operator Assistant","/ops/operator-assistant",""],[4,"Revenue Sprint","/ops/monetization",""],[5,"Prospects","/ops/prospects","prospectsCount"],[6,"Client Offers","/ops/client-offers","clientOfferPacksCount"],[7,"Manual Payment","/ops/manual-payment","manualPaymentRequestsCount"],[8,"R$100 Close Loop","/ops/revenue-close-loop","closeLoopsCount"],[9,"Ledger","/ops/ledger","ledgerPreviewCount"]] as const;
export function buildR100TopbarKpis(s:Pick<R100TruthSummary,"prospectsCount"|"executionPacksCount"|"deliveryWorkspaceCount"|"operatorConfirmedRevenueBrl">):R100TopbarKpi[]{return [{label:"Opportunities",value:String(s.prospectsCount),href:"/ops/prospects"},{label:"Tasks",value:String(s.executionPacksCount),href:"/ops/tasks"},{label:"Executions",value:String(s.deliveryWorkspaceCount),href:"/ops/execution"},{label:"Revenue",value:brl(s.operatorConfirmedRevenueBrl),qualifier:"manual",href:"/ops/ledger",title:"provider not verified"},{label:"Connectors",value:"5",href:"/ops/connectors"}];}
export function buildR100SidebarSteps(s:R100TruthSummary):R100SidebarStep[]{return steps.map(([step,label,href,key])=>({step,label,href,status:step===s.currentOfficialStep?"CURRENT":step===s.nextOfficialStep?"NEXT":step<s.currentOfficialStep?"DONE":"PENDING",count:key?(s as any)[key]:undefined,manualOnly:true,safe:true}));}
export function buildR100TruthSummary():R100TruthSummary{ const w=safeWorkflow(); const l=safeLedger(); const summary = { status:"R100_TRUTH_SPINE_P1_READY" as const, mode:"MANUAL_FIRST" as const, ...r100TruthSafetyFlags, prospectsCount:count(listManualProspects), clientOfferPacksCount:count(listClientOfferSendPacks), manualPaymentRequestsCount:count(listManualPaymentRequests), closeLoopsCount:count(listRevenueCloseLoops), ledgerPreviewCount:count(listLedgerPreviews), executionPacksCount:count(listExecutionPacks), deliveryWorkspaceCount:count(listOperatorDeliveryWorkspaces), openHandoffsCount:Number(w.counts?.openHandoffs)||0, currentOfficialStep:Number(w.currentStep)||1, nextOfficialStep:Number(w.nextStep)||1, currentRoute:w.currentRoute||"/ops/r100-war-room", nextRoute:w.nextRoute||"/ops/r100-war-room", nextManualAction:w.nextRoute==="/ops/ledger"?"Review ledger preview and proof trail.":(w.nextManualAction||"Abrir Sala R$100 e revisar estado manual seguro."), forecastRevenueBrl:Number(l.forecastRevenueBrl)||0, operatorConfirmedRevenueBrl:Number(l.operatorConfirmedRevenueBrl)||0, providerVerifiedRevenueBrl:0 as const, pendingRevenueBrl:Number(l.pendingRevenueBrl)||0, lostRevenueBrl:Number(l.lostRevenueBrl)||0, revenueDisplayLabel:"Operator confirmed", revenueDisplayValue:"R$0", revenueDisplayQualifier:"operator-confirmed manual preview", revenueSafetyLabel:"provider not verified", nextActionButtonLabel:"Continue manual R$100 flow", safeFallbackUsed:false, topbarKpis:[] as R100TopbarKpi[], sidebarSteps:[] as R100SidebarStep[] };
summary.revenueDisplayValue=brl(summary.operatorConfirmedRevenueBrl); summary.nextActionButtonLabel=summary.nextRoute==="/ops/ledger"?"Review ledger preview and proof trail":"Continue manual R$100 flow"; summary.topbarKpis=buildR100TopbarKpis(summary); summary.sidebarSteps=buildR100SidebarSteps(summary); return summary; }
export function buildR100FallbackSummary():R100TruthSummary{ const s=buildR100TruthSummary(); const z={...s,prospectsCount:0,clientOfferPacksCount:0,manualPaymentRequestsCount:0,closeLoopsCount:0,ledgerPreviewCount:0,executionPacksCount:0,deliveryWorkspaceCount:0,openHandoffsCount:0,currentOfficialStep:1,nextOfficialStep:1,currentRoute:"/ops/r100-war-room",nextRoute:"/ops/r100-war-room",nextManualAction:"Abrir Sala R$100 em SAFE MODE.",forecastRevenueBrl:0,operatorConfirmedRevenueBrl:0,providerVerifiedRevenueBrl:0 as const,pendingRevenueBrl:0,lostRevenueBrl:0,revenueDisplayValue:"R$0",revenueSafetyLabel:"SAFE MODE · provider not verified",safeFallbackUsed:true}; return {...z,topbarKpis:buildR100TopbarKpis(z),sidebarSteps:buildR100SidebarSteps(z)}; }
