import { manualPaymentSafetyFlags, type ManualPaymentRequest, type ManualPaymentRequestInput } from "./manualPaymentRequestTypes";
const money=(n:number)=>`R$ ${n.toFixed(2).replace(".", ",")}`;
export function buildManualPaymentRequest(input:ManualPaymentRequestInput): ManualPaymentRequest {
 const now=new Date().toISOString(); const amount=Number(input.amountBrl ?? 100); const title=input.offerTitle?.trim() || "GXEON Manual Offer"; const id=`mpr_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
 const link=input.manualPaymentLink?.trim(); const pix=input.pixKeyLabel?.trim(); const method=input.method ?? "PIX_MANUAL";
 const paymentLine = link ? `Link manual informado pelo operador (${link}).` : pix ? `Chave/identificador Pix informado pelo operador: ${pix}.` : "Operador adicionará Pix/link Mercado Pago manualmente antes de enviar.";
 const pt=`Olá! Segue solicitação manual de pagamento GXEON para ${title}: ${money(amount)}. ${paymentLine} Envie o comprovante após pagar. Esta mensagem é apenas texto para copiar; não há checkout automático, cobrança automática ou garantia de confirmação dentro do GXEON.`;
 const en=`Hello! GXEON manual payment request for ${title}: BRL ${amount.toFixed(2)}. ${paymentLine} Please send proof after payment. This is copy-only text; GXEON does not create checkout, charge automatically, or guarantee payment confirmation.`;
 const proofChecklist=["Comprovante recebido manualmente pelo operador","Valor confere com a solicitação","Pagador/destinatário conferidos fora do GXEON","Data e identificador da transação anotados manualmente","Nenhuma confirmação automática/provider foi usada"];
 const manualConfirmationChecklist=["Verificar saldo/extrato fora do GXEON","Conferir comprovante com banco/Mercado Pago manualmente","Registrar confirmação externa apenas fora do P0","Manter ledger GXEON como preview até confirmação operacional","Não tratar este registro como nota fiscal"];
 const receiptDraft=`RECIBO RASCUNHO NÃO FISCAL\nOferta: ${title}\nValor esperado: ${money(amount)}\nMétodo manual: ${method}\nStatus: preview-only; emitir recibo real somente após confirmação externa.`;
 return {...manualPaymentSafetyFlags,id,sourceType:input.sourceType??"MANUAL_OFFER",sourceId:input.sourceId,status:"READY_TO_SEND_MANUALLY",offerTitle:title,amountBrl:amount,amountUsd:input.amountUsd,method,manualPaymentLinkDisplay:link?{label:"OPERATOR_PROVIDED_MANUAL_LINK",url:link}:undefined,pixKeyDisplayLabel:pix,notes:input.notes,ptBrCopyMessage:pt,enUsCopyMessage:en,proofChecklist,manualConfirmationChecklist,receiptDraft,ledgerPreview:{type:"MANUAL_PAYMENT_LEDGER_PREVIEW",expectedAmountBrl:amount,realRevenueBrl:0,providerVerified:false,ledgerWriteRealDisabled:true,realRevenueClaimed:false,paymentNotGuaranteed:true},nextManualAction:"Copy the message, paste any manual Pix/Mercado Pago details outside GXEON, and verify proof manually.",createdAt:now,updatedAt:now,actionHistory:[]};
}
export const actionResult=(request:ManualPaymentRequest, preview:Record<string,unknown>={} )=>({mode:"PREVIEW_ONLY" as const,requestId:request.id,status:request.status,safetyFlags:manualPaymentSafetyFlags,nextManualAction:request.nextManualAction,paymentProviderDisabled:true as const,realRevenueClaimed:false as const,paymentNotGuaranteed:true as const,preview:{request,...preview}});
