import { apiUrl } from "./apiBase";
export type IntegrationCandidateCategory = "MCP_SERVER" | "MODEL_ROUTER" | "CONNECTOR" | "AGENT_FRAMEWORK" | "RAG_TOOL" | "BROWSER_AGENT" | "GITHUB_TOOL" | "DATABASE_TOOL" | "DEPLOYMENT_TOOL" | "SECURITY_TOOL" | "UNKNOWN";
export type AgentEconomySource = { id: string; label: string; type: string; bestFor: string[]; manualOnly: true; riskNotes: string[]; monetizationAngles: string[] };
export type IntegrationCandidatePreview = { id: string; title: string; url: string | null; sourceId: string; sourceLabel: string; category: IntegrationCandidateCategory; status: string; decision: string; mode: "PREVIEW_ONLY"; manualApprovalRequired: true; installDisabled: true; executionDisabled: true; secretStorageDisabled: true; externalApiCallsDisabled: true; monetizationNotGuaranteed: true; integrationValueScore: number; securityRiskScore: number; licenseConfidenceScore: number; monetizationPotentialScore: number; implementationComplexityScore: number; finalGxeonFitScore: number; riskFlags: string[]; valueSignals: string[]; licenseHint: string; maintenanceHint: string; notes: string; monetizationAngles: string[]; recommendedNextManualAction: string; connectorPreview?: ConnectorPreview; taskPreview?: any };
export type ConnectorPreview = { suggestedIntegrationType: string; implementationPlan: string[]; safetyChecklist: string[]; monetizationAngles: string[]; nextManualAction: string };
export type AgentEconomyStatus = { status: string; mode: "PREVIEW_ONLY"; sourceCount: number; candidateCount: number; taskQueueReadyCount: number; boundaries: string[] };
export type ManualImportInput = { title: string; url: string; sourceId: string; categoryHint: string; licenseHint: string; maintenanceHint: string; notes: string; monetizationAngle: string };
const boundary = { mode:"PREVIEW_ONLY" as const, manualApprovalRequired:true as const, installDisabled:true as const, executionDisabled:true as const, secretStorageDisabled:true as const, externalApiCallsDisabled:true as const, monetizationNotGuaranteed:true as const };
export const fallbackSources: AgentEconomySource[] = [{ id:"manual_import", label:"Manual Repository / Tool Import", type:"OPERATOR_INPUT", bestFor:["operator-pasted repositories","private research","manual candidate tracking"], manualOnly:true, riskNotes:["Backend unavailable fallback; manual preview only"], monetizationAngles:["Manual audit","Custom integration service"] }];
export const fallbackStatus: AgentEconomyStatus = { status:"AGENT_ECONOMY_FALLBACK_PREVIEW", mode:"PREVIEW_ONLY", sourceCount:fallbackSources.length, candidateCount:0, taskQueueReadyCount:0, boundaries:["No install","No execute","No secrets","No external API calls"] };
async function get<T>(path: string, fallback: T, signal?: AbortSignal): Promise<T> { try { const r = await fetch(apiUrl(path), { headers:{ Accept:"application/json" }, signal }); if (!r.ok) throw new Error(path); const j = await r.json(); return j.data as T; } catch { return fallback; } }
async function post<T>(path: string, body?: unknown): Promise<T> { const r = await fetch(apiUrl(path), { method:"POST", headers:{ "Content-Type":"application/json", Accept:"application/json" }, body: JSON.stringify(body ?? {}) }); const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.message || "AGENT_ECONOMY_REQUEST_FAILED"); return j.data as T; }
export const fetchAgentEconomyStatus = (signal?: AbortSignal) => get<AgentEconomyStatus>("/api/agent-economy/status", fallbackStatus, signal);
export const fetchAgentEconomySources = (signal?: AbortSignal) => get<{ sources: AgentEconomySource[] }>("/api/agent-economy/sources", { ...boundary, sources:fallbackSources }, signal);
export const fetchIntegrationCandidates = (signal?: AbortSignal) => get<{ candidates: IntegrationCandidatePreview[]; count: number }>("/api/agent-economy/candidates", { ...boundary, candidates:[], count:0 }, signal);
export const manualImportIntegrationCandidate = (input: ManualImportInput) => post<{ candidate: IntegrationCandidatePreview }>("/api/agent-economy/manual-import", input);
export const createConnectorPreview = (id: string) => post<{ candidate: IntegrationCandidatePreview; connectorPreview: ConnectorPreview }>(`/api/agent-economy/candidates/${id}/create-connector-preview`);
export const createTaskPreviewFromCandidate = (id: string) => post<{ candidate: IntegrationCandidatePreview; taskPreview: any }>(`/api/agent-economy/candidates/${id}/create-task-preview`);
