import { apiUrl } from "./apiBase";
export type BrainMode = "PREVIEW_ONLY";
export type RevenueSprintStatus = "PLANNED" | "ACTIVE_MANUAL" | "WAITING_PAYMENT_MANUAL" | "SUBMISSION_PREPARED" | "BLOCKED" | "COMPLETED_UNVERIFIED" | "CANCELLED";
export type RevenueRouteType = "DIRECT_PIX_OFFER" | "WEB3_TASK_ATTEMPT" | "AGENT_ECONOMY_AUDIT" | "MANUAL_OTHER";
export type PreferredPayoutMethod = "MERCADO_PAGO_PIX_MANUAL" | "PIX_MANUAL" | "MERCADO_PAGO_MANUAL" | "MANUAL_OTHER";
export type SafetyFlags = { mode: BrainMode; manualExecutionRequired: true; paymentProviderApiDisabled: true; externalContactAutomationDisabled: true; realRevenueNotGuaranteed: true; operatorApprovalRequired: true };
export type RevenueOfferPack = { id: string; routeType: RevenueRouteType; title: string; priceBrl: number; targetSales: number; deliveryWindow: string; deliverables: string[]; readyToCopyMessage: string; manualExecutionNotes: string[] };
export type RevenueActionPlan = { rank: number; routeType: RevenueRouteType; label: string; description: string; target: string; estimatedSpeed: string; manualSteps: string[]; riskNotes: string[] };
export type MinimumRevenueSprintInput = { targetAmountBrl?: number; deadlineLabel?: string; preferredPayoutMethod?: PreferredPayoutMethod; operatorNotes?: string; mercadoPagoManualLink?: string; pixKeyLabel?: string };
export type MinimumRevenueSprintRecord = SafetyFlags & { id: string; createdAt: string; updatedAt: string; status: RevenueSprintStatus; targetAmountBrl: number; deadlineLabel: string; preferredPayoutMethod: PreferredPayoutMethod; operatorNotes: string; actionPlan: RevenueActionPlan[]; offerPacks: RevenueOfferPack[]; paymentInstruction: { instructionText: string; boundaries: string[] }; evidenceChecklist: string[]; ledgerPreview: SafetyFlags & { targetAmountBrl: number; expectedGrossBrl: number; providerVerified: false; realRevenueClaimed: false; ledgerWriteDisabled: true; previewNote: string }; nextBestAction: string };
export type RevenueSprintStatusResponse = SafetyFlags & { status: string; sprintCount: number; activeSprintCount: number; targetAmountBrl: number; fastestRoute: RevenueRouteType; boundaries: string[] };
const fallbackFlags: SafetyFlags = { mode: "PREVIEW_ONLY", manualExecutionRequired: true, paymentProviderApiDisabled: true, externalContactAutomationDisabled: true, realRevenueNotGuaranteed: true, operatorApprovalRequired: true };
const fallbackPacks: RevenueOfferPack[] = [{ id: "ai_audit_express_50", routeType: "DIRECT_PIX_OFFER", title: "Auditoria Express com IA", priceBrl: 50, targetSales: 2, deliveryWindow: "Hoje", deliverables: ["diagnóstico simples", "pontos de melhoria", "plano de 7 dias", "texto pronto para usar"], readyToCopyMessage: "Oi! Estou abrindo 2 vagas hoje para Auditoria Express com IA por R$50. Pagamento Pix/Mercado Pago manual; GXEON não cria link nem confirma pagamento.", manualExecutionNotes: ["Enviar manualmente", "Conferir pagamento fora do GXEON"] }];
async function request<T>(path: string, init?: RequestInit): Promise<T> { const res = await fetch(apiUrl(path), { ...init, headers: { Accept: "application/json", "Content-Type": "application/json", ...(init?.headers ?? {}) } }); const payload = await res.json() as { success: boolean; data: T; error?: string }; if (!res.ok || !payload.success) throw new Error(payload.error ?? `REQUEST_FAILED_${res.status}`); return payload.data; }
export async function fetchCommandBrainStatus(signal?: AbortSignal) { try { return await request<RevenueSprintStatusResponse & { layer: string }>("/api/brain/status", { signal }); } catch { return { ...fallbackFlags, status: "COMMAND_BRAIN_FALLBACK_PREVIEW", sprintCount: 0, activeSprintCount: 0, targetAmountBrl: 100, fastestRoute: "DIRECT_PIX_OFFER" as const, boundaries: ["backend unavailable fallback", "manual only"], layer: "GXEON Command Brain P0" }; } }
export async function fetchRevenueSprintStatus(signal?: AbortSignal) { try { return await request<RevenueSprintStatusResponse>("/api/brain/revenue-sprint/status", { signal }); } catch { return { ...fallbackFlags, status: "REVENUE_SPRINT_FALLBACK_PREVIEW", sprintCount: 0, activeSprintCount: 0, targetAmountBrl: 100, fastestRoute: "DIRECT_PIX_OFFER" as const, boundaries: ["backend unavailable fallback", "manual only"] }; } }
export async function fetchRevenueSprintOfferPacks(signal?: AbortSignal) { try { return await request<SafetyFlags & { offerPacks: RevenueOfferPack[]; count: number }>("/api/brain/revenue-sprint/offer-packs", { signal }); } catch { return { ...fallbackFlags, offerPacks: fallbackPacks, count: fallbackPacks.length }; } }
export function fetchRevenueSprints(signal?: AbortSignal) { return request<SafetyFlags & { sprints: MinimumRevenueSprintRecord[]; count: number }>("/api/brain/revenue-sprint/sprints", { signal }); }
export function startMinimumRevenueSprint(input: MinimumRevenueSprintInput) { return request<SafetyFlags & { sprint: MinimumRevenueSprintRecord }>("/api/brain/revenue-sprint/start", { method: "POST", body: JSON.stringify(input) }); }
export function updateRevenueSprintStatus(id: string, status: RevenueSprintStatus) { return request<SafetyFlags & { sprint: MinimumRevenueSprintRecord }>(`/api/brain/revenue-sprint/sprints/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }); }
