import { apiUrl } from "./apiBase";

export type R100DatabaseMirrorStatus = { status:"R100_DB_MIRROR_P2_READY"|"R100_DB_MIRROR_DISABLED"|"R100_DB_NOT_CONFIGURED"|"R100_DB_MIRROR_UNHEALTHY"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; mirrorEnabled:boolean; safeToWrite:boolean; safeToProceed:boolean; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; latestSnapshotAt:string|null; snapshotCount:number; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorReadiness = { status:"R100_DB_MIRROR_SCHEMA_READINESS_P2"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; schemaReady:boolean; snapshotsTableReady:boolean; auditEventsTableReady:boolean; mirrorEnabled:boolean; safeToWrite:boolean; nextManualAction:string; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorActivationPlan = { status:"R100_DB_MIRROR_ACTIVATION_PLAN_P2"; mode:"MANUAL_FIRST"; readinessStatus:R100DatabaseMirrorReadiness["status"]; currentReadiness:R100DatabaseMirrorReadiness; checklist:string[]; rollback:string[]; nextManualAction:string; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorSnapshot = { snapshotId:string|null; snapshotMode:"SAFE_REDACTED"; source:"R100_DURABLE_STATE_MIRROR_P2"; collectionCounts:Record<string, number>; collections:Record<string, unknown[]>|Partial<Record<string, unknown[]>>; metadata:Record<string, unknown>; createdAt:string|null; safety:Record<string, unknown> };
export type R100DatabaseMirrorTableDiagnostics = { tableName:string; exists:boolean; requiredColumns:string[]; availableColumns:string[]; missingColumns:string[]; extraColumns:string[]; ready:boolean };
export type R100DatabaseMirrorSchemaDiagnostics = { status:"R100_DB_MIRROR_SCHEMA_DIAGNOSTICS_P2"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; schemaReady:boolean; mirrorEnabled:boolean; schemaApplyEnabled:boolean; safeToWrite:boolean; tables:R100DatabaseMirrorTableDiagnostics[]; warnings:string[]; nextManualAction:string; safety:Record<string, unknown> };
export type R100DatabaseMirrorSchemaDryRun = { status:"R100_DB_MIRROR_SCHEMA_DRY_RUN_P2"; mode:"MANUAL_FIRST"; wouldWrite:false; schemaApplyEnabled:boolean; requiredAction:"APPLY_R100_DB_MIRROR_SCHEMA_OPERATOR_APPROVED"; plan:Array<{index:number; sqlPreview:string}>; diagnostics:R100DatabaseMirrorSchemaDiagnostics; nextManualAction:string; safety:Record<string, unknown> };
export type R100DatabaseMirrorSchemaApplyResult = { status:string; mode:"MANUAL_FIRST"; applied:boolean; blocked:boolean; diagnostics?:R100DatabaseMirrorSchemaDiagnostics; nextManualAction:string; safety:Record<string, unknown> };
export type R100DatabaseMirrorActivationSmokeTest = { status:"R100_DB_MIRROR_ACTIVATION_SMOKE_TEST_P2"; mode:"MANUAL_FIRST"; wroteToDatabase:false; readiness:R100DatabaseMirrorReadiness; diagnostics:R100DatabaseMirrorSchemaDiagnostics; mirrorStatus:R100DatabaseMirrorStatus; latestSnapshot:R100DatabaseMirrorSnapshot; nextManualAction:string; safety:Record<string, unknown> };
export type R100DatabaseMirrorWriteResult = { status:string; eventId?:string; snapshotId?:string; wroteToDatabase:true; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; safety:Record<string, unknown> };

export const fallbackR100DatabaseMirrorReadiness = (): R100DatabaseMirrorReadiness => ({ status:"R100_DB_MIRROR_SCHEMA_READINESS_P2", mode:"MANUAL_FIRST", databaseConfigured:false, schemaReady:false, snapshotsTableReady:false, auditEventsTableReady:false, mirrorEnabled:false, safeToWrite:false, nextManualAction:"Backend unavailable; no persistence claim. Verify API server before activation.", warnings:["DB mirror backend unavailable; no persistence claim.","This is not payment settlement."], safety:{manualFirst:true,previewOnly:true,noPaymentProviderApi:true,noSecrets:true,dbMirrorOnly:true,notPaymentSettlement:true,providerVerifiedRevenueBrl:0,realRevenueClaimedAutomatically:false} });
export const fallbackR100DatabaseMirrorStatus = (): R100DatabaseMirrorStatus => ({ status:"R100_DB_NOT_CONFIGURED", mode:"MANUAL_FIRST", databaseConfigured:false, mirrorEnabled:false, safeToWrite:false, safeToProceed:false, providerVerifiedRevenueBrl:0, realRevenueClaimedAutomatically:false, latestSnapshotAt:null, snapshotCount:0, warnings:["DB mirror unavailable; no persistence claim.","Database mirror is readiness only, not payment settlement."], safety:fallbackR100DatabaseMirrorReadiness().safety });
export const fallbackR100DatabaseMirrorSnapshot = (): R100DatabaseMirrorSnapshot => ({ snapshotId:null, snapshotMode:"SAFE_REDACTED", source:"R100_DURABLE_STATE_MIRROR_P2", collectionCounts:{}, collections:{}, metadata:{ fallback:"DB mirror unavailable; no persistence claim." }, createdAt:null, safety:fallbackR100DatabaseMirrorStatus().safety });
export const fallbackR100DatabaseMirrorSchemaDiagnostics = (): R100DatabaseMirrorSchemaDiagnostics => ({ status:"R100_DB_MIRROR_SCHEMA_DIAGNOSTICS_P2", mode:"MANUAL_FIRST", databaseConfigured:false, schemaReady:false, mirrorEnabled:false, schemaApplyEnabled:false, safeToWrite:false, tables:[], warnings:["Schema diagnostics unavailable; no secrets exposed."], nextManualAction:"Verify backend availability, then run diagnostics again.", safety:fallbackR100DatabaseMirrorReadiness().safety });
export const fallbackR100DatabaseMirrorSchemaDryRun = (): R100DatabaseMirrorSchemaDryRun => ({ status:"R100_DB_MIRROR_SCHEMA_DRY_RUN_P2", mode:"MANUAL_FIRST", wouldWrite:false, schemaApplyEnabled:false, requiredAction:"APPLY_R100_DB_MIRROR_SCHEMA_OPERATOR_APPROVED", plan:[], diagnostics:fallbackR100DatabaseMirrorSchemaDiagnostics(), nextManualAction:"Backend unavailable; dry-run did not write.", safety:fallbackR100DatabaseMirrorReadiness().safety });
export const fallbackR100DatabaseMirrorActivationPlan = (): R100DatabaseMirrorActivationPlan => ({ status:"R100_DB_MIRROR_ACTIVATION_PLAN_P2", mode:"MANUAL_FIRST", readinessStatus:"R100_DB_MIRROR_SCHEMA_READINESS_P2", currentReadiness:fallbackR100DatabaseMirrorReadiness(), checklist:["Verify the API server is reachable before making any persistence claim.","Confirm DATABASE_URL exists only in the backend environment.","Run readiness after backend recovery."], rollback:["Keep GXEON_R100_DB_MIRROR_ENABLED=false or unset."], nextManualAction:"Backend unavailable; verify API server before activation.", warnings:["Backend unavailable; no persistence claim.","Not payment settlement."], safety:fallbackR100DatabaseMirrorReadiness().safety });

async function request<T>(path:string, init?:RequestInit, fallback?:T):Promise<T>{try{const r=await fetch(apiUrl(path),{headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})},...init}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error||path); return j.data as T;}catch{return fallback as T;}}
export const fetchR100DatabaseMirrorStatus = (signal?:AbortSignal) => request<R100DatabaseMirrorStatus>("/api/r100-db/status", { signal }, fallbackR100DatabaseMirrorStatus());
export const fetchR100DatabaseMirrorReadiness = (signal?:AbortSignal) => request<R100DatabaseMirrorReadiness>("/api/r100-db/readiness", { signal }, fallbackR100DatabaseMirrorReadiness());
export const fetchR100DatabaseMirrorActivationPlan = (signal?:AbortSignal) => request<R100DatabaseMirrorActivationPlan>("/api/r100-db/activation-plan", { signal }, fallbackR100DatabaseMirrorActivationPlan());
export const fetchR100DatabaseMirrorSnapshot = (signal?:AbortSignal) => request<R100DatabaseMirrorSnapshot>("/api/r100-db/latest-snapshot", { signal }, fallbackR100DatabaseMirrorSnapshot());
export const createR100DatabaseMirrorProbe = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/probe", { method:"POST", body:JSON.stringify({ action:"CREATE_SAFE_R100_DB_MIRROR_PROBE" }) });
export const exportR100SafeSnapshotToDatabaseMirror = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/export-safe-snapshot", { method:"POST", body:JSON.stringify({ action:"EXPORT_SAFE_R100_SNAPSHOT_TO_DB_MIRROR" }) });

export const fetchR100DatabaseMirrorSchemaDiagnostics = (signal?:AbortSignal) => request<R100DatabaseMirrorSchemaDiagnostics>("/api/r100-db/schema-diagnostics", { signal }, fallbackR100DatabaseMirrorSchemaDiagnostics());
export const dryRunR100DatabaseMirrorSchema = () => request<R100DatabaseMirrorSchemaDryRun>("/api/r100-db/schema-dry-run", { method:"POST", body:JSON.stringify({}) }, fallbackR100DatabaseMirrorSchemaDryRun());
export const applyR100DatabaseMirrorSchema = () => request<R100DatabaseMirrorSchemaApplyResult>("/api/r100-db/apply-schema", { method:"POST", body:JSON.stringify({ action:"APPLY_R100_DB_MIRROR_SCHEMA_OPERATOR_APPROVED" }) });
export const runR100DatabaseMirrorActivationSmokeTest = () => request<R100DatabaseMirrorActivationSmokeTest>("/api/r100-db/activation-smoke-test", { method:"POST", body:JSON.stringify({ action:"RUN_R100_DB_MIRROR_ACTIVATION_SMOKE_TEST" }) });
