import { apiUrl } from "./apiBase";
export type R100TopbarKpi={label:"Opportunities"|"Tasks"|"Executions"|"Revenue"|"Connectors";value:string;qualifier?:string;href:string;title?:string};
export type R100SidebarStep={step:number;label:string;href:string;status:"CURRENT"|"NEXT"|"DONE"|"PENDING";count?:number;manualOnly:true;safe:true};
export type R100TruthSummary={status:string;mode:"MANUAL_FIRST";updatedAt:string;prospectsCount:number;clientOfferPacksCount:number;manualPaymentRequestsCount:number;closeLoopsCount:number;ledgerPreviewCount:number;executionPacksCount:number;deliveryWorkspaceCount:number;openHandoffsCount:number;currentOfficialStep:number;nextOfficialStep:number;currentRoute:string;nextRoute:string;nextManualAction:string;forecastRevenueBrl:number;operatorConfirmedRevenueBrl:number;providerVerifiedRevenueBrl:0;pendingRevenueBrl:number;lostRevenueBrl:number;revenueDisplayLabel:string;revenueDisplayValue:string;revenueDisplayQualifier:string;revenueSafetyLabel:string;nextActionButtonLabel:string;safeFallbackUsed:boolean;manualFirst:true;previewOnly:true;noAutoSend:true;noPaymentProviderApi:true;noCheckout:true;noInvoice:true;noWebhook:true;noExternalContact:true;noGithubWrite:true;noScraping:true;revenueNotProviderVerified:true;topbarKpis:R100TopbarKpi[];sidebarSteps:R100SidebarStep[]};
const topbarFallback:R100TopbarKpi[]=[{label:"Opportunities",value:"0",href:"/ops/prospects"},{label:"Tasks",value:"0",href:"/ops/tasks"},{label:"Executions",value:"0",href:"/ops/execution"},{label:"Revenue",value:"R$0",qualifier:"manual",href:"/ops/ledger",title:"provider not verified"},{label:"Connectors",value:"5",href:"/ops/connectors"}];
export const fallbackR100TruthSummary=():R100TruthSummary=>({status:"R100_TRUTH_SAFE_FALLBACK",mode:"MANUAL_FIRST",updatedAt:new Date().toISOString(),prospectsCount:0,clientOfferPacksCount:0,manualPaymentRequestsCount:0,closeLoopsCount:0,ledgerPreviewCount:0,executionPacksCount:0,deliveryWorkspaceCount:0,openHandoffsCount:0,currentOfficialStep:1,nextOfficialStep:1,currentRoute:"/ops/r100-war-room",nextRoute:"/ops/r100-war-room",nextManualAction:"SAFE MODE · open R$100 War Room.",forecastRevenueBrl:0,operatorConfirmedRevenueBrl:0,providerVerifiedRevenueBrl:0,pendingRevenueBrl:0,lostRevenueBrl:0,revenueDisplayLabel:"Operator confirmed",revenueDisplayValue:"R$0",revenueDisplayQualifier:"operator-confirmed manual preview",revenueSafetyLabel:"SAFE MODE · provider not verified",nextActionButtonLabel:"Continue manual R$100 flow",safeFallbackUsed:true,manualFirst:true,previewOnly:true,noAutoSend:true,noPaymentProviderApi:true,noCheckout:true,noInvoice:true,noWebhook:true,noExternalContact:true,noGithubWrite:true,noScraping:true,revenueNotProviderVerified:true,topbarKpis:topbarFallback,sidebarSteps:[]});
async function request<T>(path:string,signal?:AbortSignal,fallback?:T):Promise<T>{try{const r=await fetch(apiUrl(path),{headers:{Accept:"application/json"},signal}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error||path); return j.data as T;}catch(e){if((e as any)?.name==="AbortError") throw e; return fallback as T;}}
export const getR100TruthSummary=(signal?:AbortSignal)=>request<R100TruthSummary>("/api/r100-truth/summary",signal,fallbackR100TruthSummary());
export const getR100TopbarKpis=(signal?:AbortSignal)=>request<{kpis:R100TopbarKpi[]}>("/api/r100-truth/topbar",signal,{kpis:topbarFallback});
export const getR100SidebarState=(signal?:AbortSignal)=>request<{steps:R100SidebarStep[];summary:R100TruthSummary}>("/api/r100-truth/sidebar",signal,{steps:[],summary:fallbackR100TruthSummary()});
