import { apiUrl } from "./apiBase";

export type R100DatabaseMirrorStatus = { status:"R100_DB_MIRROR_P2_READY"|"R100_DB_MIRROR_DISABLED"|"R100_DB_NOT_CONFIGURED"|"R100_DB_MIRROR_UNHEALTHY"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; mirrorEnabled:boolean; safeToWrite:boolean; safeToProceed:boolean; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; latestSnapshotAt:string|null; snapshotCount:number; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorReadiness = { status:"R100_DB_MIRROR_SCHEMA_READINESS_P2"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; schemaReady:boolean; snapshotsTableReady:boolean; auditEventsTableReady:boolean; mirrorEnabled:boolean; safeToWrite:boolean; nextManualAction:string; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorActivationPlan = { status:"R100_DB_MIRROR_ACTIVATION_PLAN_P2"; mode:"MANUAL_FIRST"; readinessStatus:R100DatabaseMirrorReadiness["status"]; currentReadiness:R100DatabaseMirrorReadiness; checklist:string[]; rollback:string[]; nextManualAction:string; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorSnapshot = { snapshotId:string|null; snapshotMode:"SAFE_REDACTED"; source:"R100_DURABLE_STATE_MIRROR_P2"; collectionCounts:Record<string, number>; collections:Record<string, unknown[]>|Partial<Record<string, unknown[]>>; metadata:Record<string, unknown>; createdAt:string|null; safety:Record<string, unknown> };
export type R100DatabaseMirrorWriteResult = { status:string; eventId?:string; snapshotId?:string; wroteToDatabase:true; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; safety:Record<string, unknown> };

export const fallbackR100DatabaseMirrorReadiness = (): R100DatabaseMirrorReadiness => ({ status:"R100_DB_MIRROR_SCHEMA_READINESS_P2", mode:"MANUAL_FIRST", databaseConfigured:false, schemaReady:false, snapshotsTableReady:false, auditEventsTableReady:false, mirrorEnabled:false, safeToWrite:false, nextManualAction:"Backend unavailable; no persistence claim. Verify API server before activation.", warnings:["DB mirror backend unavailable; no persistence claim.","This is not payment settlement."], safety:{manualFirst:true,previewOnly:true,noPaymentProviderApi:true,noSecrets:true,dbMirrorOnly:true,notPaymentSettlement:true,providerVerifiedRevenueBrl:0,realRevenueClaimedAutomatically:false} });
export const fallbackR100DatabaseMirrorStatus = (): R100DatabaseMirrorStatus => ({ status:"R100_DB_NOT_CONFIGURED", mode:"MANUAL_FIRST", databaseConfigured:false, mirrorEnabled:false, safeToWrite:false, safeToProceed:false, providerVerifiedRevenueBrl:0, realRevenueClaimedAutomatically:false, latestSnapshotAt:null, snapshotCount:0, warnings:["DB mirror unavailable; no persistence claim.","Database mirror is readiness only, not payment settlement."], safety:fallbackR100DatabaseMirrorReadiness().safety });
export const fallbackR100DatabaseMirrorSnapshot = (): R100DatabaseMirrorSnapshot => ({ snapshotId:null, snapshotMode:"SAFE_REDACTED", source:"R100_DURABLE_STATE_MIRROR_P2", collectionCounts:{}, collections:{}, metadata:{ fallback:"DB mirror unavailable; no persistence claim." }, createdAt:null, safety:fallbackR100DatabaseMirrorStatus().safety });
export const fallbackR100DatabaseMirrorActivationPlan = (): R100DatabaseMirrorActivationPlan => ({ status:"R100_DB_MIRROR_ACTIVATION_PLAN_P2", mode:"MANUAL_FIRST", readinessStatus:"R100_DB_MIRROR_SCHEMA_READINESS_P2", currentReadiness:fallbackR100DatabaseMirrorReadiness(), checklist:["Verify the API server is reachable before making any persistence claim.","Confirm DATABASE_URL exists only in the backend environment.","Run readiness after backend recovery."], rollback:["Keep GXEON_R100_DB_MIRROR_ENABLED=false or unset."], nextManualAction:"Backend unavailable; verify API server before activation.", warnings:["Backend unavailable; no persistence claim.","Not payment settlement."], safety:fallbackR100DatabaseMirrorReadiness().safety });

async function request<T>(path:string, init?:RequestInit, fallback?:T):Promise<T>{try{const r=await fetch(apiUrl(path),{headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})},...init}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error||path); return j.data as T;}catch{return fallback as T;}}
export const fetchR100DatabaseMirrorStatus = (signal?:AbortSignal) => request<R100DatabaseMirrorStatus>("/api/r100-db/status", { signal }, fallbackR100DatabaseMirrorStatus());
export const fetchR100DatabaseMirrorReadiness = (signal?:AbortSignal) => request<R100DatabaseMirrorReadiness>("/api/r100-db/readiness", { signal }, fallbackR100DatabaseMirrorReadiness());
export const fetchR100DatabaseMirrorActivationPlan = (signal?:AbortSignal) => request<R100DatabaseMirrorActivationPlan>("/api/r100-db/activation-plan", { signal }, fallbackR100DatabaseMirrorActivationPlan());
export const fetchR100DatabaseMirrorSnapshot = (signal?:AbortSignal) => request<R100DatabaseMirrorSnapshot>("/api/r100-db/latest-snapshot", { signal }, fallbackR100DatabaseMirrorSnapshot());
export const createR100DatabaseMirrorProbe = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/probe", { method:"POST", body:JSON.stringify({ action:"CREATE_SAFE_R100_DB_MIRROR_PROBE" }) });
export const exportR100SafeSnapshotToDatabaseMirror = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/export-safe-snapshot", { method:"POST", body:JSON.stringify({ action:"EXPORT_SAFE_R100_SNAPSHOT_TO_DB_MIRROR" }) });
