import { apiUrl } from "./apiBase";

export type R100DatabaseMirrorStatus = { status:"R100_DB_MIRROR_P2_READY"|"R100_DB_MIRROR_DISABLED"|"R100_DB_NOT_CONFIGURED"|"R100_DB_MIRROR_UNHEALTHY"; mode:"MANUAL_FIRST"; databaseConfigured:boolean; mirrorEnabled:boolean; safeToWrite:boolean; safeToProceed:boolean; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; latestSnapshotAt:string|null; snapshotCount:number; warnings:string[]; safety:Record<string, unknown> };
export type R100DatabaseMirrorSnapshot = { snapshotId:string|null; snapshotMode:"SAFE_REDACTED"; source:"R100_DURABLE_STATE_MIRROR_P2"; collectionCounts:Record<string, number>; collections:Record<string, unknown[]>|Partial<Record<string, unknown[]>>; metadata:Record<string, unknown>; createdAt:string|null; safety:Record<string, unknown> };
export type R100DatabaseMirrorWriteResult = { status:string; eventId?:string; snapshotId?:string; wroteToDatabase:true; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; safety:Record<string, unknown> };

export const fallbackR100DatabaseMirrorStatus = (): R100DatabaseMirrorStatus => ({ status:"R100_DB_NOT_CONFIGURED", mode:"MANUAL_FIRST", databaseConfigured:false, mirrorEnabled:false, safeToWrite:false, safeToProceed:false, providerVerifiedRevenueBrl:0, realRevenueClaimedAutomatically:false, latestSnapshotAt:null, snapshotCount:0, warnings:["DB mirror unavailable; no persistence claim.","Database mirror is readiness only, not payment settlement."], safety:{manualFirst:true,previewOnly:true,noPaymentProviderApi:true,noSecrets:true,dbMirrorOnly:true,notPaymentSettlement:true,providerVerifiedRevenueBrl:0,realRevenueClaimedAutomatically:false} });
export const fallbackR100DatabaseMirrorSnapshot = (): R100DatabaseMirrorSnapshot => ({ snapshotId:null, snapshotMode:"SAFE_REDACTED", source:"R100_DURABLE_STATE_MIRROR_P2", collectionCounts:{}, collections:{}, metadata:{ fallback:"DB mirror unavailable; no persistence claim." }, createdAt:null, safety:fallbackR100DatabaseMirrorStatus().safety });

async function request<T>(path:string, init?:RequestInit, fallback?:T):Promise<T>{try{const r=await fetch(apiUrl(path),{headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})},...init}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error||path); return j.data as T;}catch{return fallback as T;}}
export const fetchR100DatabaseMirrorStatus = (signal?:AbortSignal) => request<R100DatabaseMirrorStatus>("/api/r100-db/status", { signal }, fallbackR100DatabaseMirrorStatus());
export const fetchR100DatabaseMirrorSnapshot = (signal?:AbortSignal) => request<R100DatabaseMirrorSnapshot>("/api/r100-db/latest-snapshot", { signal }, fallbackR100DatabaseMirrorSnapshot());
export const createR100DatabaseMirrorProbe = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/probe", { method:"POST", body:JSON.stringify({ action:"CREATE_SAFE_R100_DB_MIRROR_PROBE" }) });
export const exportR100SafeSnapshotToDatabaseMirror = () => request<R100DatabaseMirrorWriteResult>("/api/r100-db/export-safe-snapshot", { method:"POST", body:JSON.stringify({ action:"EXPORT_SAFE_R100_SNAPSHOT_TO_DB_MIRROR" }) });
