import { apiUrl } from "./apiBase";

export type R100PersistenceMode = "SAFE_MEMORY_FALLBACK" | "SERVER_LOCAL_JSON";
export type R100DurabilityLevel = "MEMORY_ONLY" | "SERVER_LOCAL_JSON" | "UNHEALTHY_FALLBACK";
export type R100OperatorTrustLevel = "LOW" | "MEDIUM" | "HIGH";
export type R100CollectionCounts = { manualProspects:number; clientOfferSendPacks:number; manualPaymentRequests:number; revenueCloseLoops:number; operatorConfirmedRevenue:number; ledgerPreviews:number; operatorWorkflowHandoffs:number; durabilityProbes:number };
export type R100VerificationDbMirror = { status:string; databaseConfigured:boolean; mirrorEnabled:boolean; safeToWrite:boolean; safeToProceed:boolean; providerVerifiedRevenueBrl:0; realRevenueClaimedAutomatically:false; latestSnapshotAt:string|null; snapshotCount:number; warnings:string[] };
export type R100VerificationSummary = { status:"R100_DURABLE_STATE_VERIFICATION_P1_READY"; mode:"MANUAL_FIRST"; persistenceMode:R100PersistenceMode; healthy:boolean; fallbackUsed:boolean; durabilityLevel:R100DurabilityLevel; operatorTrustLevel:R100OperatorTrustLevel; safeToProceed:boolean; needsDatabaseBeforeScale:boolean; lastLoadedAt:string|null; lastSavedAt:string|null; collectionCounts:R100CollectionCounts; restoredCollections:string[]; warnings:string[]; nextManualAction:string; safety:{manualFirst:true;previewOnly:true;noPaymentProviderApi:true;noAutoSend:true;noGithubWrite:true;noExternalContact:true;noScraping:true;providerVerifiedRevenueBrl:0;realRevenueClaimedAutomatically:false}; dbMirror?:R100VerificationDbMirror };
export type R100ProbeResult = { status:string; mode:"MANUAL_FIRST"; probeId:string; persistenceMode:R100PersistenceMode; saved:boolean; reloaded:boolean; roundtripOk:boolean; durabilityProbeCount:number; createdBusinessRecords:false; safety:R100VerificationSummary["safety"] };
export type R100Snapshot = { snapshotMode:"SAFE_REDACTED"; collections:Record<string,unknown[]>; safety:Record<string,unknown> };

export const fallbackR100Verification = (): R100VerificationSummary => ({ status:"R100_DURABLE_STATE_VERIFICATION_P1_READY", mode:"MANUAL_FIRST", persistenceMode:"SAFE_MEMORY_FALLBACK", healthy:false, fallbackUsed:true, durabilityLevel:"UNHEALTHY_FALLBACK", operatorTrustLevel:"LOW", safeToProceed:false, needsDatabaseBeforeScale:true, lastLoadedAt:null, lastSavedAt:null, collectionCounts:{manualProspects:0,clientOfferSendPacks:0,manualPaymentRequests:0,revenueCloseLoops:0,operatorConfirmedRevenue:0,ledgerPreviews:0,operatorWorkflowHandoffs:0,durabilityProbes:0}, restoredCollections:[], warnings:["Backend unavailable; do not claim persistence.","Manual-first.","Preview-only.","Operator-approved only.","No payment provider API.","No checkout.","No invoice.","No auto-send.","No external contact.","No GitHub write.","No scraping.","Provider verified revenue remains R$0.","Real revenue is operator-confirmed only."], nextManualAction:"Refresh verification when backend is available; keep operating manually without claiming recovery.", safety:{manualFirst:true,previewOnly:true,noPaymentProviderApi:true,noAutoSend:true,noGithubWrite:true,noExternalContact:true,noScraping:true,providerVerifiedRevenueBrl:0,realRevenueClaimedAutomatically:false} });
async function request<T>(path:string, init?:RequestInit, fallback?:T):Promise<T>{try{const r=await fetch(apiUrl(path),{headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})},...init}); const j=await r.json(); if(!r.ok||!j.success) throw new Error(j.error||path); return j.data as T;}catch{return fallback as T;}}
export const fetchR100Verification = (signal?:AbortSignal) => request<R100VerificationSummary>("/api/r100-state/verification", { signal }, fallbackR100Verification());
export const fetchR100Snapshot = () => request<R100Snapshot>("/api/r100-state/snapshot", undefined, { snapshotMode:"SAFE_REDACTED", collections:{}, safety:{redacted:true,noSecrets:true} });
export const createR100DurabilityProbe = () => request<R100ProbeResult>("/api/r100-state/probe", { method:"POST", body:JSON.stringify({ action:"CREATE_SAFE_R100_DURABILITY_PROBE" }) });
export const reloadR100StateManually = () => request<{reloaded:boolean;verification:R100VerificationSummary}>("/api/r100-state/reload", { method:"POST", body:JSON.stringify({ action:"RELOAD_R100_STATE_MANUALLY" }) });
