import { and, eq, sql } from "drizzle-orm";
import { parseAuditCaseRows } from "./auditReadContracts";
import { auditCaseIntakeRequestSchema, type AuditCaseIntakeRequest } from "@workspace/api-zod";
import { auditAssets, auditCases, auditClients, auditModuleCatalog, auditOperatorNotes, getDb, getPool, isDatabaseConfigured } from "@workspace/db";

const writeModes = ["disabled", "preview_only", "enabled"] as const;
type WriteMode = (typeof writeModes)[number];
type AuditDbProvider = "postgres" | "supabase_rest";
type AuditDbProviderMode = "auto" | AuditDbProvider;
const expectedAuditTables = ["audit_assets", "audit_cases", "audit_findings", "audit_evidences", "audit_operator_notes"] as const;
const publicAuditEnums = ["audit_case_status", "audit_asset_type", "audit_module_key", "audit_severity", "audit_evidence_type", "audit_report_type", "audit_task_status", "audit_proposal_status", "audit_revenue_status", "audit_connector_status"] as const;
type AuditSchemaDiagnosticCode = "AUDIT_TABLES_MISSING" | "DATABASE_CONNECTION_FAILED" | "PUBLIC_SCHEMA_NOT_VISIBLE" | "AUDIT_SCHEMA_NOT_READY" | "POSTGRES_AUTH_FAILED" | "POSTGRES_HOST_NOT_FOUND" | "SUPABASE_REST_AUTH_FAILED" | "SUPABASE_REST_NOT_CONFIGURED" | "SUPABASE_REST_ERROR";

type ProviderDiagnostic = { configured: boolean; available: boolean; status: "ready" | "missing_config" | "failed" | "not_checked"; code: AuditSchemaDiagnosticCode | null; errorClass?: string | null; foundTables?: string[]; missingTables?: string[] };

export function getAuditWriteMode(): WriteMode { const value = process.env.GXEON_AUDIT_WRITE_MODE; return writeModes.includes(value as WriteMode) ? (value as WriteMode) : "disabled"; }
export function getAuditDbProviderMode(): AuditDbProviderMode { const value = process.env.GXEON_AUDIT_DB_PROVIDER; return value === "postgres" || value === "supabase_rest" || value === "auto" ? value : "auto"; }
export function hasSupabaseRestConfig() { return Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY); }

export function detectPotentialSecrets(text = "") { const patterns = [/service_role/i, /DATABASE_URL/i, /postgres(?:ql)?:\/\//i, /sk-[A-Za-z0-9_-]{16,}/, /api[_ -]?key\s*[:=]/i, /password\s*=/i, /eyJ[A-Za-z0-9_-]{30,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/]; return { detected: patterns.some((pattern) => pattern.test(text)), message: "Potential secret detected. Remove credentials, tokens, service_role keys, DATABASE_URL values, passwords, and API keys before continuing." }; }
function normalizePriority(priority: AuditCaseIntakeRequest["priority"]) { return { low: 1, medium: 2, high: 3, critical: 4 }[priority]; }
function toDbAssetType(type: AuditCaseIntakeRequest["assetType"]) { return type.toUpperCase() as any; }
function selectedModuleSummaries(keys: AuditCaseIntakeRequest["selectedModules"]) { return keys.map((key) => auditModuleCatalog.find((module) => module.key === key)!).map(({ key, name, category, defaultWeight }) => ({ key, name, category, defaultWeight })); }

export function parseAuditCaseIntake(body: unknown) { const intake = auditCaseIntakeRequestSchema.parse(body); const secretScan = detectPotentialSecrets([intake.operatorNotes, intake.auditGoal, intake.tags?.join(" ")].filter(Boolean).join("\n")); if (secretScan.detected) { const error = new Error(secretScan.message) as Error & { statusCode?: number; code?: string }; error.statusCode = 400; error.code = "POTENTIAL_SECRET_DETECTED"; throw error; } return intake; }

export function buildAuditCasePreview(body: unknown) { const intake = parseAuditCaseIntake(body); const writeMode = getAuditWriteMode(); const writeAllowed = writeMode === "enabled" && process.env.GXEON_AUDIT_ALLOW_DB_WRITES === "true"; const warnings = ["Preview does not write to the database or external connectors.", ...(writeAllowed ? [] : ["Audit case writes are disabled until GXEON_AUDIT_WRITE_MODE=enabled and GXEON_AUDIT_ALLOW_DB_WRITES=true."]), ...(isDatabaseConfigured() || hasSupabaseRestConfig() ? [] : ["No Audit OS data provider is configured; create remains degraded-safe."])]; return { previewId: `preview_${Buffer.from(`${intake.assetName}:${intake.assetUrl}`).toString("base64url").slice(0, 18)}`, caseTitle: `${intake.assetName} · ${intake.auditGoal.slice(0, 80)}`, initialStatus: "DRAFT" as const, writeMode, writeAllowed, degradedSafe: !writeAllowed, selectedModules: selectedModuleSummaries(intake.selectedModules), intake, warnings, nextSafeAction: writeAllowed ? "Schema readiness will be checked before INSERT." : "Create and review preview only; do not claim a case was saved." }; }

function sanitizeDatabaseError(error: unknown) { const candidate = error as { name?: unknown; code?: unknown; message?: unknown }; const code = typeof candidate?.code === "string" ? candidate.code : undefined; const message = typeof candidate?.message === "string" ? candidate.message.toLowerCase() : ""; const messageClass = code === "28P01" ? "POSTGRES_AUTH_FAILED" : message.includes("enotfound") || code === "ENOTFOUND" ? "POSTGRES_HOST_NOT_FOUND" : code === "42P01" ? "UNDEFINED_TABLE" : code === "42501" ? "INSUFFICIENT_PRIVILEGE" : message.includes("connect") || message.includes("timeout") ? "CONNECTION_ERROR" : "DATABASE_ERROR"; return { name: typeof candidate?.name === "string" ? candidate.name : "DatabaseError", code, messageClass }; }
function codeFromSanitized(error: ReturnType<typeof sanitizeDatabaseError>): AuditSchemaDiagnosticCode { if (error.messageClass === "POSTGRES_AUTH_FAILED") return "POSTGRES_AUTH_FAILED"; if (error.messageClass === "POSTGRES_HOST_NOT_FOUND") return "POSTGRES_HOST_NOT_FOUND"; if (error.messageClass === "CONNECTION_ERROR") return "DATABASE_CONNECTION_FAILED"; if (error.code === "42P01") return "AUDIT_TABLES_MISSING"; if (error.code === "42501" || error.messageClass === "INSUFFICIENT_PRIVILEGE") return "PUBLIC_SCHEMA_NOT_VISIBLE"; return "AUDIT_SCHEMA_NOT_READY"; }
function classifyAuditSchemaProblem(foundTables: string[], error?: unknown): AuditSchemaDiagnosticCode { if (error) return codeFromSanitized(sanitizeDatabaseError(error)); if (expectedAuditTables.some((table) => !foundTables.includes(table))) return "AUDIT_TABLES_MISSING"; return "AUDIT_SCHEMA_NOT_READY"; }
function deriveProjectRefHintMasked() { const databaseUrl = process.env.DATABASE_URL; if (!databaseUrl) return null; try { const host = new URL(databaseUrl).hostname; const match = host.match(/([a-z0-9]{20})\.supabase\.(?:co|com)$/i) ?? host.match(/db\.([a-z0-9]{20})\.supabase\.(?:co|com)$/i); const ref = match?.[1]; return ref ? `${ref.slice(0, 4)}…${ref.slice(-4)}` : null; } catch { return null; } }

async function getPostgresDiagnostics(): Promise<ProviderDiagnostic & { foundEnums: string[]; currentSchema: string | null; currentDatabase: string | null }> { if (!isDatabaseConfigured()) return { configured: false, available: false, status: "missing_config", code: "DATABASE_CONNECTION_FAILED", foundTables: [], missingTables: [...expectedAuditTables], foundEnums: [], currentSchema: null, currentDatabase: null }; try { const pool = getPool(); const [tablesResult, enumsResult, contextResult] = await Promise.all([pool.query<{ table_name: string }>("select table_name from information_schema.tables where table_schema = 'public' and table_name like 'audit_%' order by table_name"), pool.query<{ typname: string }>("select t.typname from pg_type t join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' and t.typname like 'audit_%' order by t.typname"), pool.query<{ current_schema: string; current_database: string }>("select current_schema() as current_schema, current_database() as current_database")]); const foundTables = tablesResult.rows.map((row) => row.table_name); const missingTables = expectedAuditTables.filter((table) => !foundTables.includes(table)); return { configured: true, available: missingTables.length === 0, status: missingTables.length === 0 ? "ready" : "failed", code: missingTables.length === 0 ? null : "AUDIT_TABLES_MISSING", foundTables, missingTables, foundEnums: enumsResult.rows.map((row) => row.typname).filter((name) => publicAuditEnums.includes(name as any)), currentSchema: contextResult.rows[0]?.current_schema ?? null, currentDatabase: contextResult.rows[0]?.current_database ?? null }; } catch (error) { const safe = sanitizeDatabaseError(error); return { configured: true, available: false, status: "failed", code: codeFromSanitized(safe), errorClass: safe.messageClass, foundTables: [], missingTables: [...expectedAuditTables], foundEnums: [], currentSchema: null, currentDatabase: null }; } }

function supabaseRestUrl(path: string) { const base = process.env.SUPABASE_URL?.replace(/\/+$/, ""); if (!base) throw new Error("SUPABASE_REST_NOT_CONFIGURED"); return `${base}/rest/v1/${path}`; }
function supabaseHeaders(extra: Record<string, string> = {}) { const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!process.env.SUPABASE_URL || !key) throw new Error("SUPABASE_REST_NOT_CONFIGURED"); return { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", ...extra }; }
function classifySupabaseStatus(status: number, body = ""): AuditSchemaDiagnosticCode { if (status === 401 || status === 403) return "SUPABASE_REST_AUTH_FAILED"; if (status === 404 || /PGRST205|42P01|not exist|not found/i.test(body)) return "AUDIT_TABLES_MISSING"; return "SUPABASE_REST_ERROR"; }
export async function supabaseFetch(path: string, init?: RequestInit) { return fetch(supabaseRestUrl(path), { ...init, headers: supabaseHeaders((init?.headers as Record<string, string>) ?? {}) }); }
async function getSupabaseRestDiagnostics(): Promise<ProviderDiagnostic> { if (!hasSupabaseRestConfig()) return { configured: false, available: false, status: "missing_config", code: "SUPABASE_REST_NOT_CONFIGURED", foundTables: [], missingTables: [...expectedAuditTables] }; const foundTables: string[] = []; for (const table of expectedAuditTables) { const res = await supabaseFetch(`${table}?select=id&limit=1`); if (res.status === 200 || res.status === 206) { foundTables.push(table); continue; } const code = classifySupabaseStatus(res.status, await res.text().catch(() => "")); return { configured: true, available: false, status: "failed", code, errorClass: code, foundTables, missingTables: expectedAuditTables.filter((t) => !foundTables.includes(t)) }; } return { configured: true, available: true, status: "ready", code: null, foundTables, missingTables: [] }; }

export async function getActiveAuditProviderDiagnostics() { const providerMode = getAuditDbProviderMode(); const postgres: ProviderDiagnostic & { foundEnums?: string[]; currentSchema?: string | null; currentDatabase?: string | null } = providerMode === "supabase_rest" ? { configured: isDatabaseConfigured(), available: false, status: "not_checked" as const, code: null } : await getPostgresDiagnostics(); const supabaseRest: ProviderDiagnostic = providerMode === "postgres" || (providerMode === "auto" && postgres.available) ? { configured: hasSupabaseRestConfig(), available: false, status: "not_checked" as const, code: null } : await getSupabaseRestDiagnostics(); const activeProvider: AuditDbProvider | null = providerMode === "postgres" ? (postgres.available ? "postgres" : null) : providerMode === "supabase_rest" ? (supabaseRest.available ? "supabase_rest" : null) : postgres.available ? "postgres" : supabaseRest.available ? "supabase_rest" : null; return { providerMode, activeProvider, postgres, supabaseRest }; }

export async function getAuditSchemaDiagnostics() { const provider = await getActiveAuditProviderDiagnostics(); const active = provider.activeProvider === "postgres" ? provider.postgres : provider.activeProvider === "supabase_rest" ? provider.supabaseRest : provider.postgres.status === "failed" ? provider.postgres : provider.supabaseRest; const foundTables = active.foundTables ?? []; const missingTables = active.missingTables ?? [...expectedAuditTables]; const schemaReady = Boolean(provider.activeProvider && missingTables.length === 0); return { system: "GXEON Audit OS", readOnly: true, databaseConfigured: isDatabaseConfigured(), supabaseRestConfigured: hasSupabaseRestConfig(), expectedTables: [...expectedAuditTables], projectRefHintMasked: deriveProjectRefHintMasked(), safeMode: true, providerMode: provider.providerMode, activeProvider: provider.activeProvider, postgresAvailable: provider.postgres.available, supabaseRestAvailable: provider.supabaseRest.available, providerDiagnostics: provider, schemaReady, foundTables, missingTables, foundEnums: provider.activeProvider === "postgres" && "foundEnums" in provider.postgres ? provider.postgres.foundEnums : [], currentSchema: provider.activeProvider === "postgres" && "currentSchema" in provider.postgres ? provider.postgres.currentSchema : null, currentDatabase: provider.activeProvider === "postgres" && "currentDatabase" in provider.postgres ? provider.postgres.currentDatabase : null, code: schemaReady ? null : active.code ?? classifyAuditSchemaProblem(foundTables), error: active.errorClass ? { messageClass: active.errorClass } : null }; }

export async function validateAuditCaseWriteReadiness() { const writeMode = getAuditWriteMode(); if (writeMode !== "enabled" || process.env.GXEON_AUDIT_ALLOW_DB_WRITES !== "true") return { ok: false as const, status: 409, code: "WRITE_DISABLED", message: "Audit writes are disabled by feature flags." }; const diagnostics = await getAuditSchemaDiagnostics(); if (!diagnostics.schemaReady || !diagnostics.activeProvider) return { ok: false as const, status: 503, code: diagnostics.code ?? "AUDIT_SCHEMA_NOT_READY", message: "Audit schema is not accessible; no write was attempted.", diagnostics: { providerMode: diagnostics.providerMode, activeProvider: diagnostics.activeProvider, postgresAvailable: diagnostics.postgresAvailable, supabaseRestAvailable: diagnostics.supabaseRestAvailable, expectedTables: diagnostics.expectedTables, foundTables: diagnostics.foundTables, missingTables: diagnostics.missingTables, schemaReady: diagnostics.schemaReady, errorClass: diagnostics.error?.messageClass } }; return { ok: true as const, provider: diagnostics.activeProvider }; }
export async function validateAuditSchemaReadiness() { const readiness = await getAuditSchemaDiagnostics(); if (!readiness.schemaReady) throw new Error(readiness.code ?? "AUDIT_SCHEMA_NOT_READY"); return { ok: true as const }; }

export async function createAuditCase(body: unknown) { const preview = buildAuditCasePreview(body); const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: { system: "GXEON Audit OS", ok: false, code: readiness.code, message: readiness.message, preview } }; if (readiness.provider === "supabase_rest") return { status: 409, payload: { system: "GXEON Audit OS", ok: false, code: "SUPABASE_REST_CREATE_LIMITED_TO_BOOTSTRAP", message: "Supabase REST writes are enabled only for the protected first-case bootstrap path.", preview } }; const db = getDb(); const clientRows = preview.intake.clientName ? await db.insert(auditClients).values({ displayName: preview.intake.clientName, contactReference: preview.intake.clientEmail ?? preview.intake.clientPhone ?? null, metadata: { source: preview.intake.source } }).returning({ id: auditClients.id }) : []; const assetRows = await db.insert(auditAssets).values({ clientId: clientRows[0]?.id, type: toDbAssetType(preview.intake.assetType), label: preview.intake.assetName, referenceUrl: preview.intake.assetUrl, metadata: { tags: preview.intake.tags ?? [], selectedModules: preview.intake.selectedModules } }).returning({ id: auditAssets.id }); const caseRows = await db.insert(auditCases).values({ clientId: clientRows[0]?.id, assetId: assetRows[0]?.id, title: preview.caseTitle, status: "DRAFT", priority: normalizePriority(preview.intake.priority), metadata: { auditGoal: preview.intake.auditGoal, source: preview.intake.source, expectedDelivery: preview.intake.expectedDelivery, commercialIntent: preview.intake.commercialIntent ?? "none", selectedModules: preview.intake.selectedModules } }).returning({ id: auditCases.id }); if (preview.intake.operatorNotes) await db.insert(auditOperatorNotes).values({ caseId: caseRows[0]?.id, note: preview.intake.operatorNotes, operatorReference: "internal_operator", metadata: { redactionRequired: false } }); return { status: 201, payload: { system: "GXEON Audit OS", ok: true, code: "AUDIT_CASE_CREATED", message: "Audit case saved with guarded write flags enabled.", caseId: caseRows[0]?.id, preview } }; }

const firstInternalAuditCaseOperatorNotes = "Primeiro caso interno oficial do Audit OS. Não contém secrets. Não representa cliente externo. Não representa receita.";
const firstInternalAuditCasePayload: AuditCaseIntakeRequest = { assetName: "GXEON-AI Repository", assetUrl: "https://github.com/xpex-systems-ai/GXEON-AI", assetType: "github_repository", auditGoal: "Auditar o próprio repositório GXEON-AI como primeiro caso interno do Audit OS, verificando estrutura, módulos, schema, deploy readiness e segurança operacional.", selectedModules: ["github_repository_audit", "codebase_audit", "supabase_database_audit", "deployment_audit", "api_backend_audit", "ai_automation_audit"], priority: "high", source: "operator_manual", operatorNotes: firstInternalAuditCaseOperatorNotes };
function firstCaseResponse(created: boolean, status: "CREATED" | "ALREADY_EXISTS" | "BLOCKED", caseId: string | null, extra: Record<string, unknown> = {}) { return { system: "GXEON Audit OS", ok: status !== "BLOCKED", created, status, caseId, revenueConfirmed: 0, fakeClientCreated: false, connectorWrites: false, safeMode: true, ...extra }; }
async function bootstrapFirstInternalAuditCaseSupabaseRest() { const existingAssets = await (await supabaseFetch(`audit_assets?select=id&reference_url=eq.${encodeURIComponent(firstInternalAuditCasePayload.assetUrl)}&limit=1`)).json() as Array<{ id: string }>; if (existingAssets[0]?.id) { const existingCases = await (await supabaseFetch(`audit_cases?select=id,asset_id&asset_id=eq.${existingAssets[0].id}&limit=1`)).json() as Array<{ id: string; asset_id: string }>; if (existingCases[0]?.id) return { status: 200, payload: firstCaseResponse(false, "ALREADY_EXISTS", existingCases[0].id, { assetId: existingCases[0].asset_id }) }; } const preview = buildAuditCasePreview(firstInternalAuditCasePayload); const assetRows = await (await supabaseFetch("audit_assets", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ type: "GITHUB_REPOSITORY", label: "GXEON-AI Repository", reference_url: preview.intake.assetUrl, metadata: { internal_case: true, bootstrap_source: "supabase_rest_provider", fakeClientCreated: false } }) })).json() as Array<{ id: string }>; const assetId = assetRows[0]?.id; const caseRows = await (await supabaseFetch("audit_cases", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ asset_id: assetId, title: preview.caseTitle, status: "DRAFT", priority: 3, metadata: { auditGoal: preview.intake.auditGoal, source: "operator_manual", selectedModules: preview.intake.selectedModules, internal_case: true, bootstrap_source: "supabase_rest_provider", revenueConfirmed: 0, fakeClientCreated: false, connectorWrites: false } }) })).json() as Array<{ id: string }>; const caseId = caseRows[0]?.id; if (!caseId) throw new Error("AUDIT_BOOTSTRAP_CASE_ID_MISSING"); await supabaseFetch("audit_operator_notes", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ case_id: caseId, note: firstInternalAuditCaseOperatorNotes, operator_reference: "internal_operator", metadata: { bootstrap_source: "supabase_rest_provider", redactionRequired: false } }) }); return { status: 201, payload: firstCaseResponse(true, "CREATED", caseId, { assetId }) }; }
export async function bootstrapFirstInternalAuditCase() { const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: firstCaseResponse(false, "BLOCKED", null, { code: readiness.code, message: readiness.message, diagnostics: "diagnostics" in readiness ? readiness.diagnostics : undefined }) }; if (readiness.provider === "supabase_rest") return bootstrapFirstInternalAuditCaseSupabaseRest(); const db = getDb(); const existing = await db.select({ id: auditCases.id, assetId: auditCases.assetId }).from(auditCases).leftJoin(auditAssets, eq(auditCases.assetId, auditAssets.id)).where(and(eq(auditAssets.referenceUrl, firstInternalAuditCasePayload.assetUrl), sql`${auditCases.metadata}->>'source' = ${firstInternalAuditCasePayload.source}`)).limit(1); if (existing[0]?.id) return { status: 200, payload: firstCaseResponse(false, "ALREADY_EXISTS", existing[0].id, { assetId: existing[0].assetId }) }; const preview = buildAuditCasePreview(firstInternalAuditCasePayload); const assetRows = await db.insert(auditAssets).values({ type: toDbAssetType(preview.intake.assetType), label: preview.intake.assetName, referenceUrl: preview.intake.assetUrl, metadata: { internal_case: true, bootstrap_source: "railway_protected_endpoint", tags: preview.intake.tags ?? [], selectedModules: preview.intake.selectedModules, fakeClientCreated: false } }).returning({ id: auditAssets.id }); const caseRows = await db.insert(auditCases).values({ assetId: assetRows[0]?.id, title: preview.caseTitle, status: "DRAFT", priority: normalizePriority(preview.intake.priority), metadata: { auditGoal: preview.intake.auditGoal, source: preview.intake.source, selectedModules: preview.intake.selectedModules, internal_case: true, bootstrap_source: "railway_protected_endpoint", revenueConfirmed: 0, fakeClientCreated: false, connectorWrites: false } }).returning({ id: auditCases.id }); const caseId = caseRows[0]?.id; if (!caseId) throw new Error("AUDIT_BOOTSTRAP_CASE_ID_MISSING"); await db.insert(auditOperatorNotes).values({ caseId, note: preview.intake.operatorNotes ?? firstInternalAuditCaseOperatorNotes, operatorReference: "internal_operator", metadata: { bootstrap_source: "railway_protected_endpoint", redactionRequired: false } }); return { status: 201, payload: firstCaseResponse(true, "CREATED", caseId, { assetId: assetRows[0]?.id }) }; }

async function listSupabaseRestCases() { const res = await supabaseFetch("audit_cases?select=*&order=created_at.desc&limit=50"); if (!res.ok) throw new Error(classifySupabaseStatus(res.status, await res.text().catch(() => ""))); return parseAuditCaseRows(await res.json()); }
export async function listAuditCases() { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") { try { const items = await listSupabaseRestCases(); return { degradedSafe: false, databaseConfigured: isDatabaseConfigured(), provider: "supabase_rest", count: items.length, items, nextSafeAction: "Open a case detail or create the protected first case from Bootstrap sem terminal." }; } catch { return { degradedSafe: true, databaseConfigured: isDatabaseConfigured(), provider: "supabase_rest", count: 0, items: [], nextSafeAction: "Supabase REST case listing failed safely; run schema diagnostics." }; } } if (!isDatabaseConfigured()) return { degradedSafe: true, databaseConfigured: false, count: 0, items: [], nextSafeAction: "Configure DATABASE_URL or Supabase REST before read-backed case listing." }; try { const items = await getDb().select().from(auditCases).limit(50); return { degradedSafe: false, databaseConfigured: true, provider: "postgres", count: items.length, items, nextSafeAction: "Open a case detail or create a preview for a new case." }; } catch { if (diagnostics.supabaseRest.available) { const items = await listSupabaseRestCases(); return { degradedSafe: false, databaseConfigured: true, provider: "supabase_rest", count: items.length, items, nextSafeAction: "Postgres failed; Supabase REST fallback returned real cases." }; } return { degradedSafe: true, databaseConfigured: true, count: 0, items: [], nextSafeAction: "Audit schema not ready; validate schema before enabling writes." }; } }
export async function getAuditCaseById(caseId: string) { if (!isDatabaseConfigured()) return null; try { return (await getDb().select().from(auditCases).where(eq(auditCases.id, caseId)).limit(1))[0] ?? null; } catch { return null; } }
export function getAuditCaseTimeline(caseId: string) { return { caseId, degradedSafe: true, items: [{ status: "DRAFT", label: "Intake preview/create initialized", generatedAt: new Date().toISOString() }] }; }
