export type AuditOfferKey = "audit_express" | "technical_audit" | "audit_assisted_fixes" | "operational_ai_setup" | "gxeon_consulting_os";

export const auditOfferCatalog = [
  { key: "audit_express", name: "GXEON Express Audit", namePtBr: "Auditoria Expressa GXEON", startingTargetBrl: 100, priceLabel: "R$100", status: "planned_offer_proof_based", description: "Diagnóstico rápido de um ativo digital com achados principais, evidências e resumo executivo.", deliverables: ["1 audit case", "minimum 3 findings when available", "minimum 3 evidences when available", "executive summary", "priority recommendations"] },
  { key: "technical_audit", name: "Complete Technical Audit", namePtBr: "Auditoria Técnica Completa", startingTargetBrl: 300, priceLabel: "R$300", status: "planned_offer_proof_based", description: "Auditoria técnica com score, relatório completo, evidências, severidade e plano de correção.", deliverables: ["audit report", "score snapshot", "findings grouped by severity", "evidence references", "correction roadmap"] },
  { key: "audit_assisted_fixes", name: "Audit + Assisted Fixes", namePtBr: "Auditoria + Correções Assistidas", startingTargetBrl: 500, priceLabel: "R$500+", status: "planned_offer_proof_based", description: "Auditoria com apoio na correção dos principais problemas encontrados.", deliverables: ["technical audit", "fix plan", "implementation checklist", "operator-guided correction support", "before/after evidence"] },
  { key: "operational_ai_setup", name: "Operational AI Setup", namePtBr: "Setup IA Operacional", startingTargetBrl: 700, priceLabel: "R$700+", status: "commercial_package_planned", description: "Organização de operação digital com IA, repo, deploy, painel, automações e fluxo de evidência.", deliverables: ["operational diagnosis", "tooling map", "implementation plan", "automation-ready workflow", "handoff checklist"] },
  { key: "gxeon_consulting_os", name: "GXEON Consulting OS", namePtBr: "GXEON Consulting OS", startingTargetBrl: 1500, priceLabel: "R$1500+", status: "commercial_priority", description: "Implantação estratégica de sistema operacional assistido por IA para operação, auditoria, proposta e execução.", deliverables: ["strategic audit", "system blueprint", "implementation roadmap", "AI-assisted workflow", "executive handoff"] },
] as const;

export function listAuditOffers() { return { system: "GXEON Audit OS", offerFamily: "GXEON Audit OS Services", readOnly: true, sanitized: true, proofRequired: true, paymentCalls: false, autoSend: false, revenueConfirmed: 0, offers: auditOfferCatalog }; }
export function getAuditOffer(key: string) { return auditOfferCatalog.find((offer) => offer.key === key); }
