import { eq } from "drizzle-orm";
import { auditProposals, getDb, isDatabaseConfigured } from "@workspace/db";
import { detectPotentialSecrets, getActiveAuditProviderDiagnostics, supabaseFetch, validateAuditCaseWriteReadiness } from "./auditCaseService";
import { auditCaseExists, listEvidencesByCase, listFindingsByCase } from "./auditEvidenceFindingService";
import { auditScoreReportCounts } from "./auditMissionRunnerService";
import { getAuditOffer } from "./auditOfferCatalogService";

const languages = ["pt-BR", "en-US"] as const;
const audiences = ["founder", "small_business", "agency", "developer", "investor", "internal", "other"] as const;
export const proposalStatuses = ["DRAFT", "READY_FOR_OPERATOR_REVIEW", "OPERATOR_SENT_MANUALLY", "ACCEPTED_MANUALLY", "REJECTED_MANUALLY", "ARCHIVED"] as const;
type ProposalStatus = (typeof proposalStatuses)[number];
function fail(statusCode: number, code: string, message: string): never { const e = new Error(message) as Error & { statusCode: number; code: string }; e.statusCode = statusCode; e.code = code; throw e; }
function str(v: unknown, name: string) { if (typeof v !== "string" || !v.trim()) fail(400, "INVALID_FIELD", `${name} is required.`); return v.trim(); }
function opt(v: unknown) { return typeof v === "string" && v.trim() ? v.trim() : undefined; }
function assertSafe(...values: unknown[]) { const text = values.map((v) => typeof v === "string" ? v : JSON.stringify(v ?? "")).join("\n"); const scan = detectPotentialSecrets(text); if (scan.detected) fail(400, "POTENTIAL_SECRET_DETECTED", scan.message); }
function safeMeta(metadata: unknown) { if (!metadata || typeof metadata !== "object" || Array.isArray(metadata)) return {}; assertSafe(metadata); return metadata as Record<string, unknown>; }
export function authorizeAuditProposalOperator(header: unknown) { const value = typeof header === "string" ? header : ""; const token = value.startsWith("Bearer ") ? value.slice(7).trim() : ""; if (!token) return { ok: false as const, status: 401, code: "OPERATOR_TOKEN_REQUIRED", message: "Authorization: Bearer operator token is required." }; const expected = process.env.GXEON_AUDIT_OPERATOR_TOKEN || process.env.GXEON_AUDIT_MISSION_RUNNER_TOKEN; if (!expected || token !== expected) return { ok: false as const, status: 403, code: "OPERATOR_TOKEN_INVALID", message: "Operator token is invalid or not configured." }; return { ok: true as const }; }
function sanitize(row: any) { const metadata = row?.metadata && !detectPotentialSecrets(JSON.stringify(row.metadata)).detected ? row.metadata : {}; return { id: row?.id, proposalId: row?.id, caseId: row?.case_id ?? row?.caseId ?? metadata.caseId, title: row?.title, status: metadata.proposalStatus ?? row?.status ?? "DRAFT", offerKey: metadata.offerKey, currency: row?.currency ?? "BRL", priceTarget: Number(row?.amount ?? metadata.priceTarget ?? 0), proposalCopy: metadata.proposalCopy, scope: metadata.scope ?? [], deliverables: metadata.deliverables ?? [], metadata: { language: metadata.language, manualFirst: true, proofRequired: true }, createdAt: row?.created_at ?? row?.createdAt, updatedAt: row?.updated_at ?? row?.updatedAt }; }
async function listProposals(caseId?: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") return (await (await supabaseFetch(`audit_proposals?select=*&${caseId ? `case_id=eq.${encodeURIComponent(caseId)}&` : ""}order=created_at.desc&limit=100`)).json() as any[]).map(sanitize); if (!isDatabaseConfigured()) return []; const q = getDb().select().from(auditProposals).limit(100); const rows = caseId ? await getDb().select().from(auditProposals).where(eq(auditProposals.caseId, caseId)).limit(100) : await q; return rows.map(sanitize); }
export async function getProposalReadiness() { const diagnostics = await getActiveAuditProviderDiagnostics(); let caseId: string | undefined; if (diagnostics.activeProvider === "supabase_rest") caseId = ((await (await supabaseFetch("audit_cases?select=id&order=created_at.desc&limit=1")).json()) as any[])[0]?.id; else if (isDatabaseConfigured()) caseId = (await getDb().select({ id: (await import("@workspace/db")).auditCases.id }).from((await import("@workspace/db")).auditCases).limit(1))[0]?.id; const counts = caseId ? await auditScoreReportCounts(caseId) : { scoresCount: 0, reportsCount: 0 }; const ef = caseId ? await Promise.all([listFindingsByCase(caseId), listEvidencesByCase(caseId)]) : [{ items: [] as unknown[] }, { items: [] as unknown[] }]; const proposals = caseId ? await listProposals(caseId) : []; return { system: "GXEON Audit OS", readOnly: true, sanitized: true, caseId: caseId ?? null, caseExists: Boolean(caseId), findingsCount: ef[0].items.length, evidencesCount: ef[1].items.length, scoreCount: counts.scoresCount, reportCount: counts.reportsCount, proposalCount: proposals.length, readyForProposal: Boolean(caseId && (counts.reportsCount > 0 || ef[0].items.length > 0 || ef[1].items.length > 0)), readyForCommercialSend: false, revenueConfirmed: 0, proofRequired: true, paymentCalls: false, autoSend: false }; }
export async function buildProposalPreview(body: any) { const caseId = str(body?.caseId, "caseId"); const offerKey = str(body?.offerKey, "offerKey"); const offer = getAuditOffer(offerKey); if (!offer) fail(400, "INVALID_OFFER_KEY", "offerKey is not in the official offer catalog."); const language = languages.includes(body?.language) ? body.language : "pt-BR"; if (body?.audienceType && !audiences.includes(body.audienceType)) fail(400, "INVALID_AUDIENCE_TYPE", "audienceType is not allowed."); assertSafe(body?.notes, body?.prospectName, body?.assetName, body?.metadata); const [findings, evidences, counts] = await Promise.all([listFindingsByCase(caseId), listEvidencesByCase(caseId), auditScoreReportCounts(caseId).catch(() => ({ scoresCount: 0, reportsCount: 0 }))]); const preliminary = counts.reportsCount === 0 || findings.items.length === 0 || evidences.items.length === 0; const title = language === "en-US" ? `Proposal — ${offer.name}` : `Proposta — ${offer.namePtBr}`; const opening = language === "en-US" ? `This ${offer.name} proposal converts the selected audit case into an operator-reviewed commercial draft.` : `Esta proposta de ${offer.namePtBr} transforma o caso de auditoria selecionado em um rascunho comercial revisado pelo operador.`; const proposalCopy = [`${preliminary ? "PRELIMINARY · " : ""}${title}`, opening, `Asset: ${opt(body?.assetName) ?? "selected audit asset"}`, `Evidence: ${evidences.items.length} · Findings: ${findings.items.length} · Reports: ${counts.reportsCount}`, `Starting target: BRL ${offer.startingTargetBrl}. Not confirmed revenue.`].join("\n\n"); return { system: "GXEON Audit OS", ok: true, noWrite: true, sanitized: true, preliminary, requiresOperatorReview: true, caseId, offerKey, proposal: { title, proposalCopy, scope: offer.deliverables, deliverables: offer.deliverables, priceTarget: offer.startingTargetBrl, currency: "BRL", language }, disclaimers: ["No auto-send.", "No payment call.", "No checkout or invoice.", "Revenue requires real acceptance and payment proof in a future Revenue Ledger mission."], nextOperatorAction: "Review copy manually, edit if needed, then save DRAFT with temporary in-memory operator token if approved." }; }
export async function createProposal(body: any) { const preview = await buildProposalPreview({ ...body, offerKey: body?.offerKey, caseId: body?.caseId, language: body?.language }); if (!await auditCaseExists(preview.caseId)) return { status: 404, payload: { ok: false, code: "AUDIT_CASE_NOT_FOUND", preview } }; assertSafe(body?.title, body?.proposalCopy, body?.scope, body?.deliverables, body?.metadata); const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: { ok: false, code: readiness.code, message: readiness.message, preview } }; const metadata = { ...safeMeta(body?.metadata), offerKey: preview.offerKey, proposalStatus: "DRAFT", proposalCopy: str(body?.proposalCopy, "proposalCopy"), scope: Array.isArray(body?.scope) ? body.scope : preview.proposal.scope, deliverables: Array.isArray(body?.deliverables) ? body.deliverables : preview.proposal.deliverables, language: languages.includes(body?.language) ? body.language : "pt-BR", proofRequired: true, paymentCalls: false, autoSend: false };
 const values = { case_id: preview.caseId, title: str(body?.title, "title"), status: "DRAFT", currency: opt(body?.currency) ?? "BRL", amount: Number(body?.priceTarget ?? preview.proposal.priceTarget), metadata };
 const rows = readiness.provider === "supabase_rest" ? await (await supabaseFetch("audit_proposals", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(values) })).json() as any[] : await getDb().insert(auditProposals).values({ caseId: values.case_id, title: values.title, status: "DRAFT", currency: values.currency, amount: String(values.amount), metadata }).returning(); return { status: 201, payload: { ok: true, code: "AUDIT_PROPOSAL_DRAFT_CREATED", proposalId: rows[0]?.id, status: "DRAFT", proposal: sanitize(rows[0]) } }; }
export async function listProposalsByCase(caseId: string) { return { system: "GXEON Audit OS", readOnly: true, sanitized: true, count: (await listProposals(caseId)).length, items: await listProposals(caseId) }; }
export async function getProposal(id: string) { const rows = await listProposals(); return rows.find((p) => p.id === id) ?? null; }
export function previewProposalStatus(id: string, targetStatus: string) { if (!proposalStatuses.includes(targetStatus as ProposalStatus) || targetStatus === "DRAFT") fail(400, "INVALID_PROPOSAL_STATUS", "Only non-financial manual target statuses are allowed."); return { system: "GXEON Audit OS", noWrite: true, proposalId: id, targetStatus, allowed: true, paymentCalls: false, revenueEventCreated: false, message: "Payment/revenue proof belongs to future MISSION_008_REVENUE_LEDGER_AND_PAYMENT_PROOF." }; }
export async function updateProposalStatus(id: string, targetStatus: string) { previewProposalStatus(id, targetStatus); const existing = await getProposal(id); if (!existing) return { status: 404, payload: { ok: false, code: "AUDIT_PROPOSAL_NOT_FOUND" } }; const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: { ok: false, code: readiness.code, message: readiness.message } }; const metadata = { ...(existing.metadata ?? {}), proposalStatus: targetStatus, paymentCalls: false, revenueEventCreated: false }; if (readiness.provider === "supabase_rest") await supabaseFetch(`audit_proposals?id=eq.${encodeURIComponent(id)}`, { method: "PATCH", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ metadata }) }); else await getDb().update(auditProposals).set({ metadata }).where(eq(auditProposals.id, id)); return { status: 200, payload: { ok: true, proposalId: id, status: targetStatus, paymentCalls: false, revenueEventCreated: false } }; }
