import { eq } from "drizzle-orm";
import { auditCases, auditEvidences, auditFindings, getDb, isDatabaseConfigured } from "@workspace/db";
import { detectPotentialSecrets, getActiveAuditProviderDiagnostics, getAuditWriteMode, supabaseFetch, validateAuditCaseWriteReadiness } from "./auditCaseService";

const severities = ["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"] as const;
const evidenceTypes = ["URL", "SCREENSHOT", "LOG_EXCERPT", "REPOSITORY_REFERENCE", "SCHEMA_REFERENCE", "REDACTED_CONFIG", "WORKFLOW_REFERENCE", "OPERATOR_NOTE", "OTHER"] as const;
const moduleKeys = ["website_audit", "ecommerce_audit", "ux_checkout_audit", "seo_basic_audit", "tracking_pixel_audit", "security_basic_audit", "github_repository_audit", "codebase_audit", "supabase_database_audit", "deployment_audit", "api_backend_audit", "ai_automation_audit", "business_offer_audit", "funnel_audit", "content_landing_page_audit"] as const;

type Severity = (typeof severities)[number];
type EvidenceType = (typeof evidenceTypes)[number];

type FindingInput = { caseId?: unknown; moduleKey?: unknown; title?: unknown; severity?: unknown; summary?: unknown; recommendation?: unknown; metadata?: unknown };
type EvidenceInput = { caseId?: unknown; findingId?: unknown; type?: unknown; title?: unknown; referenceUrl?: unknown; redactedText?: unknown; metadata?: unknown };

function fail(statusCode: number, code: string, message: string): never { const error = new Error(message) as Error & { statusCode: number; code: string }; error.statusCode = statusCode; error.code = code; throw error; }
function requiredString(value: unknown, field: string) { if (typeof value !== "string" || !value.trim()) fail(400, "INVALID_BODY", `${field} is required.`); return value.trim(); }
function optionalString(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : null; }
function metadataObject(value: unknown) { if (value == null) return {}; if (typeof value !== "object" || Array.isArray(value)) fail(400, "INVALID_METADATA", "metadata must be an object."); return value as Record<string, unknown>; }
function assertNoSecrets(...values: unknown[]) { const text = values.map((value) => typeof value === "string" ? value : JSON.stringify(value ?? {})).join("\n"); const scan = detectPotentialSecrets(text); if (scan.detected) fail(400, "POTENTIAL_SECRET_DETECTED", scan.message); }
function writeAllowed() { return getAuditWriteMode() === "enabled" && process.env.GXEON_AUDIT_ALLOW_DB_WRITES === "true"; }

export function authorizeAuditOperator(header: unknown) { const value = typeof header === "string" ? header : ""; const token = value.startsWith("Bearer ") ? value.slice(7).trim() : ""; if (!token) return { ok: false as const, status: 401, code: "OPERATOR_TOKEN_REQUIRED", message: "Authorization: Bearer token is required." }; const expected = process.env.GXEON_AUDIT_OPERATOR_TOKEN || process.env.GXEON_AUDIT_BOOTSTRAP_TOKEN; if (!expected) return { ok: false as const, status: 403, code: "OPERATOR_TOKEN_NOT_CONFIGURED", message: "Operator token is not configured." }; if (token !== expected) return { ok: false as const, status: 403, code: "OPERATOR_TOKEN_INVALID", message: "Operator token is invalid." }; return { ok: true as const }; }

export function buildFindingPreview(body: unknown) { const input = body as FindingInput; const caseId = requiredString(input.caseId, "caseId"); const title = requiredString(input.title, "title"); const summary = requiredString(input.summary, "summary"); const severity = (typeof input.severity === "string" ? input.severity : "INFO") as Severity; if (!severities.includes(severity)) fail(400, "INVALID_SEVERITY", "Allowed severities: INFO, LOW, MEDIUM, HIGH, CRITICAL."); const moduleKey = optionalString(input.moduleKey); if (moduleKey && !moduleKeys.includes(moduleKey as any)) fail(400, "INVALID_MODULE_KEY", "moduleKey is not in the official Audit OS catalog."); const recommendation = optionalString(input.recommendation); const metadata = metadataObject(input.metadata); assertNoSecrets(title, summary, recommendation, metadata); return { previewId: `finding_preview_${Buffer.from(`${caseId}:${title}`).toString("base64url").slice(0, 18)}`, writeAllowed: writeAllowed(), noWrite: true, finding: { caseId, moduleKey, title, severity, summary, recommendation, status: "OPEN", metadata }, warnings: ["Preview endpoint does not write.", "Manual-first: create requires operator token and write flags."] }; }

export function buildEvidencePreview(body: unknown) { const input = body as EvidenceInput; const caseId = requiredString(input.caseId, "caseId"); const type = (typeof input.type === "string" ? input.type : "OPERATOR_NOTE") as EvidenceType; if (!evidenceTypes.includes(type)) fail(400, "INVALID_EVIDENCE_TYPE", "Evidence type is not allowed."); const title = requiredString(input.title, "title"); const referenceUrl = optionalString(input.referenceUrl); const redactedText = optionalString(input.redactedText); const findingId = optionalString(input.findingId); const metadata = metadataObject(input.metadata); assertNoSecrets(title, referenceUrl, redactedText, metadata); return { previewId: `evidence_preview_${Buffer.from(`${caseId}:${title}`).toString("base64url").slice(0, 18)}`, writeAllowed: writeAllowed(), noWrite: true, noScraping: true, evidence: { caseId, findingId, type, title, referenceUrl, redactedText, metadata }, warnings: ["Preview endpoint does not write.", "Evidence is reference-only: GXEON will not fetch, scrape, crawl, or download referenceUrl."] }; }

export async function auditCaseExists(caseId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") { const rows = await (await supabaseFetch(`audit_cases?select=id&id=eq.${encodeURIComponent(caseId)}&limit=1`)).json() as Array<{ id: string }>; return Boolean(rows[0]?.id); } if (!isDatabaseConfigured()) return false; return Boolean((await getDb().select({ id: auditCases.id }).from(auditCases).where(eq(auditCases.id, caseId)).limit(1))[0]?.id); }
async function findingExists(findingId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") { const rows = await (await supabaseFetch(`audit_findings?select=id&id=eq.${encodeURIComponent(findingId)}&limit=1`)).json() as Array<{ id: string }>; return Boolean(rows[0]?.id); } if (!isDatabaseConfigured()) return false; return Boolean((await getDb().select({ id: auditFindings.id }).from(auditFindings).where(eq(auditFindings.id, findingId)).limit(1))[0]?.id); }

export async function createFinding(body: unknown) { const preview = buildFindingPreview(body); if (!await auditCaseExists(preview.finding.caseId)) return { status: 404, payload: { ok: false, code: "AUDIT_CASE_NOT_FOUND", message: "caseId does not exist.", preview } }; const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: { ok: false, code: readiness.code, message: readiness.message, preview } }; if (readiness.provider === "supabase_rest") { const rows = await (await supabaseFetch("audit_findings", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ case_id: preview.finding.caseId, module_key: preview.finding.moduleKey, title: preview.finding.title, severity: preview.finding.severity, summary: preview.finding.summary, recommendation: preview.finding.recommendation, status: "OPEN", metadata: preview.finding.metadata }) })).json() as Array<{ id: string }>; return { status: 201, payload: { ok: true, code: "AUDIT_FINDING_CREATED", findingId: rows[0]?.id, finding: { ...preview.finding, id: rows[0]?.id } } }; } const rows = await getDb().insert(auditFindings).values({ caseId: preview.finding.caseId, moduleKey: preview.finding.moduleKey as any, title: preview.finding.title, severity: preview.finding.severity, summary: preview.finding.summary, recommendation: preview.finding.recommendation, status: "OPEN", metadata: preview.finding.metadata }).returning({ id: auditFindings.id }); return { status: 201, payload: { ok: true, code: "AUDIT_FINDING_CREATED", findingId: rows[0]?.id, finding: { ...preview.finding, id: rows[0]?.id } } }; }

export async function createEvidence(body: unknown) { const preview = buildEvidencePreview(body); if (!await auditCaseExists(preview.evidence.caseId)) return { status: 404, payload: { ok: false, code: "AUDIT_CASE_NOT_FOUND", message: "caseId does not exist.", preview } }; if (preview.evidence.findingId && !await findingExists(preview.evidence.findingId)) return { status: 404, payload: { ok: false, code: "AUDIT_FINDING_NOT_FOUND", message: "findingId does not exist.", preview } }; const readiness = await validateAuditCaseWriteReadiness(); if (!readiness.ok) return { status: readiness.status, payload: { ok: false, code: readiness.code, message: readiness.message, preview } }; if (readiness.provider === "supabase_rest") { const rows = await (await supabaseFetch("audit_evidences", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ case_id: preview.evidence.caseId, finding_id: preview.evidence.findingId, type: preview.evidence.type, title: preview.evidence.title, reference_url: preview.evidence.referenceUrl, redacted_text: preview.evidence.redactedText, metadata: preview.evidence.metadata }) })).json() as Array<{ id: string }>; return { status: 201, payload: { ok: true, code: "AUDIT_EVIDENCE_CREATED", evidenceId: rows[0]?.id, evidence: { ...preview.evidence, id: rows[0]?.id } } }; } const rows = await getDb().insert(auditEvidences).values({ caseId: preview.evidence.caseId, findingId: preview.evidence.findingId, type: preview.evidence.type, title: preview.evidence.title, referenceUrl: preview.evidence.referenceUrl, redactedText: preview.evidence.redactedText, metadata: preview.evidence.metadata }).returning({ id: auditEvidences.id }); return { status: 201, payload: { ok: true, code: "AUDIT_EVIDENCE_CREATED", evidenceId: rows[0]?.id, evidence: { ...preview.evidence, id: rows[0]?.id } } }; }

export async function listFindingsByCase(caseId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") return { provider: "supabase_rest", items: await (await supabaseFetch(`audit_findings?select=*&case_id=eq.${encodeURIComponent(caseId)}&order=created_at.desc`)).json() }; if (!isDatabaseConfigured()) return { provider: null, items: [] }; return { provider: "postgres", items: await getDb().select().from(auditFindings).where(eq(auditFindings.caseId, caseId)).limit(100) }; }
export async function getFinding(findingId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") return (await (await supabaseFetch(`audit_findings?select=*&id=eq.${encodeURIComponent(findingId)}&limit=1`)).json() as any[])[0] ?? null; if (!isDatabaseConfigured()) return null; return (await getDb().select().from(auditFindings).where(eq(auditFindings.id, findingId)).limit(1))[0] ?? null; }
export async function listEvidencesByCase(caseId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") return { provider: "supabase_rest", items: await (await supabaseFetch(`audit_evidences?select=*&case_id=eq.${encodeURIComponent(caseId)}&order=created_at.desc`)).json() }; if (!isDatabaseConfigured()) return { provider: null, items: [] }; return { provider: "postgres", items: await getDb().select().from(auditEvidences).where(eq(auditEvidences.caseId, caseId)).limit(100) }; }
export async function listEvidencesByFinding(findingId: string) { const diagnostics = await getActiveAuditProviderDiagnostics(); if (diagnostics.activeProvider === "supabase_rest") return { provider: "supabase_rest", items: await (await supabaseFetch(`audit_evidences?select=*&finding_id=eq.${encodeURIComponent(findingId)}&order=created_at.desc`)).json() }; if (!isDatabaseConfigured()) return { provider: null, items: [] }; return { provider: "postgres", items: await getDb().select().from(auditEvidences).where(eq(auditEvidences.findingId, findingId)).limit(100) }; }
export async function auditEvidenceFindingCounts(caseId: string) { const [findings, evidences] = await Promise.all([listFindingsByCase(caseId), listEvidencesByCase(caseId)]); return { findingsCount: findings.items.length, evidencesCount: evidences.items.length, provider: findings.provider ?? evidences.provider }; }
