import { executionSafetyFlags, type ExecutionPackActionResult, type GitHubDemandExecutionPack } from "./githubDemandExecutionTypes";
const base = (pack: GitHubDemandExecutionPack) => ({ packId: pack.id, mode: "PREVIEW_ONLY" as const, safetyFlags: executionSafetyFlags, nextManualAction: pack.nextManualAction });
export const createTaskPreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "TASK_PREVIEW", status: "TASK_PREVIEW_CREATED", ...base(pack), preview: { title: pack.taskPreviewPayload.title, checklist: pack.technicalChecklist, evidenceChecklist: pack.evidenceChecklist, copyOnly: true } });
export const createBrokerRoutePreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "BROKER_ROUTE_PREVIEW", status: "BROKER_ROUTE_PREPARED", ...base(pack), preview: { route: pack.brokerRouteHint.route, priority: pack.brokerRouteHint.priority, externalActionsDisabled: true } });
export const createExecutionCenterPreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "EXECUTION_CENTER_PREVIEW", status: "EXECUTION_PREVIEW_CREATED", ...base(pack), preview: { checklist: pack.technicalChecklist, artifacts: pack.deliveryArtifacts, runtimeExecutionDisabled: true, noRepoClone: true } });
export const createValidationPreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "VALIDATION_PREVIEW", status: "VALIDATION_PREVIEW_CREATED", ...base(pack), preview: { validationChecklist: pack.validationChecklist, evidenceChecklist: pack.evidenceChecklist } });
export const createReleasePreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "RELEASE_PREVIEW", status: "RELEASE_PREVIEW_CREATED", ...base(pack), preview: { releaseSummaryDraft: pack.operatorSummary, deliveryArtifacts: pack.deliveryArtifacts, githubWriteDisabled: true } });
export const createLedgerPreviewFromExecutionPack = (pack: GitHubDemandExecutionPack): ExecutionPackActionResult => ({ actionType: "LEDGER_PREVIEW", status: "LEDGER_PREVIEW_CREATED", ...base(pack), preview: pack.ledgerPreview });

export { createOperatorDeliveryWorkspace as createDeliveryWorkspacePreviewFromExecutionPack } from "../deliveryWorkspace/operatorDeliveryWorkspaceStore";
