import type { GitHubDemandQueryPack } from "./githubDemandTypes";
export const GITHUB_DEMAND_MAX_CANDIDATES = 10;
export const githubDemandQueryPacks: GitHubDemandQueryPack[] = [
 {id:"explicit_bounty",label:"Explicit bounty / reward",query:"\"bounty\" OR \"reward\" OR \"paid\" \"help wanted\"",categoryHint:"EXPLICIT_BOUNTY",monetizationRouteHint:"BOUNTY_ATTEMPT",riskNotes:["Verify bounty source and terms manually.","Reward is never guaranteed."],operatorUseCase:"Find issues with explicit payment-like language.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
 {id:"agent_mcp_integration",label:"Agent / MCP integration need",query:"\"MCP\" OR \"agent\" OR \"tool calling\" OR \"model context protocol\" \"help wanted\"",categoryHint:"AGENT_INTEGRATION_NEED",monetizationRouteHint:"AGENT_MCP_INTEGRATION_OFFER",riskNotes:["Likely service lead unless budget is explicit."],operatorUseCase:"Spot connector and agent setup demand.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
 {id:"deploy_rescue",label:"Deploy / CI rescue",query:"\"Vercel\" OR \"Railway\" OR \"GitHub Actions\" OR \"CI\" \"help wanted\"",categoryHint:"DEPLOY_CI_RESCUE",monetizationRouteHint:"DEPLOY_RESCUE_OFFER",riskNotes:["Do not run candidate repository code."],operatorUseCase:"Find deploy rescue and CI triage opportunities.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
 {id:"supabase_database",label:"Supabase / database / RLS",query:"\"Supabase\" OR \"RLS\" OR \"Postgres\" \"help wanted\"",categoryHint:"SUPABASE_RLS_OR_DATABASE",monetizationRouteHint:"DATA_API_CONNECTOR_OFFER",riskNotes:["Database/security work needs manual scope review."],operatorUseCase:"Find RLS, Postgres and backend data needs.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
 {id:"docs_template_quick_win",label:"Docs / README / examples",query:"\"documentation\" OR \"README\" OR \"example\" \"good first issue\"",categoryHint:"DOCS_TEMPLATE_REQUEST",monetizationRouteHint:"DOCS_TEMPLATE_OFFER",riskNotes:["Often unpaid OSS; do not infer budget."],operatorUseCase:"Find low-risk template/doc service previews.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
 {id:"api_data_connector",label:"API / data connector need",query:"\"API\" OR \"webhook\" OR \"connector\" \"help wanted\"",categoryHint:"DATA_API_NEED",monetizationRouteHint:"DATA_API_CONNECTOR_OFFER",riskNotes:["Check API terms and auth boundaries manually."],operatorUseCase:"Find API/webhook connector demand.",maxPreviewCandidates:5,noScraping:true,noExternalWrites:true},
];
export const getGitHubDemandQueryPack=(id?:string)=>githubDemandQueryPacks.find((p)=>p.id===id)??null;
