// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ReentrancyGuard$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ReentrancyGuard";
  readonly sourceName: "contracts/interfaces/ReentrancyGuard.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ReentrancyGuard.sol";
  readonly buildInfoId: "solc-0_8_20-2ea50d980e193d3bbf29660fb6aa9a04bb1e5ff5";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ReentrancyGuard"]: ReentrancyGuard$Type;
    ["contracts/interfaces/ReentrancyGuard.sol:ReentrancyGuard"]: ReentrancyGuard$Type;
  }
}