import { Router, type IRouter, type Response } from "express";
import { agentEconomySources } from "../agentEconomy/agentEconomySources";
import { attachConnectorPreview, createIntegrationCandidatePreview, getIntegrationCandidatePreviewById, listIntegrationCandidatePreviews, updateIntegrationCandidateState } from "../agentEconomy/integrationCandidateStore";
import { previewBoundary } from "../agentEconomy/agentEconomyTypes";
const router: IRouter = Router();
router.use("/agent-economy", (_req, res, next) => { res.setHeader("Cache-Control", "no-store"); next(); });
function safeError(res: Response, error: unknown, fallback = "AGENT_ECONOMY_REQUEST_FAILED", status = 400) { const message = error instanceof Error ? error.message : fallback; res.status(status).json({ success: false, data: previewBoundary, error: message, message }); }
function status() { const candidates = listIntegrationCandidatePreviews(); return { ...previewBoundary, status: "AGENT_ECONOMY_INTEGRATION_RADAR_P0_PREVIEW_READY", manualFirst: true, persistence: "IN_MEMORY_ONLY", sourceCount: agentEconomySources.length, candidateCount: candidates.length, taskQueueReadyCount: candidates.filter((c) => c.finalGxeonFitScore >= 65 && c.securityRiskScore < 50 && c.decision !== "BLOCKED").length, boundaries:["No install route","No execute route","No clone route","No credential route","No external API calls","No production database writes","No workers or schedulers"] }; }
router.get("/agent-economy/status", (_req, res) => res.json({ success: true, data: status() }));
router.get("/agent-economy/sources", (_req, res) => res.json({ success: true, data: { ...previewBoundary, sources: agentEconomySources } }));
router.get("/agent-economy/candidates", (_req, res) => { const candidates = listIntegrationCandidatePreviews(); res.json({ success: true, data: { ...previewBoundary, candidates, count: candidates.length } }); });
router.get("/agent-economy/candidates/:id", (req, res) => { const candidate = getIntegrationCandidatePreviewById(req.params.id); if (!candidate) return safeError(res, new Error("INTEGRATION_CANDIDATE_NOT_FOUND"), "INTEGRATION_CANDIDATE_NOT_FOUND", 404); return res.json({ success: true, data: { ...previewBoundary, candidate } }); });
router.post("/agent-economy/manual-import", (req, res) => { try { const candidate = createIntegrationCandidatePreview(req.body ?? {}); res.status(201).json({ success: true, data: { ...previewBoundary, candidate } }); } catch (error) { safeError(res, error, "AGENT_ECONOMY_MANUAL_IMPORT_FAILED"); } });
router.post("/agent-economy/candidates/:id/create-connector-preview", (req, res) => { try { const candidate = attachConnectorPreview(req.params.id); if (!candidate) return safeError(res, new Error("INTEGRATION_CANDIDATE_NOT_FOUND"), "INTEGRATION_CANDIDATE_NOT_FOUND", 404); res.status(201).json({ success: true, data: { ...previewBoundary, candidate, connectorPreview: candidate.connectorPreview } }); } catch (error) { safeError(res, error, "CONNECTOR_PREVIEW_FAILED"); } });
router.post("/agent-economy/candidates/:id/create-task-preview", (req, res) => { try { const candidate = getIntegrationCandidatePreviewById(req.params.id); if (!candidate) return safeError(res, new Error("INTEGRATION_CANDIDATE_NOT_FOUND"), "INTEGRATION_CANDIDATE_NOT_FOUND", 404); if (candidate.securityRiskScore >= 70 || candidate.decision === "BLOCKED") return safeError(res, new Error("SECURITY_REVIEW_REQUIRED_BEFORE_TASK_PREVIEW"), "SECURITY_REVIEW_REQUIRED_BEFORE_TASK_PREVIEW", 409); const taskPreview = { title: `Preview GXEON integration candidate: ${candidate.title}`, mode: "PREVIEW_ONLY" as const, internalOnly: true as const, taskQueueMutationDisabled: true as const, brokerPreparation:["Map candidate to read-only connector lane","Declare forbidden install/execute/secret actions","Require operator approval before any execution center stage"], validationPlan:["Validate license and owner manually","Validate no secrets are requested","Validate no external write or paid API path exists"], releaseGateNotes:["Release remains blocked until manual security approval"], ledgerPreviewNotes:["Ledger may record future approved service opportunity only; no revenue guaranteed"], nextManualAction:"Operator can copy this preview into Task Queue Linking P0; this endpoint does not mutate Task Queue." }; const updated = updateIntegrationCandidateState(candidate.id, "TASK_QUEUE_PREVIEW_READY", { taskPreview }); res.status(201).json({ success: true, data: { ...previewBoundary, candidate: updated, taskPreview } }); } catch (error) { safeError(res, error, "TASK_PREVIEW_FAILED"); } });
export default router;
