import { Router, type IRouter, type Response } from "express"; import { searchGitHubDemandPreview, getGitHubDemandStatus, GitHubDemandClientError } from "../radar/githubDemandClient"; import { githubDemandQueryPacks } from "../radar/githubDemandQueryPacks"; import { scoreGitHubDemandCandidate } from "../radar/githubDemandScoring"; import { createGitHubDemandPipelinePreview, getGitHubDemandPipelinePreviewById, listGitHubDemandPipelinePreviews, updateGitHubDemandPipelineStatus } from "../radar/githubDemandPipelineStore"; import { generateGitHubDemandProposalPack } from "../radar/githubDemandProposalPack"; import { createOpportunityFromGitHubDemandCandidate } from "../radar/githubDemandOpportunityBridge"; import { createConversionPack, getConversionPackById, listConversionPacks, recordConversionPackAction, updateConversionPackStatus } from "../radar/githubDemandConversionStore"; import { createBrainSprintPreviewFromConversionPack, createOpportunityPreviewFromConversionPack, createTaskPreviewFromConversionPack } from "../radar/githubDemandConversionBridge"; import { createExecutionPack, getExecutionPackById, listExecutionPacks, recordExecutionPackAction, updateExecutionPackStatus } from "../radar/githubDemandExecutionStore"; import { createBrokerRoutePreviewFromExecutionPack, createExecutionCenterPreviewFromExecutionPack, createDeliveryWorkspacePreviewFromExecutionPack, createLedgerPreviewFromExecutionPack, createReleasePreviewFromExecutionPack, createTaskPreviewFromExecutionPack, createValidationPreviewFromExecutionPack } from "../radar/githubDemandExecutionBridge"; import type { ExecutionPackStatus } from "../radar/githubDemandExecutionTypes";
const router:IRouter=Router(); const err=(res:Response,e:unknown,code=400)=>res.status(code).json({success:false,data:{mode:"PREVIEW_ONLY",manualReviewRequired:true,externalContactDisabled:true,githubWriteDisabled:true,rewardNotGuaranteed:true},error:e instanceof Error?e.message:"GITHUB_DEMAND_REQUEST_FAILED",message:e instanceof Error?e.message:"GITHUB_DEMAND_REQUEST_FAILED"});
router.use("/github-demand",(_req,res,next)=>{res.setHeader("Cache-Control","no-store");next();});
router.get("/github-demand/status",(_req,res)=>res.json({success:true,data:getGitHubDemandStatus()}));
router.get("/github-demand/query-packs",(_req,res)=>res.json({success:true,data:{mode:"PREVIEW_ONLY",queryPacks:githubDemandQueryPacks,count:githubDemandQueryPacks.length,githubWriteDisabled:true,externalContactDisabled:true}}));
router.post("/github-demand/search-preview",async(req,res)=>{try{res.json({success:true,data:await searchGitHubDemandPreview(req.body??{})})}catch(e){if(e instanceof GitHubDemandClientError) return err(res,e,e.statusCode); return err(res,e,502)}});
router.post("/github-demand/score-preview",(req,res)=>{try{res.json({success:true,data:scoreGitHubDemandCandidate(req.body?.candidate??req.body??{})})}catch(e){err(res,e)}});
router.post("/github-demand/pipeline-preview",(req,res)=>{try{res.status(201).json({success:true,data:{pipelinePreview:createGitHubDemandPipelinePreview(req.body?.candidate),mode:"PREVIEW_ONLY"}})}catch(e){err(res,e)}});
router.get("/github-demand/pipeline-previews",(_req,res)=>res.json({success:true,data:{mode:"PREVIEW_ONLY",pipelinePreviews:listGitHubDemandPipelinePreviews(),count:listGitHubDemandPipelinePreviews().length}}));
router.get("/github-demand/pipeline-previews/:id",(req,res)=>{const p=getGitHubDemandPipelinePreviewById(req.params.id); if(!p)return err(res,new Error("GITHUB_DEMAND_PIPELINE_PREVIEW_NOT_FOUND"),404); return res.json({success:true,data:{pipelinePreview:p}})});
router.post("/github-demand/pipeline-previews/:id/proposal-pack",(req,res)=>{const p=getGitHubDemandPipelinePreviewById(req.params.id); if(!p)return err(res,new Error("GITHUB_DEMAND_PIPELINE_PREVIEW_NOT_FOUND"),404); return res.json({success:true,data:{mode:"PREVIEW_ONLY",proposalPack:generateGitHubDemandProposalPack(p.candidate)}})});

router.post("/github-demand/pipeline-previews/:id/conversion-pack",(req,res)=>{try{const p=getGitHubDemandPipelinePreviewById(req.params.id); if(!p)return err(res,new Error("GITHUB_DEMAND_PIPELINE_PREVIEW_NOT_FOUND"),404); return res.status(201).json({success:true,data:{mode:"PREVIEW_ONLY",conversionPack:createConversionPack(p),manualReviewRequired:true,githubWriteDisabled:true,externalContactDisabled:true,rewardNotGuaranteed:true}})}catch(e){err(res,e)}});
router.get("/github-demand/conversion-packs",(_req,res)=>res.json({success:true,data:{mode:"PREVIEW_ONLY",conversionPacks:listConversionPacks(),count:listConversionPacks().length,manualReviewRequired:true,githubWriteDisabled:true,externalContactDisabled:true,rewardNotGuaranteed:true}}));
router.get("/github-demand/conversion-packs/:id",(req,res)=>{const pack=getConversionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_CONVERSION_PACK_NOT_FOUND"),404); return res.json({success:true,data:{mode:"PREVIEW_ONLY",conversionPack:pack,safetyFlags:pack}})});

router.post("/github-demand/conversion-packs/:id/execution-pack",(req,res)=>{try{const pack=getConversionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_CONVERSION_PACK_NOT_FOUND"),404); const executionPack=createExecutionPack(pack); return res.status(201).json({success:true,data:{mode:"PREVIEW_ONLY",executionPack,actionResult:{actionType:"EXECUTION_PACK_CREATED",status:executionPack.status,packId:executionPack.id,safetyFlags:executionPack,nextManualAction:executionPack.nextManualAction}}})}catch(e){err(res,e)}});
router.get("/github-demand/execution-packs",(_req,res)=>res.json({success:true,data:{mode:"PREVIEW_ONLY",executionPacks:listExecutionPacks(),count:listExecutionPacks().length,manualReviewRequired:true,githubWriteDisabled:true,externalContactDisabled:true,paymentProviderDisabled:true,rewardNotGuaranteed:true}}));
router.get("/github-demand/execution-packs/:id",(req,res)=>{const pack=getExecutionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_EXECUTION_PACK_NOT_FOUND"),404); return res.json({success:true,data:{mode:"PREVIEW_ONLY",executionPack:pack,safetyFlags:pack}})});
const executionAction=(kind:string, status:ExecutionPackStatus, fn:(pack:any)=>any)=>(req:any,res:any)=>{try{const pack=getExecutionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_EXECUTION_PACK_NOT_FOUND"),404); const actionResult=fn(pack); updateExecutionPackStatus(pack.id,status); recordExecutionPackAction(pack.id,{actionType:kind as any,status,previewId:`${pack.id}_${kind.toLowerCase()}`}); return res.json({success:true,data:{actionResult:{...actionResult,status}}})}catch(e){err(res,e)}};
router.post("/github-demand/execution-packs/:id/task-preview",executionAction("TASK_PREVIEW","TASK_PREVIEW_CREATED",createTaskPreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/broker-preview",executionAction("BROKER_ROUTE_PREVIEW","BROKER_ROUTE_PREPARED",createBrokerRoutePreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/execution-center-preview",executionAction("EXECUTION_CENTER_PREVIEW","EXECUTION_PREVIEW_CREATED",createExecutionCenterPreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/validation-preview",executionAction("VALIDATION_PREVIEW","VALIDATION_PREVIEW_CREATED",createValidationPreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/release-preview",executionAction("RELEASE_PREVIEW","RELEASE_PREVIEW_CREATED",createReleasePreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/ledger-preview",executionAction("LEDGER_PREVIEW","LEDGER_PREVIEW_CREATED",createLedgerPreviewFromExecutionPack));
router.post("/github-demand/execution-packs/:id/delivery-workspace-preview",(req,res)=>{try{const pack=getExecutionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_EXECUTION_PACK_NOT_FOUND"),404); const workspace=createDeliveryWorkspacePreviewFromExecutionPack(pack); return res.status(201).json({success:true,data:{mode:"PREVIEW_ONLY",workspace,workspaceRoute:"/ops/delivery-workspace",actionResult:{actionType:"DELIVERY_WORKSPACE_PREVIEW",status:workspace.status,packId:pack.id,workspaceId:workspace.id,mode:"PREVIEW_ONLY",safetyFlags:workspace,nextManualAction:workspace.nextManualAction,preview:{workspaceRoute:"/ops/delivery-workspace",copyOnly:true}}}})}catch(e){err(res,e)}});

router.post("/github-demand/conversion-packs/:id/create-opportunity-preview",(req,res)=>{try{const pack=getConversionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_CONVERSION_PACK_NOT_FOUND"),404); const operatorConfirmed=req.body?.operatorConfirmed===true; const actionResult=createOpportunityPreviewFromConversionPack(pack,operatorConfirmed); if(operatorConfirmed) updateConversionPackStatus(pack.id,"OPPORTUNITY_PREVIEW_CREATED"); recordConversionPackAction(pack.id,{actionType:"OPPORTUNITY_PREVIEW",status:actionResult.status,previewIds:actionResult.opportunity?.id?{opportunityId:actionResult.opportunity.id}:undefined}); return res.status(operatorConfirmed?201:200).json({success:true,data:{actionResult}})}catch(e){err(res,e)}});
router.post("/github-demand/conversion-packs/:id/create-task-preview",(req,res)=>{try{const pack=getConversionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_CONVERSION_PACK_NOT_FOUND"),404); const actionResult=createTaskPreviewFromConversionPack(pack); updateConversionPackStatus(pack.id,"TASK_PREVIEW_CREATED"); recordConversionPackAction(pack.id,{actionType:"TASK_PREVIEW",status:actionResult.status,previewIds:{taskPreviewId:actionResult.taskPreview.id}}); return res.json({success:true,data:{actionResult}})}catch(e){err(res,e)}});
router.post("/github-demand/conversion-packs/:id/brain-revenue-sprint-preview",(req,res)=>{try{const pack=getConversionPackById(req.params.id); if(!pack)return err(res,new Error("GITHUB_DEMAND_CONVERSION_PACK_NOT_FOUND"),404); const actionResult=createBrainSprintPreviewFromConversionPack(pack); updateConversionPackStatus(pack.id,"BRAIN_SPRINT_PREVIEW_CREATED"); recordConversionPackAction(pack.id,{actionType:"BRAIN_SPRINT_PREVIEW",status:actionResult.status,previewIds:{conversionPackId:pack.id}}); return res.json({success:true,data:{actionResult}})}catch(e){err(res,e)}});
router.post("/github-demand/pipeline-previews/:id/create-opportunity-preview",(req,res)=>{try{const p=getGitHubDemandPipelinePreviewById(req.params.id); if(!p)return err(res,new Error("GITHUB_DEMAND_PIPELINE_PREVIEW_NOT_FOUND"),404); const bridge=createOpportunityFromGitHubDemandCandidate(p.candidate,req.body?.operatorConfirmed===true); const updated=updateGitHubDemandPipelineStatus(p.id,"OPPORTUNITY_PREVIEW_CREATED",{opportunityPreviewId:bridge.opportunity.id,taskPreviewRoute:bridge.taskPreviewRoute,taskCreationRoute:bridge.taskCreationRoute}); return res.status(201).json({success:true,data:{...bridge,pipelinePreview:updated,mode:"PREVIEW_ONLY"}})}catch(e){err(res,e)}});
export default router;
