import { Router, type IRouter } from "express";
import healthRouter from "./health";
import governanceRouter from "./governance";
import conversionRouter from "./conversion";
import phase8Router from "./phase8";
import runtimeRouter from "./runtime";
import financialRouter from "./financial";
import connectorsRouter from "./connectors";
import githubConnectorRouter from "./connectors/github";
import vercelConnectorRouter from "./connectors/vercel";
import railwayConnectorRouter from "./connectors/railway";
import supabaseConnectorRouter from "./connectors/supabase";
import microsoft365ConnectorRouter from "./connectors/microsoft365";
import monetizationRouter from "./monetization";
import radarRouter from "./radar";
import opportunitiesRouter from "./opportunities";
import agentsRouter from "./agents";
import brokerRouter from "./broker";
import executionRouter from "./execution";
import validationRouter from "./validation";
import releaseRouter from "./release";
import ledgerRouter from "./ledger";
import tasksRouter from "./tasks";
import web3TasksRouter from "./web3Tasks";
import agentEconomyRouter from "./agentEconomy";
import brainRouter from "./brain";
import githubDemandRouter from "./githubDemand";
import operatorDeliveryWorkspaceRouter from "./operatorDeliveryWorkspace";
import manualPaymentRouter from "./manualPayment";
import clientOfferSendRouter from "./clientOfferSend";
import manualProspectsRouter from "./manualProspects";
import r100WarRoomRouter from "./r100WarRoom";

const router: IRouter = Router();

router.use(healthRouter);
router.use(governanceRouter);
router.use(conversionRouter);
router.use(phase8Router);
router.use(runtimeRouter);
router.use(financialRouter);
router.use(connectorsRouter);
router.use(githubConnectorRouter);
router.use(vercelConnectorRouter);
router.use(railwayConnectorRouter);
router.use(supabaseConnectorRouter);
router.use(microsoft365ConnectorRouter);
router.use(monetizationRouter);
router.use(radarRouter);
router.use(githubDemandRouter);
router.use(operatorDeliveryWorkspaceRouter);
router.use(manualPaymentRouter);
router.use(clientOfferSendRouter);
router.use(manualProspectsRouter);
router.use(r100WarRoomRouter);
router.use(opportunitiesRouter);
router.use(tasksRouter);
router.use(web3TasksRouter);
router.use(agentEconomyRouter);
router.use(brainRouter);
router.use(agentsRouter);
router.use(brokerRouter);
router.use(executionRouter);
router.use(validationRouter);
router.use(releaseRouter);
router.use(ledgerRouter);

export default router;
