import { Router } from "express";
import { calculateOperatorAssistantNextAction } from "../operatorAssistant/operatorAssistantNextActionEngine";
import { buildOperatorAssistantPreview } from "../operatorAssistant/operatorAssistantPreviewBuilder";
import { readOperatorAssistantState } from "../operatorAssistant/operatorAssistantStateReader";
import { createInternalHandoff, listActionPreviews, listInternalHandoffs, saveActionPreview } from "../operatorAssistant/operatorAssistantStore";
import { operatorAssistantSafety } from "../operatorAssistant/operatorAssistantTypes";
const router=Router(); const ok=(data:any)=>({success:true,data:{...operatorAssistantSafety,...data}}); const safe=(res:any,e:any)=>res.status(200).json(ok({error:e instanceof Error?e.message:"OPERATOR_ASSISTANT_SAFE_ERROR",safeError:true}));
router.get("/operator-assistant/status",(_req,res)=>res.json(ok({status:"OPERATOR_EXECUTION_ASSISTANT_P1_READY",capabilities:["read_internal_preview_state","recommend_next_best_action","generate_internal_action_preview","generate_copy_only_message","create_internal_handoff_preview"],forbidden:["send_email","send_whatsapp","create_checkout","capture_payment","verify_payment_provider","write_to_github","connect_wallet"]})));
router.get("/operator-assistant/state",(req,res)=>{try{res.json(ok({state:readOperatorAssistantState(String(req.query.currentRoute||"/ops/operator-assistant"))}))}catch(e){safe(res,e)}});
router.get("/operator-assistant/next-action",(req,res)=>{try{res.json(ok({state:readOperatorAssistantState(String(req.query.currentRoute||"/ops/operator-assistant")),nextAction:calculateOperatorAssistantNextAction(readOperatorAssistantState(String(req.query.currentRoute||"/ops/operator-assistant")))}))}catch(e){safe(res,e)}});
router.post("/operator-assistant/action-preview",(req,res)=>{try{const preview=saveActionPreview(buildOperatorAssistantPreview(req.body??{}));res.status(201).json(ok({preview,history:listActionPreviews()}))}catch(e){safe(res,e)}});
router.post("/operator-assistant/internal-handoff",(req,res)=>{try{const handoff=createInternalHandoff(req.body??{});res.status(201).json(ok({handoff,history:listInternalHandoffs()}))}catch(e){safe(res,e)}});
export default router;
