import { Router } from "express";
import { buildCloseLoopDetail, buildCloseLoopSummary } from "../revenueCloseLoop/revenueCloseLoopBuilder";
import { confirmRevenueManually, createOrReuseCloseLoop, ledgerPreview, nextBestManualAction, previewProofChecklist, updateCloseLoopStatus } from "../revenueCloseLoop/revenueCloseLoopActions";
import { getRevenueCloseLoopById, listRevenueCloseLoops } from "../revenueCloseLoop/revenueCloseLoopStore";
import { revenueCloseLoopSafetyFlags, type RevenueCloseLoopStatus } from "../revenueCloseLoop/revenueCloseLoopTypes";
const router=Router(); const ok=(data:any)=>({success:true,data:{...data,safetyFlags:data?.safetyFlags??revenueCloseLoopSafetyFlags}}); const safe=(res:any,e:any,code=400)=>res.status(code).json({success:false,error:e?.message??String(e),data:{safetyFlags:revenueCloseLoopSafetyFlags}});
router.get('/revenue-close-loop/status',(_req,res)=>res.json(ok({status:'REVENUE_CLOSE_LOOP_P0_READY',mode:'MANUAL_FIRST',persistence:'IN_MEMORY_P0',operatorConfirmedRevenueAllowed:true,providerVerifiedRevenueDisabled:true,paymentProviderDisabled:true,checkoutDisabled:true,autoSendDisabled:true,externalContactAutomationDisabled:true,githubWriteDisabled:true})));
router.get('/revenue-close-loop/summary',(_req,res)=>res.json(ok(buildCloseLoopSummary())));
router.get('/revenue-close-loop/loops',(_req,res)=>res.json(ok({loops:listRevenueCloseLoops().map(buildCloseLoopDetail)})));
router.get('/revenue-close-loop/loops/:id',(req,res)=>{const l=getRevenueCloseLoopById(req.params.id); if(!l)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok(buildCloseLoopDetail(l)));});
router.post('/revenue-close-loop/from-prospect/:prospectId',(req,res)=>res.status(201).json(ok({loop:buildCloseLoopDetail(createOrReuseCloseLoop({prospectId:req.params.prospectId},req.body))})));
router.post('/revenue-close-loop/from-offer/:offerId',(req,res)=>res.status(201).json(ok({loop:buildCloseLoopDetail(createOrReuseCloseLoop({offerId:req.params.offerId},req.body))})));
router.post('/revenue-close-loop/from-payment/:paymentRequestId',(req,res)=>res.status(201).json(ok({loop:buildCloseLoopDetail(createOrReuseCloseLoop({paymentRequestId:req.params.paymentRequestId},req.body))})));
router.patch('/revenue-close-loop/loops/:id/status',(req,res)=>{try{const l=updateCloseLoopStatus(req.params.id,req.body?.status as RevenueCloseLoopStatus,req.body?.operatorNote); if(!l)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok({loop:buildCloseLoopDetail(l)}));}catch(e){safe(res,e)}});
router.post('/revenue-close-loop/loops/:id/proof-checklist-preview',(req,res)=>{const l=previewProofChecklist(req.params.id,req.body); if(!l)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok({loop:buildCloseLoopDetail(l),proofChecklist:l.proofChecklist}));});
router.post('/revenue-close-loop/loops/:id/confirm-revenue-manually',(req,res)=>{try{const r=confirmRevenueManually(req.params.id,req.body); if(!r)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok(r));}catch(e){safe(res,e)}});
router.post('/revenue-close-loop/loops/:id/ledger-preview',(req,res)=>{const l=getRevenueCloseLoopById(req.params.id); if(!l)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok({ledgerPreview:ledgerPreview(l)}));});
router.post('/revenue-close-loop/loops/:id/next-action-preview',(req,res)=>{const l=getRevenueCloseLoopById(req.params.id); if(!l)return safe(res,new Error('REVENUE_CLOSE_LOOP_NOT_FOUND'),404); res.json(ok({nextBestManualAction:nextBestManualAction(l)}));});
export default router;
