import type { AgentEconomySource } from "./agentEconomyTypes";
const commonRisk = ["Manual review only", "No install, clone, execution, credentials, scraping or paid API calls in P0"];
export const agentEconomySources: AgentEconomySource[] = [
 { id:"anthropic_mcp", label:"Anthropic MCP / Model Context Protocol", type:"MCP_ECOSYSTEM", bestFor:["tool servers","context connectors","Claude-compatible agent infrastructure","MCP gateway patterns"], manualOnly:true, riskNotes:[...commonRisk,"Tool poisoning and prompt injection surfaces require review"], monetizationAngles:["GXEON MCP Gateway Pack","GXEON Connector Pack","Security Review for MCP repositories"]},
 { id:"openrouter", label:"OpenRouter Ecosystem", type:"MODEL_ROUTING", bestFor:["multi-model routing","model comparison","provider abstraction","future GXEON model router"], manualOnly:true, riskNotes:[...commonRisk,"Provider keys and external API costs stay disabled"], monetizationAngles:["GXEON Model Router Blueprint","AI Ops Stack Setup"]},
 { id:"huggingface", label:"Hugging Face", type:"MODEL_AND_DATASET_HUB", bestFor:["open models","embeddings","datasets","spaces","inference prototypes"], manualOnly:true, riskNotes:[...commonRisk,"License, dataset provenance and inference cost must be checked"], monetizationAngles:["Model audit","Embedding/RAG blueprint","Enterprise agent setup"]},
 { id:"github_open_source_agents", label:"GitHub Open Source Agents", type:"REPOSITORY_ECOSYSTEM", bestFor:["agent frameworks","MCP servers","automation libraries","connectors","workflow engines"], manualOnly:true, riskNotes:[...commonRisk,"No runtime GitHub writes or arbitrary repository execution"], monetizationAngles:["Open Source Agent Audit","Connector Pack","Security Review"]},
 { id:"langchain_langgraph", label:"LangChain / LangGraph", type:"AGENT_FRAMEWORK", bestFor:["agent workflows","graphs","tool orchestration","enterprise workflows"], manualOnly:true, riskNotes:commonRisk, monetizationAngles:["Enterprise Agent Integration Service","AI Ops Stack Setup"]},
 { id:"llamaindex", label:"LlamaIndex", type:"RAG_AND_AGENT_FRAMEWORK", bestFor:["RAG","document agents","knowledge connectors","enterprise data access"], manualOnly:true, riskNotes:commonRisk, monetizationAngles:["RAG connector blueprint","Knowledge access audit"]},
 { id:"crewai", label:"CrewAI", type:"MULTI_AGENT_FRAMEWORK", bestFor:["role-based agents","team execution","agent collaboration"], manualOnly:true, riskNotes:commonRisk, monetizationAngles:["Agent team setup","Enterprise workflow design"]},
 { id:"autogen", label:"AutoGen", type:"MULTI_AGENT_FRAMEWORK", bestFor:["multi-agent conversations","agent coordination","research workflows"], manualOnly:true, riskNotes:commonRisk, monetizationAngles:["Research workflow integration","Agent audit"]},
 { id:"ollama", label:"Ollama / Local Models", type:"LOCAL_MODEL_RUNTIME", bestFor:["local inference","private model testing","offline agent execution"], manualOnly:true, riskNotes:[...commonRisk,"Local runtime remains unexecuted in P0"], monetizationAngles:["Private model router","Offline AI Ops stack"]},
 { id:"manual_import", label:"Manual Repository / Tool Import", type:"OPERATOR_INPUT", bestFor:["operator-pasted repositories","private research","manual candidate tracking"], manualOnly:true, riskNotes:commonRisk, monetizationAngles:["Manual audit","Custom integration service"]},
];
export const getAgentEconomySourceById = (id?: string) => agentEconomySources.find((s) => s.id === id) ?? agentEconomySources[agentEconomySources.length - 1];
