import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const List=({title,items}:{title:string;items:string[]})=><div><p className="font-bold text-white">{title}</p><ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-slate-300">{items?.map((i,idx)=><li key={idx}>{i}</li>)}</ul></div>;
export function GitHubDemandExecutionPackCard({pack,onAction,loading}:{pack:any;onAction:(id:string,kind:string)=>void;loading?:string|null}){
 const copy=()=>navigator.clipboard?.writeText([pack.operatorSummary,...(pack.technicalChecklist??[]),...(pack.deliveryArtifacts??[])].join("\n"));
 return <Card className="border-emerald-300/20 bg-slate-950/80"><CardHeader><CardTitle className="text-white">{pack.offerTitle}</CardTitle><div className="flex flex-wrap gap-2">{["PREVIEW_ONLY","NO_GITHUB_WRITE","NO_AUTO_CONTACT","NO_PAYMENT","REWARD_NOT_GUARANTEED"].map(b=><Badge key={b} className="bg-emerald-300/10 text-emerald-100">{b}</Badge>)}</div></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 text-sm text-slate-300 md:grid-cols-4"><p>Route <b className="text-white">{pack.route}</b></p><p>Status <b className="text-white">{pack.status}</b></p><p>Value <b className="text-white">{pack.suggestedValue}</b></p><p>Timebox <b className="text-white">{pack.suggestedTimebox}</b></p></div><p className="text-sm text-slate-300">{pack.operatorSummary}</p><div className="grid gap-4 md:grid-cols-2"><List title="Technical checklist" items={pack.technicalChecklist}/><List title="Evidence checklist" items={pack.evidenceChecklist}/><List title="Delivery artifacts" items={pack.deliveryArtifacts}/><List title="Validation checklist" items={pack.validationChecklist}/><List title="Risk warnings" items={pack.riskWarnings}/><List title="Scope included" items={pack.scopeIncluded}/><List title="Scope excluded" items={pack.scopeExcluded}/><div className="rounded-2xl border border-white/10 p-3 text-sm text-slate-300"><p className="font-bold text-white">Ledger preview</p><p>R${pack.ledgerPreview?.expectedValueBrl} / US${pack.ledgerPreview?.expectedValueUsd}</p><p>{pack.ledgerPreview?.status} · not guaranteed</p></div></div><div className="flex flex-wrap gap-2"><Button onClick={copy} variant="outline" className="border-white/20 text-white">Copy checklist/delivery text</Button>{[["task","Create Task Preview"],["broker","Prepare Broker Route"],["execution","Create Execution Preview"],["validation","Create Validation Preview"],["release","Create Release Preview"],["ledger","Create Ledger Preview"],["workspace","Create Delivery Workspace Preview"]].map(([k,l])=><Button key={k} disabled={loading===k} onClick={()=>onAction(pack.id,k)} className="bg-emerald-300 text-slate-950">{loading===k?"Creating...":l}</Button>)}<a href="/ops/delivery-workspace" className="text-sm font-bold text-cyan-200">Open Delivery Workspace</a></div></CardContent></Card>
}
