import { clientOfferSafetyFlags, type ClientOfferActionResult, type ClientOfferSendInput, type ClientOfferSendPack } from "./clientOfferSendTypes";
const money=(n:number)=>`R$ ${n.toFixed(2).replace(".",",")}`;
export function buildClientOfferSendPack(input:ClientOfferSendInput):ClientOfferSendPack{
 const now=new Date().toISOString(); const amount=Number(input.amountBrl ?? 100); const title=input.title?.trim() || "GXEON R$100 Manual Sprint Offer"; const id=`cos_${Date.now()}_${Math.random().toString(36).slice(2,8)}`; const channel=input.channel ?? "WHATSAPP_MANUAL"; const contact=input.contactLabel?.trim();
 const instruction=input.paymentInstructionSnippet?.trim() || "Payment instruction is copy-only: operator must paste Pix/link/details manually outside GXEON after checking the destination. No payment provider API is called.";
 const basePt=`Olá${contact?` ${contact}`:""}! Posso entregar ${title} por ${money(amount)} com escopo objetivo e checklist de entrega.`;
 const baseEn=`Hello${contact?` ${contact}`:""}! I can deliver ${title} for BRL ${amount.toFixed(2)} with a focused scope and delivery checklist.`;
 const safetyPt="Mensagem para copiar manualmente; GXEON não envia, não cobra e não confirma pagamento automaticamente.";
 const safetyEn="Copy-only manual message; GXEON does not send, charge, or confirm payment automatically.";
 return {...clientOfferSafetyFlags,id,sourceType:input.sourceType??"MANUAL_OFFER",sourceId:input.sourceId,status:"READY_TO_COPY",title,amountBrl:amount,channel,contactLabel:contact,notes:input.notes,ptBrShortMessage:`${basePt} ${safetyPt}`,ptBrFullMessage:`${basePt}\n\nInclui: diagnóstico rápido, entrega manual validável, resumo do que foi feito e próximos passos.\n\n${instruction}\n\n${safetyPt}`,enUsShortMessage:`${baseEn} ${safetyEn}`,enUsFullMessage:`${baseEn}\n\nIncludes: quick diagnosis, manually verifiable delivery, summary of work completed, and next steps.\n\n${instruction}\n\n${safetyEn}`,paymentInstructionSnippet:instruction,manualSendChecklist:["Review recipient/contact label supplied by operator","Copy one message variant only","Paste and send manually outside GXEON","Do not use any GXEON auto-send or provider integration","Record manual send status only after external action"],proofOfSendChecklist:["Screenshot or external evidence captured by operator","Channel and timestamp noted manually","No customer data harvested by GXEON","No automated contact occurred"],followUpChecklist:["If no answer, copy a follow-up manually","Mark waiting response manually","Mark accepted/declined only from external response","Keep payment as preview-only until proof is checked outside GXEON"],deliveryPromiseChecklist:["Confirm scope before delivery","Keep promise aligned to amount","Prepare delivery workspace/evidence manually","Do not promise guaranteed revenue or payment confirmation"],riskWarnings:["PREVIEW_ONLY pack; not a send action","COPY_ONLY text; clipboard/manual use only","Payment provider disabled; no checkout or invoice","Real revenue is not claimed in GXEON P0"],ledgerPreview:{type:"CLIENT_OFFER_LEDGER_PREVIEW",expectedAmountBrl:amount,realRevenueBrl:0,providerVerified:false,paymentProviderDisabled:true,realRevenueClaimed:false,rewardNotGuaranteed:true,sourceType:input.sourceType??"MANUAL_OFFER",sourceId:input.sourceId},nextManualAction:"Copy a message variant, send manually outside GXEON, then update follow-up status manually.",createdAt:now,updatedAt:now,actionHistory:[]};
}
export const actionResult=(pack:ClientOfferSendPack, preview:Record<string,unknown>={}):ClientOfferActionResult=>({mode:"PREVIEW_ONLY",packId:pack.id,status:pack.status,safetyFlags:clientOfferSafetyFlags,nextManualAction:pack.nextManualAction,autoSendDisabled:true,externalContactDisabled:true,paymentProviderDisabled:true,realRevenueClaimed:false,rewardNotGuaranteed:true,preview:{pack,...preview}});
