// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IFlashLoanSimpleReceiver$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFlashLoanSimpleReceiver";
  readonly sourceName: "contracts/interfaces/IPool.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"uint256","name":"premium","type":"uint256"},{"internalType":"address","name":"initiator","type":"address"},{"internalType":"bytes","name":"params","type":"bytes"}],"name":"executeOperation","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPool.sol";
  readonly buildInfoId: "solc-0_8_20-2ea50d980e193d3bbf29660fb6aa9a04bb1e5ff5";
};

export interface IPool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPool";
  readonly sourceName: "contracts/interfaces/IPool.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"receiverAddress","type":"address"},{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"bytes","name":"params","type":"bytes"},{"internalType":"uint16","name":"referralCode","type":"uint16"}],"name":"flashLoanSimple","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"onBehalfOf","type":"address"},{"internalType":"uint16","name":"referralCode","type":"uint16"}],"name":"supply","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"asset","type":"address"},{"internalType":"uint256","name":"amount","type":"uint256"},{"internalType":"address","name":"to","type":"address"}],"name":"withdraw","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPool.sol";
  readonly buildInfoId: "solc-0_8_20-2ea50d980e193d3bbf29660fb6aa9a04bb1e5ff5";
};

export interface IPoolAddressesProvider$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IPoolAddressesProvider";
  readonly sourceName: "contracts/interfaces/IPool.sol";
  readonly abi: [{"inputs":[],"name":"getPool","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getPoolConfigurator","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getPriceOracle","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IPool.sol";
  readonly buildInfoId: "solc-0_8_20-2ea50d980e193d3bbf29660fb6aa9a04bb1e5ff5";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IFlashLoanSimpleReceiver"]: IFlashLoanSimpleReceiver$Type
    ["IPool"]: IPool$Type
    ["IPoolAddressesProvider"]: IPoolAddressesProvider$Type;
    ["contracts/interfaces/IPool.sol:IFlashLoanSimpleReceiver"]: IFlashLoanSimpleReceiver$Type
    ["contracts/interfaces/IPool.sol:IPool"]: IPool$Type
    ["contracts/interfaces/IPool.sol:IPoolAddressesProvider"]: IPoolAddressesProvider$Type;
  }
}