import { getClientOfferSendPackById } from "../clientOffer/clientOfferSendStore";
import { getManualPaymentRequestById } from "../manualPayment/manualPaymentRequestStore";
import { getManualProspectById } from "../prospect/manualProspectStore";
import { findLoopByLink, getOperatorConfirmedRevenueById, getRevenueCloseLoopById, nextLoopId, nextRevenueId, saveOperatorConfirmedRevenue, saveRevenueCloseLoop } from "./revenueCloseLoopStore";
import { manualPaymentMethods, revenueCloseLoopSafetyFlags, revenueCloseLoopStatuses, type CloseLoopLedgerPreview, type ManualPaymentMethod, type OperatorConfirmedRevenue, type ProofChecklist, type RevenueCloseLoop, type RevenueCloseLoopStatus } from "./revenueCloseLoopTypes";
const now=()=>new Date().toISOString(); const ev=(type:string,status?:RevenueCloseLoopStatus,operatorNote?:string,metadata:Record<string,unknown>={})=>({id:`event_${Date.now()}_${Math.random().toString(16).slice(2,8)}`,timestamp:now(),type,status,operatorNote,metadata});
export function createOrReuseCloseLoop(link:{prospectId?:string;offerId?:string;paymentRequestId?:string}, input:any={}){ const key=link.prospectId?["prospectId",link.prospectId]:link.offerId?["offerId",link.offerId]:["paymentRequestId",link.paymentRequestId]; const existing=key[1]?findLoopByLink(key[0] as any,key[1] as string):undefined; if(existing) return existing; const status:RevenueCloseLoopStatus=link.prospectId?"PROSPECT_SELECTED":link.offerId?"OFFER_READY_TO_COPY":"PAYMENT_REQUEST_READY"; return saveRevenueCloseLoop({id:nextLoopId(),status,targetAmountBrl:Number(input.targetAmountBrl)||100,route:input.route??"DIRECT_PIX_OFFER",notes:input.notes,...link,createdAt:now(),updatedAt:now(),timeline:[ev("CLOSE_LOOP_CREATED",status,input.notes,{...link,safetyFlags:revenueCloseLoopSafetyFlags})]}); }
export function getLinkedSnapshot(loop:RevenueCloseLoop){return {prospect:loop.prospectId?getManualProspectById(loop.prospectId):undefined,offer:loop.offerId?getClientOfferSendPackById(loop.offerId):undefined,payment:loop.paymentRequestId?getManualPaymentRequestById(loop.paymentRequestId):undefined};}
export function updateCloseLoopStatus(id:string,status:RevenueCloseLoopStatus,operatorNote?:string){ if(!revenueCloseLoopStatuses.includes(status)) throw new Error("INVALID_MANUAL_STATUS"); const l=getRevenueCloseLoopById(id); if(!l) return undefined; return saveRevenueCloseLoop({...l,status,updatedAt:now(),timeline:[...l.timeline,ev("MANUAL_STATUS_UPDATED",status,operatorNote)]});}
export function buildProofChecklist(proofLabel:string,operatorNote?:string):ProofChecklist{return {proofLabel:proofLabel||"Comprovante conferido manualmente",operatorNote,noSensitiveProofStored:true,providerVerified:false,paymentGuaranteed:false,previewOnly:true,checklist:["Operador conferiu comprovante fora do GXEON","Nenhum Pix key, CPF, cartão, token ou imagem completa foi armazenado","providerVerified=false; sem API, checkout ou webhook","Receita real só após confirmação explícita do operador"]};}
export function previewProofChecklist(id:string,input:any){const l=getRevenueCloseLoopById(id); if(!l) return undefined; const proof=buildProofChecklist(input?.proofLabel,input?.operatorNote); return saveRevenueCloseLoop({...l,proofChecklist:proof,updatedAt:now(),timeline:[...l.timeline,ev("PROOF_CHECKLIST_PREVIEWED",l.status,input?.operatorNote)]});}
export function nextBestManualAction(loop:RevenueCloseLoop){ const map:any={PROSPECT_SELECTED:["Preparar oferta","Crie/copiar pacote de oferta manual.","/ops/client-offers"],OFFER_READY_TO_COPY:["Copiar oferta manualmente","Envie fora do GXEON; sem auto-send.","/ops/client-offers"],OFFER_SENT_MANUALLY:["Marcar aguardando resposta","Registrar WAITING_RESPONSE_MANUAL.","/ops/revenue-close-loop"],WAITING_RESPONSE_MANUAL:["Follow-up manual","Acompanhar externamente sem automação.","/ops/revenue-close-loop"],ACCEPTED_MANUALLY:["Criar pedido de pagamento manual","Preparar instrução Pix/link manual.","/ops/manual-payment"],PAYMENT_REQUEST_READY:["Copiar instrução de pagamento","Enviar manualmente fora do GXEON.","/ops/manual-payment"],PAYMENT_REQUEST_SENT_MANUALLY:["Aguardar pagamento manual","Não verificar provider automaticamente.","/ops/revenue-close-loop"],PAYMENT_PROOF_RECEIVED_MANUALLY:["Confirmar receita manualmente","Exige checkbox do operador e providerVerified=false.","/ops/revenue-close-loop"],OPERATOR_CONFIRMED_REVENUE:["Revisar ledger e arquivar","Registro manual, não settlement provider.","/ops/ledger"]}; const [title,description,route]=map[loop.status]??["Selecionar próximo passo manual","Avançar o ciclo sem automação.","/ops/revenue-close-loop"]; return {title,description,route,manualOnly:true,copyOnly:true,safetyFlags:revenueCloseLoopSafetyFlags};}
export function ledgerPreview(loop:RevenueCloseLoop):CloseLoopLedgerPreview{const r=loop.operatorConfirmedRevenueId?getOperatorConfirmedRevenueById(loop.operatorConfirmedRevenueId):undefined; return {id:`ledger_manual_${loop.id}`,source:"REVENUE_CLOSE_LOOP_P0",closeLoopId:loop.id,amountBrl:r?.amountBrl??loop.targetAmountBrl,currency:"BRL",status:r?"OPERATOR_CONFIRMED_MANUAL":"PREVIEW_MANUAL",providerVerified:false,paymentGuaranteed:false,realRevenueClaimedByOperator:Boolean(r),previewRevenueBrl:r?0:loop.targetAmountBrl,operatorConfirmedRevenueBrl:r?.amountBrl??0,notes:r?"External payment confirmed manually by operator. No provider API called.":"Preview only before external operator confirmation.",warning:"Manual operator record only; not provider settlement."};}
export function confirmRevenueManually(id:string,input:any){const l=getRevenueCloseLoopById(id); if(!l) return undefined; if(input?.operatorConfirmation!==true) throw new Error("OPERATOR_CONFIRMATION_REQUIRED"); if(input?.providerVerified===true) throw new Error("PROVIDER_VERIFIED_FORBIDDEN_IN_P0"); const amount=Number(input?.amountBrl); if(!(amount>0)) throw new Error("AMOUNT_BRL_MUST_BE_GREATER_THAN_ZERO"); if(!manualPaymentMethods.includes(input?.paymentMethod)) throw new Error("MANUAL_PAYMENT_METHOD_REQUIRED"); const r:OperatorConfirmedRevenue={id:nextRevenueId(),closeLoopId:id,amountBrl:amount,currency:"BRL",paymentMethod:input.paymentMethod as ManualPaymentMethod,proofLabel:input.proofLabel||"Comprovante verificado fora do GXEON",operatorNote:input.notes,confirmedAt:now(),providerVerified:false,paymentGuaranteed:false,realRevenueClaimedByOperator:true}; saveOperatorConfirmedRevenue(r); const updated=saveRevenueCloseLoop({...l,status:"OPERATOR_CONFIRMED_REVENUE",operatorConfirmedRevenueId:r.id,proofChecklist:buildProofChecklist(r.proofLabel,r.operatorNote),updatedAt:now(),timeline:[...l.timeline,ev("OPERATOR_CONFIRMED_REVENUE","OPERATOR_CONFIRMED_REVENUE",r.operatorNote,{revenueId:r.id,providerVerified:false,paymentGuaranteed:false})]}); return {loop:updated,revenue:r,ledgerPreview:ledgerPreview(updated)};}
