import { listManualProspects } from "../prospect/manualProspectStore";
import { listClientOfferSendPacks } from "../clientOffer/clientOfferSendStore";
import { listManualPaymentRequests } from "../manualPayment/manualPaymentRequestStore";
import { listRevenueCloseLoops, listOperatorConfirmedRevenue } from "../revenueCloseLoop/revenueCloseLoopStore";
import { listLedgerPreviews } from "../ledger/ledgerStore";
import { listExecutionPacks } from "../radar/githubDemandExecutionStore";
import { listOperatorDeliveryWorkspaces } from "../deliveryWorkspace/operatorDeliveryWorkspaceStore";
import { operatorAssistantSafety, type OperatorAssistantState } from "./operatorAssistantTypes";
const safeList=<T>(name:string,fn:()=>T[],fallbacks:Record<string,boolean>)=>{try{return fn()}catch{fallbacks[name]=true;return [] as T[]}};
export function readOperatorAssistantState(currentRoute="/ops/operator-assistant"): OperatorAssistantState { const f:Record<string,boolean>={}; const prospects=safeList("prospects",listManualProspects,f); const offers=safeList("offers",listClientOfferSendPacks,f); const payments=safeList("manualPayments",listManualPaymentRequests,f); const loops=safeList("closeLoops",listRevenueCloseLoops,f); const ledger=safeList("ledgerPreviews",listLedgerPreviews,f); const packs=safeList("executionPacks",listExecutionPacks,f); const workspaces=safeList("deliveryWorkspaces",listOperatorDeliveryWorkspaces,f); const revenue=safeList("confirmedRevenue",listOperatorConfirmedRevenue,f);
return {...operatorAssistantSafety,safeFallbackUsed:Object.values(f).some(Boolean),currentOfficialStep:1,currentRoute,counts:{prospects:prospects.length,offers:offers.length,manualPayments:payments.length,closeLoops:loops.length,ledgerPreviews:ledger.length,executionPacks:packs.length,deliveryWorkspaces:workspaces.length},readiness:{hasHotProspect:prospects.some((p:any)=>!["ARCHIVED","DECLINED_MANUALLY"].includes(p.status)),hasOfferReady:offers.some((o:any)=>["READY_TO_COPY","SENT_MANUALLY","WAITING_RESPONSE_MANUAL"].includes(o.status)),hasPaymentRequestReady:payments.some((p:any)=>["READY_TO_SEND_MANUALLY","WAITING_MANUAL_PAYMENT","PROOF_RECEIVED_MANUAL"].includes(p.status)),hasCloseLoopActive:loops.some((l:any)=>!["ARCHIVED_MANUALLY","DECLINED_MANUALLY"].includes(l.status)),hasProofPending:payments.some((p:any)=>p.status==="PROOF_RECEIVED_MANUAL")||loops.some((l:any)=>l.status==="PAYMENT_PROOF_RECEIVED_MANUALLY"),hasLedgerPreview:ledger.length>0||loops.some((l:any)=>l.operatorConfirmedRevenueId),hasConfirmedRevenue:revenue.length>0},moduleFallbacks:f};}
