import { defaultConnectorSafety, type ConnectorRegistryItem } from "./connectorTypes";
const item = (x: Omit<ConnectorRegistryItem,"mode"|"safety"|"docsNotes"|"monetizationRelevance"|"providerUrl"> & Partial<Pick<ConnectorRegistryItem,"docsNotes"|"monetizationRelevance"|"providerUrl">>): ConnectorRegistryItem => ({ mode:"MANUAL_FIRST", safety: defaultConnectorSafety, docsNotes:x.docsNotes ?? ["P0 manual-first onboarding only; no external mutation is performed."], monetizationRelevance:x.monetizationRelevance ?? "Readiness signal for future monetization and operations routing.", providerUrl:x.providerUrl ?? "https://example.com", ...x });
export const connectorRegistry: ConnectorRegistryItem[] = [
item({id:"github",label:"GitHub",category:"CODE_AND_REPO",connectionModes:["GITHUB_APP","OAUTH","CLI_MANUAL"],capabilities:["read repositories","read pull requests","read issues","read workflow status","prepare internal tasks"],blockedActions:["runtime GitHub writes","automatic PR creation","automatic issue comments","automatic merge"],requiredEnv:["GITHUB_APP_ID_OPTIONAL","GITHUB_CLIENT_ID_OPTIONAL","GITHUB_CLIENT_SECRET_OPTIONAL"],statusGoal:"CONNECTED_READ_ONLY_OR_SETUP_REQUIRED",providerUrl:"https://github.com"}),
item({id:"google",label:"Google",category:"IDENTITY_AND_WORKSPACE",connectionModes:["OAUTH"],capabilities:["identity readiness","calendar/email/docs future readiness"],blockedActions:["send email","modify calendar","download private files without explicit scope"],requiredEnv:["GOOGLE_CLIENT_ID_OPTIONAL","GOOGLE_CLIENT_SECRET_OPTIONAL","GOOGLE_REDIRECT_URI_OPTIONAL"],statusGoal:"OAUTH_READY_OR_SETUP_REQUIRED",providerUrl:"https://console.cloud.google.com/apis/credentials"}),
item({id:"microsoft_365",label:"Microsoft 365",category:"IDENTITY_AND_WORKSPACE",connectionModes:["OAUTH"],capabilities:["Graph readiness","email/calendar future readiness"],blockedActions:["send email","modify files","contact users"],requiredEnv:["MICROSOFT_CLIENT_ID_OPTIONAL","MICROSOFT_CLIENT_SECRET_OPTIONAL","MICROSOFT_TENANT_ID_OPTIONAL"],statusGoal:"OAUTH_READY_OR_SETUP_REQUIRED",providerUrl:"https://portal.azure.com"}),
item({id:"mercado_pago",label:"Mercado Pago",category:"PAYMENT",connectionModes:["OAUTH_SETUP","MANUAL_PAYMENT_LINK"],capabilities:["manual payment instruction","connection readiness","future webhook planning","future payment status read"],blockedActions:["create charge","capture payment","withdraw money","mark provider verified","store access token in frontend"],requiredEnv:["MERCADO_PAGO_CLIENT_ID_OPTIONAL","MERCADO_PAGO_CLIENT_SECRET_OPTIONAL","MERCADO_PAGO_REDIRECT_URI_OPTIONAL"],statusGoal:"PAYMENT_PROVIDER_SETUP_READY_OR_MANUAL_ONLY",providerUrl:"https://www.mercadopago.com.br/developers"}),
item({id:"mercado_livre",label:"Mercado Livre",category:"MARKETPLACE",connectionModes:["OAUTH_SETUP","MANUAL_SELLER_LINK"],capabilities:["seller connection readiness","future affiliate/product catalog planning","manual listing planning"],blockedActions:["create listing","change listing","buy product","send buyer message","auto-affiliate posting"],requiredEnv:["MERCADO_LIVRE_CLIENT_ID_OPTIONAL","MERCADO_LIVRE_CLIENT_SECRET_OPTIONAL","MERCADO_LIVRE_REDIRECT_URI_OPTIONAL"],statusGoal:"MARKETPLACE_SETUP_READY_OR_MANUAL_ONLY",providerUrl:"https://developers.mercadolivre.com.br"}),
item({id:"metamask",label:"MetaMask",category:"WEB3_WALLET",connectionModes:["WALLET_ADDRESS_READ_ONLY","MANUAL_WALLET"],capabilities:["read wallet address manually","risk checklist","future wallet connect planning"],blockedActions:["seed phrase","private key","sign message","send transaction","claim reward","connect main wallet automatically"],requiredEnv:[],statusGoal:"WALLET_MANUAL_READ_ONLY",providerUrl:"https://metamask.io"}),
item({id:"walletconnect",label:"WalletConnect",category:"WEB3_WALLET",connectionModes:["PLANNED_P1","MANUAL_ONLY_P0"],capabilities:["future WalletConnect planning","wallet safety checklist"],blockedActions:["live connection","signing","transaction","claim","wallet drain risk"],requiredEnv:["WALLETCONNECT_PROJECT_ID_FUTURE_OPTIONAL"],statusGoal:"PLANNED_NOT_CONNECTED",providerUrl:"https://walletconnect.com"}),
item({id:"openrouter",label:"OpenRouter",category:"MODEL_ROUTER",connectionModes:["SERVER_ENV_KEY_MANUAL"],capabilities:["model router readiness","future model comparison","provider cost planning"],blockedActions:["store key in frontend","call paid models by default","auto-spend"],requiredEnv:["OPENROUTER_API_KEY_OPTIONAL"],statusGoal:"ENV_READY_OR_SETUP_REQUIRED",providerUrl:"https://openrouter.ai/settings/keys"}),
item({id:"huggingface",label:"Hugging Face",category:"MODEL_AND_DATASET_HUB",connectionModes:["SERVER_ENV_TOKEN_MANUAL","PUBLIC_READ_ONLY"],capabilities:["public model registry planning","token readiness","future embedding/RAG pack"],blockedActions:["store token in frontend","download large models automatically","call paid inference by default"],requiredEnv:["HF_TOKEN_OPTIONAL","HUGGINGFACE_TOKEN_OPTIONAL"],statusGoal:"PUBLIC_READY_OR_ENV_SETUP_REQUIRED",providerUrl:"https://huggingface.co/settings/tokens"}),
item({id:"anthropic",label:"Anthropic",category:"AI_PROVIDER_AND_MCP",connectionModes:["SERVER_ENV_KEY_MANUAL","MCP_MANUAL"],capabilities:["MCP planning","Claude provider readiness","future agent economy workflows"],blockedActions:["store key in frontend","call paid API automatically","install arbitrary MCP servers"],requiredEnv:["ANTHROPIC_API_KEY_OPTIONAL"],statusGoal:"ENV_READY_OR_SETUP_REQUIRED",providerUrl:"https://console.anthropic.com/settings/keys"}),
item({id:"openai",label:"OpenAI",category:"AI_PROVIDER",connectionModes:["SERVER_ENV_KEY_MANUAL"],capabilities:["provider readiness","future model routing"],blockedActions:["store key in frontend","call paid API automatically"],requiredEnv:["OPENAI_API_KEY_OPTIONAL"],statusGoal:"ENV_READY_OR_SETUP_REQUIRED",providerUrl:"https://platform.openai.com/api-keys"}),
item({id:"vercel",label:"Vercel",category:"DEPLOYMENT",connectionModes:["CLI_MANUAL","PROJECT_LINK_MANUAL","SERVER_ENV_TOKEN_OPTIONAL"],capabilities:["deployment status planning","manual CLI runbook","future read-only deploy connector"],blockedActions:["auto deploy","delete project","change env vars automatically"],requiredEnv:["VERCEL_TOKEN_OPTIONAL","VERCEL_TEAM_ID_OPTIONAL"],statusGoal:"CLI_READY_OR_SETUP_REQUIRED",providerUrl:"https://vercel.com/account/tokens"}),
item({id:"railway",label:"Railway",category:"DEPLOYMENT",connectionModes:["CLI_MANUAL","PROJECT_LINK_MANUAL","SERVER_ENV_TOKEN_OPTIONAL"],capabilities:["deployment status planning","manual CLI runbook","future read-only deploy connector"],blockedActions:["auto deploy","delete project","change env vars automatically"],requiredEnv:["RAILWAY_TOKEN_OPTIONAL","RAILWAY_PROJECT_ID_OPTIONAL"],statusGoal:"CLI_READY_OR_SETUP_REQUIRED",providerUrl:"https://railway.app/account/tokens"}),
item({id:"supabase",label:"Supabase",category:"DATABASE",connectionModes:["SERVER_ENV_READ_ONLY","CLI_MANUAL"],capabilities:["project readiness","RLS audit planning","future read-only metadata connector"],blockedActions:["service role in frontend","database writes","RLS mutation","schema migration"],requiredEnv:["SUPABASE_URL_OPTIONAL","SUPABASE_ANON_KEY_OPTIONAL","SUPABASE_SERVICE_ROLE_KEY_FORBIDDEN_IN_FRONTEND"],statusGoal:"READ_ONLY_READY_OR_SETUP_REQUIRED",providerUrl:"https://supabase.com/dashboard"}),
item({id:"web3_platforms",label:"Web3 Task Platforms",category:"TASK_AND_BOUNTY",connectionModes:["MANUAL_BROWSER"],capabilities:["Superteam/Zealy/Galxe/Layer3 manual task intake","manual submission pack planning"],blockedActions:["auto login","auto quest submit","wallet claim","captcha bypass"],requiredEnv:[],statusGoal:"MANUAL_BROWSER_READY",providerUrl:"https://zealy.io"}),
];
export const getConnectorRegistryItem = (id: string) => connectorRegistry.find((c) => c.id === id);
