import { sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

export const auditCaseStatus = pgEnum("audit_case_status", ["DRAFT", "OPEN", "IN_REVIEW", "READY_FOR_REPORT", "REPORTED", "CLOSED", "ARCHIVED"]);
export const auditAssetType = pgEnum("audit_asset_type", ["WEBSITE", "ECOMMERCE", "LANDING_PAGE", "GITHUB_REPOSITORY", "CODEBASE", "SUPABASE_PROJECT", "DEPLOYMENT", "API_BACKEND", "BUSINESS_FUNNEL", "CONTENT_PAGE", "OTHER"]);
export const auditModuleKey = pgEnum("audit_module_key", ["website_audit", "ecommerce_audit", "ux_checkout_audit", "seo_basic_audit", "tracking_pixel_audit", "security_basic_audit", "github_repository_audit", "codebase_audit", "supabase_database_audit", "deployment_audit", "api_backend_audit", "ai_automation_audit", "business_offer_audit", "funnel_audit", "content_landing_page_audit"]);
export const auditSeverity = pgEnum("audit_severity", ["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"]);
export const auditEvidenceType = pgEnum("audit_evidence_type", ["URL", "SCREENSHOT", "LOG_EXCERPT", "REPOSITORY_REFERENCE", "SCHEMA_REFERENCE", "REDACTED_CONFIG", "WORKFLOW_REFERENCE", "OPERATOR_NOTE", "OTHER"]);
export const auditReportType = pgEnum("audit_report_type", ["INTERNAL_BRIEF", "CLIENT_SUMMARY", "TECHNICAL_REPORT", "PROPOSAL_BRIEF", "EXECUTION_PLAN"]);
export const auditTaskStatus = pgEnum("audit_task_status", ["BACKLOG", "READY", "IN_PROGRESS", "BLOCKED", "DONE", "CANCELLED"]);
export const auditProposalStatus = pgEnum("audit_proposal_status", ["DRAFT", "READY_FOR_OPERATOR", "SENT_MANUALLY", "ACCEPTED", "DECLINED", "EXPIRED", "CANCELLED"]);
export const auditRevenueStatus = pgEnum("audit_revenue_status", ["ESTIMATED", "PROPOSED", "ACCEPTED", "PAID", "LOST", "REFUNDED", "CANCELLED"]);
export const auditConnectorStatus = pgEnum("audit_connector_status", ["NOT_CONFIGURED", "DEGRADED_SAFE", "READY_READ_ONLY", "RUNNING", "SUCCEEDED", "FAILED", "DISABLED"]);

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() };
const metadata = { metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`) };

export const auditClients = pgTable("audit_clients", {
  id: uuid("id").primaryKey().defaultRandom(), displayName: text("display_name").notNull(), externalReference: text("external_reference"), contactReference: text("contact_reference"), ...metadata, ...timestamps,
}, (t) => [index("audit_clients_display_name_idx").on(t.displayName), index("audit_clients_external_reference_idx").on(t.externalReference)]);

export const auditAssets = pgTable("audit_assets", {
  id: uuid("id").primaryKey().defaultRandom(), clientId: uuid("client_id").references(() => auditClients.id, { onDelete: "set null" }), type: auditAssetType("type").notNull(), label: text("label").notNull(), referenceUrl: text("reference_url"), externalReference: text("external_reference"), ...metadata, ...timestamps,
}, (t) => [index("audit_assets_client_id_idx").on(t.clientId), index("audit_assets_type_idx").on(t.type), index("audit_assets_reference_url_idx").on(t.referenceUrl)]);

export const auditCases = pgTable("audit_cases", {
  id: uuid("id").primaryKey().defaultRandom(), clientId: uuid("client_id").references(() => auditClients.id, { onDelete: "set null" }), assetId: uuid("asset_id").references(() => auditAssets.id, { onDelete: "set null" }), title: text("title").notNull(), status: auditCaseStatus("status").notNull().default("DRAFT"), priority: integer("priority").notNull().default(0), openedAt: timestamp("opened_at", { withTimezone: true }).notNull().defaultNow(), closedAt: timestamp("closed_at", { withTimezone: true }), ...metadata, ...timestamps,
}, (t) => [index("audit_cases_client_id_idx").on(t.clientId), index("audit_cases_asset_id_idx").on(t.assetId), index("audit_cases_status_idx").on(t.status), index("audit_cases_opened_at_idx").on(t.openedAt)]);

export const auditModules = pgTable("audit_modules", {
  id: uuid("id").primaryKey().defaultRandom(), key: auditModuleKey("key").notNull(), name: text("name").notNull(), category: text("category").notNull(), defaultWeight: integer("default_weight").notNull().default(1), enabled: boolean("enabled").notNull().default(true), safeMode: boolean("safe_mode").notNull().default(true), checklistItems: jsonb("checklist_items").notNull().default(sql`'[]'::jsonb`), riskSignals: jsonb("risk_signals").notNull().default(sql`'[]'::jsonb`), recommendedEvidenceTypes: jsonb("recommended_evidence_types").notNull().default(sql`'[]'::jsonb`), ...metadata, ...timestamps,
}, (t) => [uniqueIndex("audit_modules_key_uq").on(t.key), index("audit_modules_enabled_idx").on(t.enabled), index("audit_modules_category_idx").on(t.category)]);

export const auditChecklists = pgTable("audit_checklists", {
  id: uuid("id").primaryKey().defaultRandom(), moduleId: uuid("module_id").notNull().references(() => auditModules.id, { onDelete: "cascade" }), itemKey: text("item_key").notNull(), label: text("label").notNull(), weight: integer("weight").notNull().default(1), ...metadata, ...timestamps,
}, (t) => [uniqueIndex("audit_checklists_module_item_uq").on(t.moduleId, t.itemKey), index("audit_checklists_module_id_idx").on(t.moduleId)]);

export const auditFindings = pgTable("audit_findings", {
  id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").notNull().references(() => auditCases.id, { onDelete: "cascade" }), moduleKey: auditModuleKey("module_key"), title: text("title").notNull(), severity: auditSeverity("severity").notNull().default("MEDIUM"), summary: text("summary").notNull(), recommendation: text("recommendation"), status: text("status").notNull().default("OPEN"), ...metadata, ...timestamps,
}, (t) => [index("audit_findings_case_id_idx").on(t.caseId), index("audit_findings_module_key_idx").on(t.moduleKey), index("audit_findings_severity_idx").on(t.severity)]);

export const auditEvidences = pgTable("audit_evidences", {
  id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "cascade" }), findingId: uuid("finding_id").references(() => auditFindings.id, { onDelete: "cascade" }), type: auditEvidenceType("type").notNull(), title: text("title").notNull(), referenceUrl: text("reference_url"), redactedText: text("redacted_text"), capturedAt: timestamp("captured_at", { withTimezone: true }).notNull().defaultNow(), ...metadata, ...timestamps,
}, (t) => [index("audit_evidences_case_id_idx").on(t.caseId), index("audit_evidences_finding_id_idx").on(t.findingId), index("audit_evidences_type_idx").on(t.type)]);

export const auditScores = pgTable("audit_scores", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").notNull().references(() => auditCases.id, { onDelete: "cascade" }), moduleKey: auditModuleKey("module_key"), score: numeric("score", { precision: 5, scale: 2 }).notNull(), maxScore: numeric("max_score", { precision: 5, scale: 2 }).notNull().default("100"), rationale: text("rationale"), ...metadata, ...timestamps }, (t) => [index("audit_scores_case_id_idx").on(t.caseId), index("audit_scores_module_key_idx").on(t.moduleKey)]);
export const auditReports = pgTable("audit_reports", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").notNull().references(() => auditCases.id, { onDelete: "cascade" }), type: auditReportType("type").notNull(), title: text("title").notNull(), content: jsonb("content").notNull().default(sql`'{}'::jsonb`), generatedBy: text("generated_by").notNull().default("operator"), publishedAt: timestamp("published_at", { withTimezone: true }), ...metadata, ...timestamps }, (t) => [index("audit_reports_case_id_idx").on(t.caseId), index("audit_reports_type_idx").on(t.type)]);
export const auditTasks = pgTable("audit_tasks", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "cascade" }), findingId: uuid("finding_id").references(() => auditFindings.id, { onDelete: "set null" }), title: text("title").notNull(), status: auditTaskStatus("status").notNull().default("BACKLOG"), ownerReference: text("owner_reference"), dueAt: timestamp("due_at", { withTimezone: true }), ...metadata, ...timestamps }, (t) => [index("audit_tasks_case_id_idx").on(t.caseId), index("audit_tasks_finding_id_idx").on(t.findingId), index("audit_tasks_status_idx").on(t.status)]);
export const auditProposals = pgTable("audit_proposals", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "set null" }), taskId: uuid("task_id").references(() => auditTasks.id, { onDelete: "set null" }), title: text("title").notNull(), status: auditProposalStatus("status").notNull().default("DRAFT"), currency: text("currency").notNull().default("BRL"), amount: numeric("amount", { precision: 14, scale: 2 }), manualDeliveryReference: text("manual_delivery_reference"), ...metadata, ...timestamps }, (t) => [index("audit_proposals_case_id_idx").on(t.caseId), index("audit_proposals_task_id_idx").on(t.taskId), index("audit_proposals_status_idx").on(t.status)]);
export const auditRevenueEvents = pgTable("audit_revenue_events", { id: uuid("id").primaryKey().defaultRandom(), proposalId: uuid("proposal_id").references(() => auditProposals.id, { onDelete: "set null" }), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "set null" }), status: auditRevenueStatus("status").notNull(), currency: text("currency").notNull().default("BRL"), amount: numeric("amount", { precision: 14, scale: 2 }).notNull().default("0"), externalProofReference: text("external_proof_reference"), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(), ...metadata, ...timestamps }, (t) => [index("audit_revenue_events_proposal_id_idx").on(t.proposalId), index("audit_revenue_events_case_id_idx").on(t.caseId), index("audit_revenue_events_status_idx").on(t.status)]);
export const auditConnectorRuns = pgTable("audit_connector_runs", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "set null" }), connectorKey: text("connector_key").notNull(), status: auditConnectorStatus("status").notNull().default("NOT_CONFIGURED"), readOnly: boolean("read_only").notNull().default(true), startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(), finishedAt: timestamp("finished_at", { withTimezone: true }), ...metadata, ...timestamps }, (t) => [index("audit_connector_runs_case_id_idx").on(t.caseId), index("audit_connector_runs_connector_key_idx").on(t.connectorKey), index("audit_connector_runs_status_idx").on(t.status)]);
export const auditOperatorNotes = pgTable("audit_operator_notes", { id: uuid("id").primaryKey().defaultRandom(), caseId: uuid("case_id").references(() => auditCases.id, { onDelete: "cascade" }), findingId: uuid("finding_id").references(() => auditFindings.id, { onDelete: "set null" }), note: text("note").notNull(), operatorReference: text("operator_reference"), ...metadata, ...timestamps }, (t) => [index("audit_operator_notes_case_id_idx").on(t.caseId), index("audit_operator_notes_finding_id_idx").on(t.findingId)]);

export const insertAuditClientSchema = createInsertSchema(auditClients); export const selectAuditClientSchema = createSelectSchema(auditClients);
export const insertAuditCaseSchema = createInsertSchema(auditCases); export const selectAuditCaseSchema = createSelectSchema(auditCases);
export const insertAuditFindingSchema = createInsertSchema(auditFindings); export const selectAuditFindingSchema = createSelectSchema(auditFindings);
