import type { MonitorSnapshot } from "./types";

/**
 * ============================================================
 *  DADOS DEMO — claramente fictícios.
 *  Endereços, IDs e hashes abaixo NÃO são reais.
 *  Substituídos automaticamente quando o modo "live" estiver ativo.
 * ============================================================
 */

const DEMO_WALLET = "0xDEM0000000000000000000000000000000000GX3";
const DEMO_AGENT = "gxeon-agent-demo-01";
const DEMO_LISTING = "CLW-DEMO-48213";

export const demoSnapshot: MonitorSnapshot = {
  mode: "demo",
  generatedAt: "2026-09-18T00:40:00.000Z",
  source: "mock://gxeon-demo",
  identity: {
    demo: true,
    agentId: DEMO_AGENT,
    publicWallet: DEMO_WALLET,
    network: "Base (USDC)",
    listingId: DEMO_LISTING,
    transactionId: null,
    transactionHash: null,
    usdcBalance: 0,
    balanceCheckedAt: "2026-09-18T00:38:12.000Z",
  },
  line: {
    demo: true,
    id: "line-001",
    name: "Linha #1 — Primeiro payout Clawlancer",
    description:
      "Acompanhar uma única tarefa do claim ao payout verificado com evidência real.",
    startedAt: "2026-09-17T14:02:00.000Z",
    pipeline: [
      { stage: "claim", state: "done", at: "2026-09-17T14:02:00.000Z", note: "Claim enviado no listing." },
      { stage: "assigned", state: "done", at: "2026-09-17T16:45:00.000Z", note: "Requester aceitou o agente." },
      { stage: "delivery", state: "active", note: "Entrega em preparação (revisão manual pendente)." },
      { stage: "release", state: "pending" },
      { stage: "payment_verified", state: "pending" },
    ],
    releaseConfirmed: false,
    releaseTxHash: null,
    paymentVerified: false,
  },
  opportunities: [
    {
      demo: true,
      listingId: DEMO_LISTING,
      title: "Auditoria de prompts para agente de suporte",
      category: "AI Ops",
      rewardUsdc: 120,
      postedAt: "2026-09-17T09:10:00.000Z",
      deadlineAt: "2026-09-19T23:59:00.000Z",
      fitScore: 91,
      risk: "low",
      requesterReputation: 4.7,
      status: "claimed",
    },
    {
      demo: true,
      listingId: "CLW-DEMO-48377",
      title: "Scraper de dados públicos com relatório CSV",
      category: "Data",
      rewardUsdc: 85,
      postedAt: "2026-09-17T21:30:00.000Z",
      deadlineAt: "2026-09-20T12:00:00.000Z",
      fitScore: 78,
      risk: "medium",
      requesterReputation: 4.1,
      status: "watching",
    },
    {
      demo: true,
      listingId: "CLW-DEMO-48402",
      title: "Landing page SaaS (copy + layout)",
      category: "Web",
      rewardUsdc: 200,
      postedAt: "2026-09-18T00:05:00.000Z",
      fitScore: 66,
      risk: "medium",
      requesterReputation: 3.6,
      status: "open",
    },
    {
      demo: true,
      listingId: "CLW-DEMO-48155",
      title: "Bot de arbitragem on-chain",
      category: "DeFi",
      rewardUsdc: 450,
      postedAt: "2026-09-16T11:00:00.000Z",
      fitScore: 32,
      risk: "high",
      requesterReputation: 2.4,
      status: "open",
    },
  ],
  tasks: [
    {
      demo: true,
      id: "task-101",
      listingId: DEMO_LISTING,
      title: "Revisar entrega da auditoria de prompts",
      stage: "delivery",
      priority: "critical",
      rewardUsdc: 120,
      updatedAt: "2026-09-18T00:20:00.000Z",
      owner: DEMO_AGENT,
      needsManualGate: true,
    },
    {
      demo: true,
      id: "task-102",
      listingId: DEMO_LISTING,
      title: "Confirmar release e registrar tx hash",
      stage: "release",
      priority: "high",
      rewardUsdc: 120,
      updatedAt: "2026-09-18T00:20:00.000Z",
      owner: DEMO_AGENT,
      needsManualGate: true,
    },
    {
      demo: true,
      id: "task-103",
      listingId: "CLW-DEMO-48377",
      title: "Avaliar viabilidade do scraper (radar)",
      stage: "claim",
      priority: "normal",
      rewardUsdc: 85,
      updatedAt: "2026-09-17T22:00:00.000Z",
      owner: DEMO_AGENT,
      needsManualGate: false,
    },
  ],
  evidence: [
    {
      demo: true,
      id: "ev-1",
      at: "2026-09-17T13:58:00.000Z",
      kind: "system",
      title: "Monitor inicializado",
      detail: "Agente registrado no monitor. Nenhum segredo armazenado no frontend.",
      verified: true,
    },
    {
      demo: true,
      id: "ev-2",
      at: "2026-09-17T14:02:00.000Z",
      kind: "claim",
      title: "Claim enviado",
      detail: "Claim submetido ao listing de auditoria de prompts.",
      ref: { label: "Listing ID", value: DEMO_LISTING },
      verified: true,
    },
    {
      demo: true,
      id: "ev-3",
      at: "2026-09-17T16:45:00.000Z",
      kind: "assignment",
      title: "Agente atribuído",
      detail: "Requester aceitou o claim. Prazo definido para 19/09.",
      ref: { label: "Agent ID", value: DEMO_AGENT },
      verified: true,
    },
    {
      demo: true,
      id: "ev-4",
      at: "2026-09-18T00:20:00.000Z",
      kind: "manual_gate",
      title: "Gate manual: revisão da entrega",
      detail: "Entrega aguarda aprovação humana antes do envio. Nenhuma ação automática.",
      verified: false,
    },
    {
      demo: true,
      id: "ev-5",
      at: "2026-09-18T00:38:12.000Z",
      kind: "onchain",
      title: "Leitura de saldo USDC",
      detail: "Consulta somente-leitura da carteira pública. Saldo: 0,00 USDC.",
      ref: { label: "Public wallet", value: DEMO_WALLET },
      verified: true,
    },
  ],
  performance: {
    demo: true,
    totalVerifiedUsdc: 0,
    totalPendingUsdc: 120,
    tasksCompleted: 0,
    tasksInFlight: 2,
    avgCycleHours: 0,
    successRate: 0,
    series: [
      { date: "2026-09-12", pendingUsdc: 0, verifiedUsdc: 0 },
      { date: "2026-09-13", pendingUsdc: 0, verifiedUsdc: 0 },
      { date: "2026-09-14", pendingUsdc: 0, verifiedUsdc: 0 },
      { date: "2026-09-15", pendingUsdc: 0, verifiedUsdc: 0 },
      { date: "2026-09-16", pendingUsdc: 0, verifiedUsdc: 0 },
      { date: "2026-09-17", pendingUsdc: 120, verifiedUsdc: 0 },
      { date: "2026-09-18", pendingUsdc: 120, verifiedUsdc: 0 },
    ],
  },
};